// Code generated by capigen. DO NOT EDIT.

package performancehint

/*
#cgo LDFLAGS: -landroid
#include "android/performance_hint.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

var _ runtime.Error
var _ unsafe.Pointer

func APerformanceHint_closeSession(session *APerformanceHintSession) {
	csession, csessionAllocMap := (*C.APerformanceHintSession)(unsafe.Pointer(session)), cgoAllocsUnknown
	C.APerformanceHint_closeSession(csession)
	runtime.KeepAlive(csessionAllocMap)
}

func APerformanceHint_createSession(manager *APerformanceHintManager, threadIds *int32, size uint64, initialTargetWorkDurationNanos int64) *APerformanceHintSession {
	cmanager, cmanagerAllocMap := (*C.APerformanceHintManager)(unsafe.Pointer(manager)), cgoAllocsUnknown
	cthreadIds, cthreadIdsAllocMap := (*C.int)(unsafe.Pointer(threadIds)), cgoAllocsUnknown
	csize, csizeAllocMap := (C.uint64_t)(size), cgoAllocsUnknown
	cinitialTargetWorkDurationNanos, cinitialTargetWorkDurationNanosAllocMap := (C.int64_t)(initialTargetWorkDurationNanos), cgoAllocsUnknown
	__ret := C.APerformanceHint_createSession(cmanager, cthreadIds, csize, cinitialTargetWorkDurationNanos)
	runtime.KeepAlive(cinitialTargetWorkDurationNanosAllocMap)
	runtime.KeepAlive(csizeAllocMap)
	runtime.KeepAlive(cthreadIdsAllocMap)
	runtime.KeepAlive(cmanagerAllocMap)
	__v := *(**APerformanceHintSession)(unsafe.Pointer(&__ret))
	return __v
}

func APerformanceHint_getManager() *APerformanceHintManager {
	__ret := C.APerformanceHint_getManager()
	__v := *(**APerformanceHintManager)(unsafe.Pointer(&__ret))
	return __v
}

func APerformanceHint_getPreferredUpdateRateNanos(manager *APerformanceHintManager) int64 {
	cmanager, cmanagerAllocMap := (*C.APerformanceHintManager)(unsafe.Pointer(manager)), cgoAllocsUnknown
	__ret := C.APerformanceHint_getPreferredUpdateRateNanos(cmanager)
	runtime.KeepAlive(cmanagerAllocMap)
	__v := (int64)(__ret)
	return __v
}

func APerformanceHint_reportActualWorkDuration(session *APerformanceHintSession, actualDurationNanos int64) int32 {
	csession, csessionAllocMap := (*C.APerformanceHintSession)(unsafe.Pointer(session)), cgoAllocsUnknown
	cactualDurationNanos, cactualDurationNanosAllocMap := (C.int64_t)(actualDurationNanos), cgoAllocsUnknown
	__ret := C.APerformanceHint_reportActualWorkDuration(csession, cactualDurationNanos)
	runtime.KeepAlive(cactualDurationNanosAllocMap)
	runtime.KeepAlive(csessionAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APerformanceHint_reportActualWorkDuration2(session *APerformanceHintSession, workDuration *AWorkDuration) int32 {
	csession, csessionAllocMap := (*C.APerformanceHintSession)(unsafe.Pointer(session)), cgoAllocsUnknown
	cworkDuration, cworkDurationAllocMap := (*C.AWorkDuration)(unsafe.Pointer(workDuration)), cgoAllocsUnknown
	__ret := C.APerformanceHint_reportActualWorkDuration2(csession, cworkDuration)
	runtime.KeepAlive(cworkDurationAllocMap)
	runtime.KeepAlive(csessionAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APerformanceHint_setPreferPowerEfficiency(session *APerformanceHintSession, enabled bool) int32 {
	csession, csessionAllocMap := (*C.APerformanceHintSession)(unsafe.Pointer(session)), cgoAllocsUnknown
	cenabled, cenabledAllocMap := (C._Bool)(enabled), cgoAllocsUnknown
	__ret := C.APerformanceHint_setPreferPowerEfficiency(csession, cenabled)
	runtime.KeepAlive(cenabledAllocMap)
	runtime.KeepAlive(csessionAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APerformanceHint_setThreads(session *APerformanceHintSession, threadIds *Pid_t, size uint64) int32 {
	csession, csessionAllocMap := (*C.APerformanceHintSession)(unsafe.Pointer(session)), cgoAllocsUnknown
	cthreadIds, cthreadIdsAllocMap := (*C.pid_t)(unsafe.Pointer(threadIds)), cgoAllocsUnknown
	csize, csizeAllocMap := (C.uint64_t)(size), cgoAllocsUnknown
	__ret := C.APerformanceHint_setThreads(csession, cthreadIds, csize)
	runtime.KeepAlive(csizeAllocMap)
	runtime.KeepAlive(cthreadIdsAllocMap)
	runtime.KeepAlive(csessionAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APerformanceHint_updateTargetWorkDuration(session *APerformanceHintSession, targetDurationNanos int64) int32 {
	csession, csessionAllocMap := (*C.APerformanceHintSession)(unsafe.Pointer(session)), cgoAllocsUnknown
	ctargetDurationNanos, ctargetDurationNanosAllocMap := (C.int64_t)(targetDurationNanos), cgoAllocsUnknown
	__ret := C.APerformanceHint_updateTargetWorkDuration(csession, ctargetDurationNanos)
	runtime.KeepAlive(ctargetDurationNanosAllocMap)
	runtime.KeepAlive(csessionAllocMap)
	__v := (int32)(__ret)
	return __v
}

func AWorkDuration_create() *AWorkDuration {
	__ret := C.AWorkDuration_create()
	__v := *(**AWorkDuration)(unsafe.Pointer(&__ret))
	return __v
}

func AWorkDuration_release(aWorkDuration *AWorkDuration) {
	caWorkDuration, caWorkDurationAllocMap := (*C.AWorkDuration)(unsafe.Pointer(aWorkDuration)), cgoAllocsUnknown
	C.AWorkDuration_release(caWorkDuration)
	runtime.KeepAlive(caWorkDurationAllocMap)
}

func AWorkDuration_setActualCpuDurationNanos(aWorkDuration *AWorkDuration, actualCpuDurationNanos int64) {
	caWorkDuration, caWorkDurationAllocMap := (*C.AWorkDuration)(unsafe.Pointer(aWorkDuration)), cgoAllocsUnknown
	cactualCpuDurationNanos, cactualCpuDurationNanosAllocMap := (C.int64_t)(actualCpuDurationNanos), cgoAllocsUnknown
	C.AWorkDuration_setActualCpuDurationNanos(caWorkDuration, cactualCpuDurationNanos)
	runtime.KeepAlive(cactualCpuDurationNanosAllocMap)
	runtime.KeepAlive(caWorkDurationAllocMap)
}

func AWorkDuration_setActualGpuDurationNanos(aWorkDuration *AWorkDuration, actualGpuDurationNanos int64) {
	caWorkDuration, caWorkDurationAllocMap := (*C.AWorkDuration)(unsafe.Pointer(aWorkDuration)), cgoAllocsUnknown
	cactualGpuDurationNanos, cactualGpuDurationNanosAllocMap := (C.int64_t)(actualGpuDurationNanos), cgoAllocsUnknown
	C.AWorkDuration_setActualGpuDurationNanos(caWorkDuration, cactualGpuDurationNanos)
	runtime.KeepAlive(cactualGpuDurationNanosAllocMap)
	runtime.KeepAlive(caWorkDurationAllocMap)
}

func AWorkDuration_setActualTotalDurationNanos(aWorkDuration *AWorkDuration, actualTotalDurationNanos int64) {
	caWorkDuration, caWorkDurationAllocMap := (*C.AWorkDuration)(unsafe.Pointer(aWorkDuration)), cgoAllocsUnknown
	cactualTotalDurationNanos, cactualTotalDurationNanosAllocMap := (C.int64_t)(actualTotalDurationNanos), cgoAllocsUnknown
	C.AWorkDuration_setActualTotalDurationNanos(caWorkDuration, cactualTotalDurationNanos)
	runtime.KeepAlive(cactualTotalDurationNanosAllocMap)
	runtime.KeepAlive(caWorkDurationAllocMap)
}

func AWorkDuration_setWorkPeriodStartTimestampNanos(aWorkDuration *AWorkDuration, workPeriodStartTimestampNanos int64) {
	caWorkDuration, caWorkDurationAllocMap := (*C.AWorkDuration)(unsafe.Pointer(aWorkDuration)), cgoAllocsUnknown
	cworkPeriodStartTimestampNanos, cworkPeriodStartTimestampNanosAllocMap := (C.int64_t)(workPeriodStartTimestampNanos), cgoAllocsUnknown
	C.AWorkDuration_setWorkPeriodStartTimestampNanos(caWorkDuration, cworkPeriodStartTimestampNanos)
	runtime.KeepAlive(cworkPeriodStartTimestampNanosAllocMap)
	runtime.KeepAlive(caWorkDurationAllocMap)
}
