// Code generated by capigen. DO NOT EDIT.

package performancehint

/*
#cgo LDFLAGS: -landroid
#include "android/performance_hint.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

type APerformanceHintManager C.APerformanceHintManager

type APerformanceHintSession C.APerformanceHintSession

type AWorkDuration C.AWorkDuration

type Pid_t C.pid_t
