// Code generated by cligen. DO NOT EDIT.

package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

var binderCmd = &cobra.Command{
	Use:   "binder",
	Short: "binder NDK module",
}

var binderErrorCmd = &cobra.Command{
	Use:   "error",
	Short: "Error operations",
}

var binderErrorErrorCmd = &cobra.Command{
	Use:   "error",
	Short: "Error.Error()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

func init() {
	binderCmd.AddCommand(binderErrorCmd)
	binderErrorCmd.AddCommand(binderErrorErrorCmd)
	rootCmd.AddCommand(binderCmd)
}
