// Code generated by cligen. DO NOT EDIT.

package main

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/xaionaro-go/ndk/camera"
)

var cameraCmd = &cobra.Command{
	Use:   "camera",
	Short: "camera NDK module",
}

var cameraCaptureSessionCmd = &cobra.Command{
	Use:   "capture-session",
	Short: "CaptureSession operations",
}

var cameraDeviceCmd = &cobra.Command{
	Use:   "device",
	Short: "Device operations",
}

var cameraErrorCmd = &cobra.Command{
	Use:   "error",
	Short: "Error operations",
}

var cameraManagerCmd = &cobra.Command{
	Use:   "manager",
	Short: "Manager operations",
}

var cameraMetadataCmd = &cobra.Command{
	Use:   "metadata",
	Short: "Metadata operations",
}

var cameraSessionOutputContainerCmd = &cobra.Command{
	Use:   "session-output-container",
	Short: "SessionOutputContainer operations",
}

var cameraCaptureSessionStopRepeatingCmd = &cobra.Command{
	Use:   "stop-repeating",
	Short: "CaptureSession.StopRepeating()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var cameraDeviceCreateCaptureRequestCmd = &cobra.Command{
	Use:   "create-capture-request",
	Short: "Device.CreateCaptureRequest()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var cameraErrorErrorCmd = &cobra.Command{
	Use:   "error",
	Short: "Error.Error()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var cameraManagerNewCmd = &cobra.Command{
	Use:   "new",
	Short: "Create Manager",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj := camera.NewManager()
		defer obj.Close()
		fmt.Println("created successfully")
		return nil
	},
}

var cameraManagerGetCameraCharacteristicsCmd = &cobra.Command{
	Use:   "get-camera-characteristics",
	Short: "Manager.GetCameraCharacteristics()",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj := camera.NewManager()
		defer obj.Close()
		cameraID, _ := cmd.Flags().GetString("camera-id")
		result, err := obj.GetCameraCharacteristics(cameraID)
		if err != nil {
			return err
		}
		fmt.Println(result)
		return nil
	},
}

var cameraManagerCameraIDListCmd = &cobra.Command{
	Use:   "camera-id-list",
	Short: "Manager.CameraIDList()",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj := camera.NewManager()
		defer obj.Close()
		result, err := obj.CameraIDList()
		if err != nil {
			return err
		}
		fmt.Println(result)
		return nil
	},
}

var cameraMetadataI32AtCmd = &cobra.Command{
	Use:   "i32-at",
	Short: "Metadata.I32At()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var cameraMetadataI32CountCmd = &cobra.Command{
	Use:   "i32-count",
	Short: "Metadata.I32Count()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var cameraSessionOutputContainerNewCmd = &cobra.Command{
	Use:   "new",
	Short: "Create SessionOutputContainer",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj, err := camera.NewSessionOutputContainer()
		if err != nil {
			return err
		}
		defer obj.Close()
		fmt.Println("created successfully")
		return nil
	},
}

func init() {
	cameraManagerGetCameraCharacteristicsCmd.Flags().String("camera-id", "", "cameraID")
	cameraCmd.AddCommand(cameraCaptureSessionCmd)
	cameraCmd.AddCommand(cameraDeviceCmd)
	cameraCmd.AddCommand(cameraErrorCmd)
	cameraCmd.AddCommand(cameraManagerCmd)
	cameraCmd.AddCommand(cameraMetadataCmd)
	cameraCmd.AddCommand(cameraSessionOutputContainerCmd)
	cameraCaptureSessionCmd.AddCommand(cameraCaptureSessionStopRepeatingCmd)
	cameraDeviceCmd.AddCommand(cameraDeviceCreateCaptureRequestCmd)
	cameraErrorCmd.AddCommand(cameraErrorErrorCmd)
	cameraManagerCmd.AddCommand(cameraManagerNewCmd)
	cameraManagerCmd.AddCommand(cameraManagerGetCameraCharacteristicsCmd)
	cameraManagerCmd.AddCommand(cameraManagerCameraIDListCmd)
	cameraMetadataCmd.AddCommand(cameraMetadataI32AtCmd)
	cameraMetadataCmd.AddCommand(cameraMetadataI32CountCmd)
	cameraSessionOutputContainerCmd.AddCommand(cameraSessionOutputContainerNewCmd)
	rootCmd.AddCommand(cameraCmd)
}
