// Code generated by cligen. DO NOT EDIT.

package main

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/xaionaro-go/ndk/egl"
)

var eglCmd = &cobra.Command{
	Use:   "egl",
	Short: "egl NDK module",
}

var eglGetCurrentContextCmd = &cobra.Command{
	Use:   "get-current-context",
	Short: "egl.GetCurrentContext()",
	RunE: func(cmd *cobra.Command, args []string) error {
		result := egl.GetCurrentContext()
		fmt.Println(result)
		return nil
	},
}

var eglGetCurrentDisplayCmd = &cobra.Command{
	Use:   "get-current-display",
	Short: "egl.GetCurrentDisplay()",
	RunE: func(cmd *cobra.Command, args []string) error {
		result := egl.GetCurrentDisplay()
		fmt.Println(result)
		return nil
	},
}

var eglGetErrorCmd = &cobra.Command{
	Use:   "get-error",
	Short: "egl.GetError()",
	RunE: func(cmd *cobra.Command, args []string) error {
		result := egl.GetError()
		fmt.Println(result)
		return nil
	},
}

var eglQueryAPICmd = &cobra.Command{
	Use:   "query-api",
	Short: "egl.QueryAPI()",
	RunE: func(cmd *cobra.Command, args []string) error {
		result := egl.QueryAPI()
		fmt.Println(result)
		return nil
	},
}

var eglReleaseThreadCmd = &cobra.Command{
	Use:   "release-thread",
	Short: "egl.ReleaseThread()",
	RunE: func(cmd *cobra.Command, args []string) error {
		result := egl.ReleaseThread()
		fmt.Println(result)
		return nil
	},
}

var eglWaitGLCmd = &cobra.Command{
	Use:   "wait-gl",
	Short: "egl.WaitGL()",
	RunE: func(cmd *cobra.Command, args []string) error {
		result := egl.WaitGL()
		fmt.Println(result)
		return nil
	},
}

func init() {
	eglCmd.AddCommand(eglGetCurrentContextCmd)
	eglCmd.AddCommand(eglGetCurrentDisplayCmd)
	eglCmd.AddCommand(eglGetErrorCmd)
	eglCmd.AddCommand(eglQueryAPICmd)
	eglCmd.AddCommand(eglReleaseThreadCmd)
	eglCmd.AddCommand(eglWaitGLCmd)
	rootCmd.AddCommand(eglCmd)
}
