// Code generated by cligen. DO NOT EDIT.

package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

var gameactivityCmd = &cobra.Command{
	Use:   "gameactivity",
	Short: "gameactivity NDK module",
}

var gameactivityActivityCmd = &cobra.Command{
	Use:   "activity",
	Short: "Activity operations",
}

var gameactivityPointerAxesCmd = &cobra.Command{
	Use:   "pointer-axes",
	Short: "PointerAxes operations",
}

var gameactivityActivityVMCmd = &cobra.Command{
	Use:   "vm",
	Short: "Activity.VM()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityActivityEnvCmd = &cobra.Command{
	Use:   "env",
	Short: "Activity.Env()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityActivityJavaGameActivityCmd = &cobra.Command{
	Use:   "java-game-activity",
	Short: "Activity.JavaGameActivity()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityActivitySDKVersionCmd = &cobra.Command{
	Use:   "sdk-version",
	Short: "Activity.SDKVersion()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityActivityInternalDataPathCmd = &cobra.Command{
	Use:   "internal-data-path",
	Short: "Activity.InternalDataPath()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityActivityExternalDataPathCmd = &cobra.Command{
	Use:   "external-data-path",
	Short: "Activity.ExternalDataPath()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityActivityOBBPathCmd = &cobra.Command{
	Use:   "obb-path",
	Short: "Activity.OBBPath()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityActivityAssetManagerCmd = &cobra.Command{
	Use:   "asset-manager",
	Short: "Activity.AssetManager()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityActivityInstanceCmd = &cobra.Command{
	Use:   "instance",
	Short: "Activity.Instance()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityActivityFinishCmd = &cobra.Command{
	Use:   "finish",
	Short: "Activity.Finish()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityActivitySetWindowFlagsCmd = &cobra.Command{
	Use:   "set-window-flags",
	Short: "Activity.SetWindowFlags()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityActivityShowSoftInputCmd = &cobra.Command{
	Use:   "show-soft-input",
	Short: "Activity.ShowSoftInput()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityActivityHideSoftInputCmd = &cobra.Command{
	Use:   "hide-soft-input",
	Short: "Activity.HideSoftInput()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityActivitySetImeEditorInfoCmd = &cobra.Command{
	Use:   "set-ime-editor-info",
	Short: "Activity.SetImeEditorInfo()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityActivityGetWindowInsetsCmd = &cobra.Command{
	Use:   "get-window-insets",
	Short: "Activity.GetWindowInsets()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityPointerAxesXCmd = &cobra.Command{
	Use:   "x",
	Short: "PointerAxes.X()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var gameactivityPointerAxesYCmd = &cobra.Command{
	Use:   "y",
	Short: "PointerAxes.Y()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

func init() {
	gameactivityCmd.AddCommand(gameactivityActivityCmd)
	gameactivityCmd.AddCommand(gameactivityPointerAxesCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivityVMCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivityEnvCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivityJavaGameActivityCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivitySDKVersionCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivityInternalDataPathCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivityExternalDataPathCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivityOBBPathCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivityAssetManagerCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivityInstanceCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivityFinishCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivitySetWindowFlagsCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivityShowSoftInputCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivityHideSoftInputCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivitySetImeEditorInfoCmd)
	gameactivityActivityCmd.AddCommand(gameactivityActivityGetWindowInsetsCmd)
	gameactivityPointerAxesCmd.AddCommand(gameactivityPointerAxesXCmd)
	gameactivityPointerAxesCmd.AddCommand(gameactivityPointerAxesYCmd)
	rootCmd.AddCommand(gameactivityCmd)
}
