// Code generated by cligen. DO NOT EDIT.

package main

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/AndroidGoLab/ndk/gles3"
)

var gles3Cmd = &cobra.Command{
	Use:   "gles3",
	Short: "gles3 NDK module",
}

var gles3BeginTransformFeedbackCmd = &cobra.Command{
	Use:   "begin-transform-feedback",
	Short: "gles3.BeginTransformFeedback()",
	RunE: func(cmd *cobra.Command, args []string) error {
		primitiveMode, _ := cmd.Flags().GetUint32("primitive-mode")
		gles3.BeginTransformFeedback(gles3.GLenum(primitiveMode))
		fmt.Println("ok")
		return nil
	},
}

var gles3EndQueryCmd = &cobra.Command{
	Use:   "end-query",
	Short: "gles3.EndQuery()",
	RunE: func(cmd *cobra.Command, args []string) error {
		target, _ := cmd.Flags().GetUint32("target")
		gles3.EndQuery(gles3.GLenum(target))
		fmt.Println("ok")
		return nil
	},
}

var gles3EndTransformFeedbackCmd = &cobra.Command{
	Use:   "end-transform-feedback",
	Short: "gles3.EndTransformFeedback()",
	RunE: func(cmd *cobra.Command, args []string) error {
		gles3.EndTransformFeedback()
		fmt.Println("ok")
		return nil
	},
}

var gles3FenceSyncCmd = &cobra.Command{
	Use:   "fence-sync",
	Short: "gles3.FenceSync()",
	RunE: func(cmd *cobra.Command, args []string) error {
		condition, _ := cmd.Flags().GetUint32("condition")
		flags, _ := cmd.Flags().GetUint32("flags")
		result := gles3.FenceSync(gles3.GLenum(condition), gles3.GLbitfield(flags))
		fmt.Println(result)
		return nil
	},
}

var gles3GlFinishCmd = &cobra.Command{
	Use:   "gl-finish",
	Short: "gles3.GlFinish()",
	RunE: func(cmd *cobra.Command, args []string) error {
		gles3.GlFinish()
		fmt.Println("ok")
		return nil
	},
}

var gles3GlFlushCmd = &cobra.Command{
	Use:   "gl-flush",
	Short: "gles3.GlFlush()",
	RunE: func(cmd *cobra.Command, args []string) error {
		gles3.GlFlush()
		fmt.Println("ok")
		return nil
	},
}

var gles3GetStringCmd = &cobra.Command{
	Use:   "get-string",
	Short: "gles3.GetString()",
	RunE: func(cmd *cobra.Command, args []string) error {
		name, _ := cmd.Flags().GetUint32("name")
		result := gles3.GetString(gles3.GLenum(name))
		fmt.Println(result)
		return nil
	},
}

var gles3GlPauseTransformFeedbackCmd = &cobra.Command{
	Use:   "gl-pause-transform-feedback",
	Short: "gles3.GlPauseTransformFeedback()",
	RunE: func(cmd *cobra.Command, args []string) error {
		gles3.GlPauseTransformFeedback()
		fmt.Println("ok")
		return nil
	},
}

var gles3ReadBufferCmd = &cobra.Command{
	Use:   "read-buffer",
	Short: "gles3.ReadBuffer()",
	RunE: func(cmd *cobra.Command, args []string) error {
		src, _ := cmd.Flags().GetUint32("src")
		gles3.ReadBuffer(gles3.GLenum(src))
		fmt.Println("ok")
		return nil
	},
}

var gles3GlReleaseShaderCompilerCmd = &cobra.Command{
	Use:   "gl-release-shader-compiler",
	Short: "gles3.GlReleaseShaderCompiler()",
	RunE: func(cmd *cobra.Command, args []string) error {
		gles3.GlReleaseShaderCompiler()
		fmt.Println("ok")
		return nil
	},
}

var gles3GlResumeTransformFeedbackCmd = &cobra.Command{
	Use:   "gl-resume-transform-feedback",
	Short: "gles3.GlResumeTransformFeedback()",
	RunE: func(cmd *cobra.Command, args []string) error {
		gles3.GlResumeTransformFeedback()
		fmt.Println("ok")
		return nil
	},
}

var gles3UnmapBufferCmd = &cobra.Command{
	Use:   "unmap-buffer",
	Short: "gles3.UnmapBuffer()",
	RunE: func(cmd *cobra.Command, args []string) error {
		target, _ := cmd.Flags().GetUint32("target")
		result := gles3.UnmapBuffer(gles3.GLenum(target))
		fmt.Println(result)
		return nil
	},
}

func init() {
	gles3BeginTransformFeedbackCmd.Flags().Uint32("primitive-mode", 0, "primitiveMode")
	gles3EndQueryCmd.Flags().Uint32("target", 0, "target")
	gles3FenceSyncCmd.Flags().Uint32("condition", 0, "condition")
	gles3FenceSyncCmd.Flags().Uint32("flags", 0, "flags")
	gles3GetStringCmd.Flags().Uint32("name", 0, "name")
	gles3ReadBufferCmd.Flags().Uint32("src", 0, "src")
	gles3UnmapBufferCmd.Flags().Uint32("target", 0, "target")
	gles3Cmd.AddCommand(gles3BeginTransformFeedbackCmd)
	gles3Cmd.AddCommand(gles3EndQueryCmd)
	gles3Cmd.AddCommand(gles3EndTransformFeedbackCmd)
	gles3Cmd.AddCommand(gles3FenceSyncCmd)
	gles3Cmd.AddCommand(gles3GlFinishCmd)
	gles3Cmd.AddCommand(gles3GlFlushCmd)
	gles3Cmd.AddCommand(gles3GetStringCmd)
	gles3Cmd.AddCommand(gles3GlPauseTransformFeedbackCmd)
	gles3Cmd.AddCommand(gles3ReadBufferCmd)
	gles3Cmd.AddCommand(gles3GlReleaseShaderCompilerCmd)
	gles3Cmd.AddCommand(gles3GlResumeTransformFeedbackCmd)
	gles3Cmd.AddCommand(gles3UnmapBufferCmd)
	rootCmd.AddCommand(gles3Cmd)
}
