// Code generated by cligen. DO NOT EDIT.

package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

var imageCmd = &cobra.Command{
	Use:   "image",
	Short: "image NDK module",
}

var imageDecoderCmd = &cobra.Command{
	Use:   "decoder",
	Short: "Decoder operations",
}

var imageErrorCmd = &cobra.Command{
	Use:   "error",
	Short: "Error operations",
}

var imageDecoderMinimumStrideCmd = &cobra.Command{
	Use:   "minimum-stride",
	Short: "Decoder.MinimumStride()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var imageDecoderSetTargetSizeCmd = &cobra.Command{
	Use:   "set-target-size",
	Short: "Decoder.SetTargetSize()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var imageErrorErrorCmd = &cobra.Command{
	Use:   "error",
	Short: "Error.Error()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

func init() {
	imageCmd.AddCommand(imageDecoderCmd)
	imageCmd.AddCommand(imageErrorCmd)
	imageDecoderCmd.AddCommand(imageDecoderMinimumStrideCmd)
	imageDecoderCmd.AddCommand(imageDecoderSetTargetSizeCmd)
	imageErrorCmd.AddCommand(imageErrorErrorCmd)
	rootCmd.AddCommand(imageCmd)
}
