// Code generated by cligen. DO NOT EDIT.

package main

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/xaionaro-go/ndk/media"
)

var mediaCmd = &cobra.Command{
	Use:   "media",
	Short: "media NDK module",
}

var mediaCodecCmd = &cobra.Command{
	Use:   "codec",
	Short: "Codec operations",
}

var mediaErrorCmd = &cobra.Command{
	Use:   "error",
	Short: "Error operations",
}

var mediaExtractorCmd = &cobra.Command{
	Use:   "extractor",
	Short: "Extractor operations",
}

var mediaFormatCmd = &cobra.Command{
	Use:   "format",
	Short: "Format operations",
}

var mediaImageReaderCmd = &cobra.Command{
	Use:   "image-reader",
	Short: "ImageReader operations",
}

var mediaMuxerCmd = &cobra.Command{
	Use:   "muxer",
	Short: "Muxer operations",
}

var mediaNewDecoderCmd = &cobra.Command{
	Use:   "new-decoder",
	Short: "media.NewDecoder()",
	RunE: func(cmd *cobra.Command, args []string) error {
		mime_type, _ := cmd.Flags().GetString("mime_type")
		result := media.NewDecoder(mime_type)
		fmt.Println(result)
		return nil
	},
}

var mediaNewEncoderCmd = &cobra.Command{
	Use:   "new-encoder",
	Short: "media.NewEncoder()",
	RunE: func(cmd *cobra.Command, args []string) error {
		mime_type, _ := cmd.Flags().GetString("mime_type")
		result := media.NewEncoder(mime_type)
		fmt.Println(result)
		return nil
	},
}

var mediaCodecFlushCmd = &cobra.Command{
	Use:   "flush",
	Short: "Codec.Flush()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var mediaCodecReleaseOutputBufferCmd = &cobra.Command{
	Use:   "release-output-buffer",
	Short: "Codec.ReleaseOutputBuffer()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var mediaCodecStartCmd = &cobra.Command{
	Use:   "start",
	Short: "Codec.Start()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var mediaCodecStopCmd = &cobra.Command{
	Use:   "stop",
	Short: "Codec.Stop()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var mediaErrorErrorCmd = &cobra.Command{
	Use:   "error",
	Short: "Error.Error()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var mediaExtractorNewCmd = &cobra.Command{
	Use:   "new",
	Short: "Create Extractor",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj := media.NewExtractor()
		defer obj.Close()
		fmt.Println("created successfully")
		return nil
	},
}

var mediaExtractorSampleTimeCmd = &cobra.Command{
	Use:   "sample-time",
	Short: "Extractor.SampleTime()",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj := media.NewExtractor()
		defer obj.Close()
		result := obj.SampleTime()
		fmt.Println(result)
		return nil
	},
}

var mediaExtractorTrackCountCmd = &cobra.Command{
	Use:   "track-count",
	Short: "Extractor.TrackCount()",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj := media.NewExtractor()
		defer obj.Close()
		result := obj.TrackCount()
		fmt.Println(result)
		return nil
	},
}

var mediaExtractorSelectTrackCmd = &cobra.Command{
	Use:   "select-track",
	Short: "Extractor.SelectTrack()",
	RunE: func(cmd *cobra.Command, args []string) error {
		idx, _ := cmd.Flags().GetUint64("idx")
		obj := media.NewExtractor()
		defer obj.Close()
		err := obj.SelectTrack(idx)
		if err != nil {
			return err
		}
		fmt.Println("ok")
		return nil
	},
}

var mediaFormatNewCmd = &cobra.Command{
	Use:   "new",
	Short: "Create Format",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj := media.NewFormat()
		defer obj.Close()
		fmt.Println("created successfully")
		return nil
	},
}

var mediaFormatSetInt32Cmd = &cobra.Command{
	Use:   "set-int32",
	Short: "Format.SetInt32()",
	RunE: func(cmd *cobra.Command, args []string) error {
		name, _ := cmd.Flags().GetString("name")
		value, _ := cmd.Flags().GetInt32("value")
		obj := media.NewFormat()
		defer obj.Close()
		result := obj.SetInt32(name, value)
		fmt.Println(result)
		return nil
	},
}

var mediaFormatSetStringCmd = &cobra.Command{
	Use:   "set-string",
	Short: "Format.SetString()",
	RunE: func(cmd *cobra.Command, args []string) error {
		name, _ := cmd.Flags().GetString("name")
		value, _ := cmd.Flags().GetString("value")
		obj := media.NewFormat()
		defer obj.Close()
		result := obj.SetString(name, value)
		fmt.Println(result)
		return nil
	},
}

var mediaImageReaderAcquireLatestImageCmd = &cobra.Command{
	Use:   "acquire-latest-image",
	Short: "ImageReader.AcquireLatestImage()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var mediaImageReaderAcquireNextImageCmd = &cobra.Command{
	Use:   "acquire-next-image",
	Short: "ImageReader.AcquireNextImage()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var mediaImageReaderWindowCmd = &cobra.Command{
	Use:   "window",
	Short: "ImageReader.Window()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var mediaMuxerStartCmd = &cobra.Command{
	Use:   "start",
	Short: "Muxer.Start()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var mediaMuxerStopCmd = &cobra.Command{
	Use:   "stop",
	Short: "Muxer.Stop()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

func init() {
	mediaNewDecoderCmd.Flags().String("mime_type", "", "mime_type")
	mediaNewEncoderCmd.Flags().String("mime_type", "", "mime_type")
	mediaExtractorSelectTrackCmd.Flags().Uint64("idx", 0, "idx")
	mediaFormatSetInt32Cmd.Flags().String("name", "", "name")
	mediaFormatSetInt32Cmd.Flags().Int32("value", 0, "value")
	mediaFormatSetStringCmd.Flags().String("name", "", "name")
	mediaFormatSetStringCmd.Flags().String("value", "", "value")
	mediaCmd.AddCommand(mediaCodecCmd)
	mediaCmd.AddCommand(mediaErrorCmd)
	mediaCmd.AddCommand(mediaExtractorCmd)
	mediaCmd.AddCommand(mediaFormatCmd)
	mediaCmd.AddCommand(mediaImageReaderCmd)
	mediaCmd.AddCommand(mediaMuxerCmd)
	mediaCmd.AddCommand(mediaNewDecoderCmd)
	mediaCmd.AddCommand(mediaNewEncoderCmd)
	mediaCodecCmd.AddCommand(mediaCodecFlushCmd)
	mediaCodecCmd.AddCommand(mediaCodecReleaseOutputBufferCmd)
	mediaCodecCmd.AddCommand(mediaCodecStartCmd)
	mediaCodecCmd.AddCommand(mediaCodecStopCmd)
	mediaErrorCmd.AddCommand(mediaErrorErrorCmd)
	mediaExtractorCmd.AddCommand(mediaExtractorNewCmd)
	mediaExtractorCmd.AddCommand(mediaExtractorSampleTimeCmd)
	mediaExtractorCmd.AddCommand(mediaExtractorTrackCountCmd)
	mediaExtractorCmd.AddCommand(mediaExtractorSelectTrackCmd)
	mediaFormatCmd.AddCommand(mediaFormatNewCmd)
	mediaFormatCmd.AddCommand(mediaFormatSetInt32Cmd)
	mediaFormatCmd.AddCommand(mediaFormatSetStringCmd)
	mediaImageReaderCmd.AddCommand(mediaImageReaderAcquireLatestImageCmd)
	mediaImageReaderCmd.AddCommand(mediaImageReaderAcquireNextImageCmd)
	mediaImageReaderCmd.AddCommand(mediaImageReaderWindowCmd)
	mediaMuxerCmd.AddCommand(mediaMuxerStartCmd)
	mediaMuxerCmd.AddCommand(mediaMuxerStopCmd)
	rootCmd.AddCommand(mediaCmd)
}
