// Code generated by cligen. DO NOT EDIT.

package main

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/xaionaro-go/ndk/nnapi"
)

var nnapiCmd = &cobra.Command{
	Use:   "nnapi",
	Short: "nnapi NDK module",
}

var nnapiCompilationCmd = &cobra.Command{
	Use:   "compilation",
	Short: "Compilation operations",
}

var nnapiErrorCmd = &cobra.Command{
	Use:   "error",
	Short: "Error operations",
}

var nnapiEventCmd = &cobra.Command{
	Use:   "event",
	Short: "Event operations",
}

var nnapiExecutionCmd = &cobra.Command{
	Use:   "execution",
	Short: "Execution operations",
}

var nnapiModelCmd = &cobra.Command{
	Use:   "model",
	Short: "Model operations",
}

var nnapiCompilationNewBurstCmd = &cobra.Command{
	Use:   "new-burst",
	Short: "Compilation.NewBurst()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var nnapiCompilationFinishCmd = &cobra.Command{
	Use:   "finish",
	Short: "Compilation.Finish()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var nnapiCompilationSetPreferenceCmd = &cobra.Command{
	Use:   "set-preference",
	Short: "Compilation.SetPreference()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var nnapiCompilationSetPriorityCmd = &cobra.Command{
	Use:   "set-priority",
	Short: "Compilation.SetPriority()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var nnapiCompilationSetTimeoutCmd = &cobra.Command{
	Use:   "set-timeout",
	Short: "Compilation.SetTimeout()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var nnapiCompilationNewExecutionCmd = &cobra.Command{
	Use:   "new-execution",
	Short: "Compilation.NewExecution()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var nnapiErrorErrorCmd = &cobra.Command{
	Use:   "error",
	Short: "Error.Error()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var nnapiEventWaitCmd = &cobra.Command{
	Use:   "wait",
	Short: "Event.Wait()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var nnapiExecutionComputeCmd = &cobra.Command{
	Use:   "compute",
	Short: "Execution.Compute()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var nnapiExecutionSetMeasureTimingCmd = &cobra.Command{
	Use:   "set-measure-timing",
	Short: "Execution.SetMeasureTiming()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var nnapiExecutionSetTimeoutCmd = &cobra.Command{
	Use:   "set-timeout",
	Short: "Execution.SetTimeout()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var nnapiExecutionStartComputeCmd = &cobra.Command{
	Use:   "start-compute",
	Short: "Execution.StartCompute()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var nnapiModelNewCmd = &cobra.Command{
	Use:   "new",
	Short: "Create Model",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj, err := nnapi.NewModel()
		if err != nil {
			return err
		}
		defer obj.Close()
		fmt.Println("created successfully")
		return nil
	},
}

var nnapiModelNewCompilationCmd = &cobra.Command{
	Use:   "new-compilation",
	Short: "Model.NewCompilation()",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj, err := nnapi.NewModel()
		if err != nil {
			return err
		}
		defer obj.Close()
		result, err := obj.NewCompilation()
		if err != nil {
			return err
		}
		fmt.Println(result)
		return nil
	},
}

var nnapiModelFinishCmd = &cobra.Command{
	Use:   "finish",
	Short: "Model.Finish()",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj, err := nnapi.NewModel()
		if err != nil {
			return err
		}
		defer obj.Close()
		err = obj.Finish()
		if err != nil {
			return err
		}
		fmt.Println("ok")
		return nil
	},
}

var nnapiModelRelaxFloat32toFloat16Cmd = &cobra.Command{
	Use:   "relax-float32to-float16",
	Short: "Model.RelaxFloat32toFloat16()",
	RunE: func(cmd *cobra.Command, args []string) error {
		allow, _ := cmd.Flags().GetBool("allow")
		obj, err := nnapi.NewModel()
		if err != nil {
			return err
		}
		defer obj.Close()
		err = obj.RelaxFloat32toFloat16(allow)
		if err != nil {
			return err
		}
		fmt.Println("ok")
		return nil
	},
}

func init() {
	nnapiModelRelaxFloat32toFloat16Cmd.Flags().Bool("allow", false, "allow")
	nnapiCmd.AddCommand(nnapiCompilationCmd)
	nnapiCmd.AddCommand(nnapiErrorCmd)
	nnapiCmd.AddCommand(nnapiEventCmd)
	nnapiCmd.AddCommand(nnapiExecutionCmd)
	nnapiCmd.AddCommand(nnapiModelCmd)
	nnapiCompilationCmd.AddCommand(nnapiCompilationNewBurstCmd)
	nnapiCompilationCmd.AddCommand(nnapiCompilationFinishCmd)
	nnapiCompilationCmd.AddCommand(nnapiCompilationSetPreferenceCmd)
	nnapiCompilationCmd.AddCommand(nnapiCompilationSetPriorityCmd)
	nnapiCompilationCmd.AddCommand(nnapiCompilationSetTimeoutCmd)
	nnapiCompilationCmd.AddCommand(nnapiCompilationNewExecutionCmd)
	nnapiErrorCmd.AddCommand(nnapiErrorErrorCmd)
	nnapiEventCmd.AddCommand(nnapiEventWaitCmd)
	nnapiExecutionCmd.AddCommand(nnapiExecutionComputeCmd)
	nnapiExecutionCmd.AddCommand(nnapiExecutionSetMeasureTimingCmd)
	nnapiExecutionCmd.AddCommand(nnapiExecutionSetTimeoutCmd)
	nnapiExecutionCmd.AddCommand(nnapiExecutionStartComputeCmd)
	nnapiModelCmd.AddCommand(nnapiModelNewCmd)
	nnapiModelCmd.AddCommand(nnapiModelNewCompilationCmd)
	nnapiModelCmd.AddCommand(nnapiModelFinishCmd)
	nnapiModelCmd.AddCommand(nnapiModelRelaxFloat32toFloat16Cmd)
	rootCmd.AddCommand(nnapiCmd)
}
