// Code generated by cligen. DO NOT EDIT.

package main

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/xaionaro-go/ndk/surfacecontrol"
)

var surfacecontrolCmd = &cobra.Command{
	Use:   "surfacecontrol",
	Short: "surfacecontrol NDK module",
}

var surfacecontrolErrorCmd = &cobra.Command{
	Use:   "error",
	Short: "Error operations",
}

var surfacecontrolSurfaceControlCmd = &cobra.Command{
	Use:   "surface-control",
	Short: "SurfaceControl operations",
}

var surfacecontrolSurfaceTransactionStatsCmd = &cobra.Command{
	Use:   "surface-transaction-stats",
	Short: "SurfaceTransactionStats operations",
}

var surfacecontrolTransactionCmd = &cobra.Command{
	Use:   "transaction",
	Short: "Transaction operations",
}

var surfacecontrolErrorErrorCmd = &cobra.Command{
	Use:   "error",
	Short: "Error.Error()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var surfacecontrolSurfaceControlAcquireCmd = &cobra.Command{
	Use:   "acquire",
	Short: "SurfaceControl.Acquire()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var surfacecontrolSurfaceControlCreateChildCmd = &cobra.Command{
	Use:   "create-child",
	Short: "SurfaceControl.CreateChild()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var surfacecontrolSurfaceTransactionStatsGetLatchTimeCmd = &cobra.Command{
	Use:   "get-latch-time",
	Short: "SurfaceTransactionStats.GetLatchTime()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var surfacecontrolSurfaceTransactionStatsGetPresentFenceFdCmd = &cobra.Command{
	Use:   "get-present-fence-fd",
	Short: "SurfaceTransactionStats.GetPresentFenceFd()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var surfacecontrolTransactionNewCmd = &cobra.Command{
	Use:   "new",
	Short: "Create Transaction",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj := surfacecontrol.NewTransaction()
		defer obj.Close()
		fmt.Println("created successfully")
		return nil
	},
}

var surfacecontrolTransactionApplyCmd = &cobra.Command{
	Use:   "apply",
	Short: "Transaction.Apply()",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj := surfacecontrol.NewTransaction()
		defer obj.Close()
		obj.Apply()
		fmt.Println("ok")
		return nil
	},
}

var surfacecontrolTransactionSetDesiredPresentTimeCmd = &cobra.Command{
	Use:   "set-desired-present-time",
	Short: "Transaction.SetDesiredPresentTime()",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj := surfacecontrol.NewTransaction()
		defer obj.Close()
		desiredPresentTime, _ := cmd.Flags().GetInt64("desired-present-time")
		obj.SetDesiredPresentTime(desiredPresentTime)
		fmt.Println("ok")
		return nil
	},
}

func init() {
	surfacecontrolTransactionSetDesiredPresentTimeCmd.Flags().Int64("desired-present-time", 0, "desiredPresentTime")
	surfacecontrolCmd.AddCommand(surfacecontrolErrorCmd)
	surfacecontrolCmd.AddCommand(surfacecontrolSurfaceControlCmd)
	surfacecontrolCmd.AddCommand(surfacecontrolSurfaceTransactionStatsCmd)
	surfacecontrolCmd.AddCommand(surfacecontrolTransactionCmd)
	surfacecontrolErrorCmd.AddCommand(surfacecontrolErrorErrorCmd)
	surfacecontrolSurfaceControlCmd.AddCommand(surfacecontrolSurfaceControlAcquireCmd)
	surfacecontrolSurfaceControlCmd.AddCommand(surfacecontrolSurfaceControlCreateChildCmd)
	surfacecontrolSurfaceTransactionStatsCmd.AddCommand(surfacecontrolSurfaceTransactionStatsGetLatchTimeCmd)
	surfacecontrolSurfaceTransactionStatsCmd.AddCommand(surfacecontrolSurfaceTransactionStatsGetPresentFenceFdCmd)
	surfacecontrolTransactionCmd.AddCommand(surfacecontrolTransactionNewCmd)
	surfacecontrolTransactionCmd.AddCommand(surfacecontrolTransactionApplyCmd)
	surfacecontrolTransactionCmd.AddCommand(surfacecontrolTransactionSetDesiredPresentTimeCmd)
	rootCmd.AddCommand(surfacecontrolCmd)
}
