// Code generated by cligen. DO NOT EDIT.

package main

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/xaionaro-go/ndk/thermal"
)

var thermalCmd = &cobra.Command{
	Use:   "thermal",
	Short: "thermal NDK module",
}

var thermalErrorCmd = &cobra.Command{
	Use:   "error",
	Short: "Error operations",
}

var thermalManagerCmd = &cobra.Command{
	Use:   "manager",
	Short: "Manager operations",
}

var thermalThermalStatusCmd = &cobra.Command{
	Use:   "thermal-status",
	Short: "ThermalStatus operations",
}

var thermalErrorErrorCmd = &cobra.Command{
	Use:   "error",
	Short: "Error.Error()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

var thermalManagerNewCmd = &cobra.Command{
	Use:   "new",
	Short: "Create Manager",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj := thermal.NewManager()
		defer obj.Close()
		fmt.Println("created successfully")
		return nil
	},
}

var thermalManagerCurrentStatusCmd = &cobra.Command{
	Use:   "current-status",
	Short: "Manager.CurrentStatus()",
	RunE: func(cmd *cobra.Command, args []string) error {
		obj := thermal.NewManager()
		defer obj.Close()
		result := obj.CurrentStatus()
		fmt.Println(result)
		return nil
	},
}

var thermalThermalStatusStringCmd = &cobra.Command{
	Use:   "string",
	Short: "ThermalStatus.String()",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("requires external context (NativeActivity, JNI, etc.)")
		return nil
	},
}

func init() {
	thermalCmd.AddCommand(thermalErrorCmd)
	thermalCmd.AddCommand(thermalManagerCmd)
	thermalCmd.AddCommand(thermalThermalStatusCmd)
	thermalErrorCmd.AddCommand(thermalErrorErrorCmd)
	thermalManagerCmd.AddCommand(thermalManagerNewCmd)
	thermalManagerCmd.AddCommand(thermalManagerCurrentStatusCmd)
	thermalThermalStatusCmd.AddCommand(thermalThermalStatusStringCmd)
	rootCmd.AddCommand(thermalCmd)
}
