// Code generated by idiomgen. DO NOT EDIT.

package surfacecontrol

import (
	capi "github.com/AndroidGoLab/ndk/capi/surfacecontrol"
)

type ASurfaceTransaction_OnCommit = capi.ASurfaceTransaction_OnCommit
