// Code generated by idiomgen. DO NOT EDIT.

package surfacecontrol

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/surfacecontrol"
)

// SurfaceTransactionStats wraps the NDK ASurfaceTransactionStats handle.
type SurfaceTransactionStats struct {
	ptr *capi.ASurfaceTransactionStats
}

// NewSurfaceTransactionStatsFromPointer wraps a raw ASurfaceTransactionStats pointer.
func NewSurfaceTransactionStatsFromPointer(ptr unsafe.Pointer) *SurfaceTransactionStats {
	return &SurfaceTransactionStats{ptr: (*capi.ASurfaceTransactionStats)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *SurfaceTransactionStats) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// GetAcquireTime returns the value directly.
func (h *SurfaceTransactionStats) GetAcquireTime(surface_control *SurfaceControl) int64 {
	return (int64)(capi.ASurfaceTransactionStats_getAcquireTime(h.ptr, surface_control.ptr))
}

// GetLatchTime returns the value directly.
func (h *SurfaceTransactionStats) GetLatchTime() int64 {
	return (int64)(capi.ASurfaceTransactionStats_getLatchTime(h.ptr))
}

// GetPresentFenceFd calls the underlying NDK function.
func (h *SurfaceTransactionStats) GetPresentFenceFd() error {
	return result(int32(capi.ASurfaceTransactionStats_getPresentFenceFd(h.ptr)))
}

// GetPreviousReleaseFenceFd calls the underlying NDK function.
func (h *SurfaceTransactionStats) GetPreviousReleaseFenceFd(surface_control *SurfaceControl) error {
	return result(int32(capi.ASurfaceTransactionStats_getPreviousReleaseFenceFd(h.ptr, surface_control.ptr)))
}
