// Code generated by idiomgen. DO NOT EDIT.

package surfacecontrol

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/surfacecontrol"
)

// SurfaceControl wraps the NDK ASurfaceControl handle.
type SurfaceControl struct {
	ptr *capi.ASurfaceControl
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *SurfaceControl) cptr() *capi.ASurfaceControl {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close releases the underlying NDK handle.
func (h *SurfaceControl) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.ASurfaceControl_release(h.ptr)
	h.ptr = nil
	return nil
}

// NewSurfaceControlFromPointer wraps a raw ASurfaceControl pointer.
func NewSurfaceControlFromPointer(ptr unsafe.Pointer) *SurfaceControl {
	return &SurfaceControl{ptr: (*capi.ASurfaceControl)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *SurfaceControl) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *SurfaceControl) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewSurfaceControlFromUintPtr wraps a uintptr as a SurfaceControl.
// The caller must ensure ptr points to a valid ASurfaceControl.
func NewSurfaceControlFromUintPtr(ptr uintptr) *SurfaceControl {
	return &SurfaceControl{ptr: (*capi.ASurfaceControl)(unsafe.Pointer(ptr))}
}

// Acquire calls the underlying NDK function.
func (h *SurfaceControl) Acquire() {
	capi.ASurfaceControl_acquire(h.ptr)
}

// CreateChild creates a new SurfaceControl from this SurfaceControl.
func (h *SurfaceControl) CreateChild(debug_name string) *SurfaceControl {
	return &SurfaceControl{ptr: capi.ASurfaceControl_create(h.ptr, debug_name)}
}
