package specgen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/ndk/tools/pkg/specmodel"

	"gopkg.in/yaml.v3"
)

func TestWriteSpec(t *testing.T) {
	spec := specmodel.Spec{
		Module:        "test",
		SourcePackage: "github.com/xaionaro-go/ndk/capi/test",
		Types: map[string]specmodel.TypeDef{
			"TestHandle": {
				Kind:   "opaque_ptr",
				CType:  "TestHandle",
				GoType: "*C.TestHandle",
			},
		},
		Enums:     map[string][]specmodel.EnumValue{},
		Functions: map[string]specmodel.FuncDef{},
		Callbacks: map[string]specmodel.CallbackDef{},
	}

	dir := t.TempDir()
	// Use a nested path to verify MkdirAll.
	outPath := filepath.Join(dir, "sub", "dir", "spec.yaml")

	if err := WriteSpec(spec, outPath); err != nil {
		t.Fatalf("WriteSpec: %v", err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	content := string(data)

	// Verify header.
	if !strings.HasPrefix(content, "# Code generated by specgen. DO NOT EDIT.\n\n") {
		t.Errorf("missing or incorrect header; got prefix: %q", content[:min(len(content), 60)])
	}

	// Verify YAML contains "module: test".
	if !strings.Contains(content, "module: test") {
		t.Errorf("YAML does not contain 'module: test'; got:\n%s", content)
	}

	// Unmarshal and verify round-trip.
	// Strip the header comment before unmarshalling.
	yamlBody := content[strings.Index(content, "\n\n")+2:]
	var roundTrip specmodel.Spec
	if err := yaml.Unmarshal([]byte(yamlBody), &roundTrip); err != nil {
		t.Fatalf("unmarshal round-trip: %v", err)
	}

	if roundTrip.Module != "test" {
		t.Errorf("round-trip module = %q, want %q", roundTrip.Module, "test")
	}
	if roundTrip.SourcePackage != "github.com/xaionaro-go/ndk/capi/test" {
		t.Errorf("round-trip source_package = %q, want %q", roundTrip.SourcePackage, "github.com/xaionaro-go/ndk/capi/test")
	}
	if td, ok := roundTrip.Types["TestHandle"]; !ok {
		t.Error("round-trip missing type TestHandle")
	} else if td.Kind != "opaque_ptr" {
		t.Errorf("round-trip TestHandle.Kind = %q, want opaque_ptr", td.Kind)
	}
}

func TestWriteSpec_WithStructs(t *testing.T) {
	spec := specmodel.Spec{
		Module:        "camera",
		SourcePackage: "github.com/xaionaro-go/ndk/capi/camera",
		Structs: map[string]specmodel.StructDef{
			"ACameraDevice_StateCallbacks": {
				Fields: []specmodel.StructField{
					{Name: "context", Type: "void*"},
					{Name: "onDisconnected", Type: "func_ptr", Params: []specmodel.Param{
						{Name: "context", Type: "void*"},
						{Name: "device", Type: "*ACameraDevice"},
					}},
					{Name: "onError", Type: "func_ptr", Params: []specmodel.Param{
						{Name: "context", Type: "void*"},
						{Name: "device", Type: "*ACameraDevice"},
						{Name: "error", Type: "int"},
					}},
				},
			},
		},
	}

	dir := t.TempDir()
	path := filepath.Join(dir, "test.yaml")
	err := WriteSpec(spec, path)
	require.NoError(t, err)

	data, err := os.ReadFile(path)
	require.NoError(t, err)

	var loaded specmodel.Spec
	err = yaml.Unmarshal(data, &loaded)
	require.NoError(t, err)

	require.Len(t, loaded.Structs["ACameraDevice_StateCallbacks"].Fields, 3)
	assert.Equal(t, "context", loaded.Structs["ACameraDevice_StateCallbacks"].Fields[0].Name)
	assert.Equal(t, "void*", loaded.Structs["ACameraDevice_StateCallbacks"].Fields[0].Type)
	assert.Equal(t, "func_ptr", loaded.Structs["ACameraDevice_StateCallbacks"].Fields[1].Type)
	assert.Len(t, loaded.Structs["ACameraDevice_StateCallbacks"].Fields[1].Params, 2)
}

func TestWriteSpecBadPath(t *testing.T) {
	spec := specmodel.Spec{Module: "x"}
	// /dev/null/impossible is not a valid directory.
	err := WriteSpec(spec, "/dev/null/impossible/spec.yaml")
	if err == nil {
		t.Error("expected error for invalid path")
	}
}
