// Code generated by idiomgen. DO NOT EDIT.

package input

type KEY_STATE int32

const (
	AKEY_STATE_UNKNOWN KEY_STATE = -1
	AKEY_STATE_UP      KEY_STATE = 0
	AKEY_STATE_DOWN    KEY_STATE = 1
	AKEY_STATE_VIRTUAL KEY_STATE = 2
)
