// Code generated by idiomgen. DO NOT EDIT.

package input

import "fmt"

type Source int32

const (
	Unknown Source = 0
	Keyboard Source = 257
	Dpad Source = 513
	Gamepad Source = 1025
	Touchscreen Source = 4098
	Mouse Source = 8194
	Stylus Source = 16386
	BluetoothStylus Source = 49154
	Trackball Source = 65540
	MouseRelative Source = 131076
	Touchpad Source = 1048584
	TouchNavigation Source = 2097152
	Joystick Source = 16777232
	Hdmi Source = 33554433
	Sensor Source = 67108864
	RotaryEncoder Source = 4194304
	Any Source = -256
)

func (v Source) String() string {
	switch v {
	case Unknown:
		return "Unknown"
	case Keyboard:
		return "Keyboard"
	case Dpad:
		return "Dpad"
	case Gamepad:
		return "Gamepad"
	case Touchscreen:
		return "Touchscreen"
	case Mouse:
		return "Mouse"
	case Stylus:
		return "Stylus"
	case BluetoothStylus:
		return "BluetoothStylus"
	case Trackball:
		return "Trackball"
	case MouseRelative:
		return "MouseRelative"
	case Touchpad:
		return "Touchpad"
	case TouchNavigation:
		return "TouchNavigation"
	case Joystick:
		return "Joystick"
	case Hdmi:
		return "Hdmi"
	case Sensor:
		return "Sensor"
	case RotaryEncoder:
		return "RotaryEncoder"
	case Any:
		return "Any"
	default:
		return fmt.Sprintf("Source(%d)", int(v))
	}
}

