// Code generated by idiomgen. DO NOT EDIT.

package choreographer

import (
	capi "github.com/xaionaro-go/ndk/capi/choreographer"
)

type AChoreographer_vsyncCallback = capi.AChoreographer_vsyncCallback
