// Code generated by idiomgen. DO NOT EDIT.

package choreographer

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/choreographer"
)

// ChoreographerFrameCallbackData wraps the NDK AChoreographerFrameCallbackData handle.
type ChoreographerFrameCallbackData struct {
	ptr *capi.AChoreographerFrameCallbackData
}

// NewChoreographerFrameCallbackDataFromPointer wraps a raw AChoreographerFrameCallbackData pointer.
func NewChoreographerFrameCallbackDataFromPointer(ptr unsafe.Pointer) *ChoreographerFrameCallbackData {
	return &ChoreographerFrameCallbackData{ptr: (*capi.AChoreographerFrameCallbackData)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *ChoreographerFrameCallbackData) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// GetFrameTimeNanos returns the value directly.
func (h *ChoreographerFrameCallbackData) GetFrameTimeNanos() int64 {
	return (int64)(capi.AChoreographerFrameCallbackData_getFrameTimeNanos(h.ptr))
}

// GetFrameTimelineDeadlineNanos returns the value directly.
func (h *ChoreographerFrameCallbackData) GetFrameTimelineDeadlineNanos(index uint64) int64 {
	return (int64)(capi.AChoreographerFrameCallbackData_getFrameTimelineDeadlineNanos(h.ptr, index))
}

// GetFrameTimelineExpectedPresentationTimeNanos returns the value directly.
func (h *ChoreographerFrameCallbackData) GetFrameTimelineExpectedPresentationTimeNanos(index uint64) int64 {
	return (int64)(capi.AChoreographerFrameCallbackData_getFrameTimelineExpectedPresentationTimeNanos(h.ptr, index))
}

// GetFrameTimelinesLength returns the value directly.
func (h *ChoreographerFrameCallbackData) GetFrameTimelinesLength() uint64 {
	return (uint64)(capi.AChoreographerFrameCallbackData_getFrameTimelinesLength(h.ptr))
}

// GetPreferredFrameTimelineIndex returns the value directly.
func (h *ChoreographerFrameCallbackData) GetPreferredFrameTimelineIndex() uint64 {
	return (uint64)(capi.AChoreographerFrameCallbackData_getPreferredFrameTimelineIndex(h.ptr))
}
