// Code generated by idiomgen. DO NOT EDIT.

package choreographer

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/choreographer"
)

// Choreographer wraps the NDK AChoreographer handle.
type Choreographer struct {
	ptr *capi.AChoreographer
}

// NewChoreographerFromPointer wraps a raw AChoreographer pointer.
func NewChoreographerFromPointer(ptr unsafe.Pointer) *Choreographer {
	return &Choreographer{ptr: (*capi.AChoreographer)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Choreographer) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// GetInstance calls the underlying C function.
func GetInstance() *Choreographer {
	return &Choreographer{ptr: capi.AChoreographer_getInstance()}
}
