// Copyright 2018-2024 The gooid Authors. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

package ndk

import (
	"github.com/xaionaro-go/ndk/ndk"
)

const (
	ACTIVITY_SHOW_SOFT_INPUT_IMPLICIT      = ndk.ACTIVITY_SHOW_SOFT_INPUT_IMPLICIT
	ACTIVITY_SHOW_SOFT_INPUT_FORCED        = ndk.ACTIVITY_SHOW_SOFT_INPUT_FORCED
	ACTIVITY_HIDE_SOFT_INPUT_IMPLICIT_ONLY = ndk.ACTIVITY_HIDE_SOFT_INPUT_IMPLICIT_ONLY
	ACTIVITY_HIDE_SOFT_INPUT_NOT_ALWAYS    = ndk.ACTIVITY_HIDE_SOFT_INPUT_NOT_ALWAYS
	WINDOW_FORMAT_RGBA_8888                = ndk.WINDOW_FORMAT_RGBA_8888
	WINDOW_FORMAT_RGBX_8888                = ndk.WINDOW_FORMAT_RGBX_8888
	WINDOW_FORMAT_RGB_565                  = ndk.WINDOW_FORMAT_RGB_565
	FLAG_ALLOW_LOCK_WHILE_SCREEN_ON        = ndk.FLAG_ALLOW_LOCK_WHILE_SCREEN_ON
	FLAG_DIM_BEHIND                        = ndk.FLAG_DIM_BEHIND
	FLAG_BLUR_BEHIND                       = ndk.FLAG_BLUR_BEHIND
	FLAG_NOT_FOCUSABLE                     = ndk.FLAG_NOT_FOCUSABLE
	FLAG_NOT_TOUCHABLE                     = ndk.FLAG_NOT_TOUCHABLE
	FLAG_NOT_TOUCH_MODAL                   = ndk.FLAG_NOT_TOUCH_MODAL
	FLAG_TOUCHABLE_WHEN_WAKING             = ndk.FLAG_TOUCHABLE_WHEN_WAKING
	FLAG_KEEP_SCREEN_ON                    = ndk.FLAG_KEEP_SCREEN_ON
	FLAG_LAYOUT_IN_SCREEN                  = ndk.FLAG_LAYOUT_IN_SCREEN
	FLAG_LAYOUT_NO_LIMITS                  = ndk.FLAG_LAYOUT_NO_LIMITS
	FLAG_FULLSCREEN                        = ndk.FLAG_FULLSCREEN
	FLAG_FORCE_NOT_FULLSCREEN              = ndk.FLAG_FORCE_NOT_FULLSCREEN
	FLAG_DITHER                            = ndk.FLAG_DITHER
	FLAG_SECURE                            = ndk.FLAG_SECURE
	FLAG_SCALED                            = ndk.FLAG_SCALED
	FLAG_IGNORE_CHEEK_PRESSES              = ndk.FLAG_IGNORE_CHEEK_PRESSES
	FLAG_LAYOUT_INSET_DECOR                = ndk.FLAG_LAYOUT_INSET_DECOR
	FLAG_ALT_FOCUSABLE_IM                  = ndk.FLAG_ALT_FOCUSABLE_IM
	FLAG_WATCH_OUTSIDE_TOUCH               = ndk.FLAG_WATCH_OUTSIDE_TOUCH
	FLAG_SHOW_WHEN_LOCKED                  = ndk.FLAG_SHOW_WHEN_LOCKED
	FLAG_SHOW_WALLPAPER                    = ndk.FLAG_SHOW_WALLPAPER
	FLAG_TURN_SCREEN_ON                    = ndk.FLAG_TURN_SCREEN_ON
	FLAG_DISMISS_KEYGUARD                  = ndk.FLAG_DISMISS_KEYGUARD
)
