// Code generated by capigen. DO NOT EDIT.

package surfacetexture

/*
#cgo LDFLAGS: -landroid
#include "android/surface_texture.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

var _ runtime.Error
var _ unsafe.Pointer

func ASurfaceTexture_acquireANativeWindow(st *ASurfaceTexture) *ANativeWindow {
	cst, cstAllocMap := (*C.ASurfaceTexture)(unsafe.Pointer(st)), cgoAllocsUnknown
	__ret := C.ASurfaceTexture_acquireANativeWindow(cst)
	runtime.KeepAlive(cstAllocMap)
	__v := (*ANativeWindow)(unsafe.Pointer(__ret))
	return __v
}

func ASurfaceTexture_attachToGLContext(st *ASurfaceTexture, texName uint32) int32 {
	cst, cstAllocMap := (*C.ASurfaceTexture)(unsafe.Pointer(st)), cgoAllocsUnknown
	ctexName, ctexNameAllocMap := (C.uint)(texName), cgoAllocsUnknown
	__ret := C.ASurfaceTexture_attachToGLContext(cst, ctexName)
	runtime.KeepAlive(ctexNameAllocMap)
	runtime.KeepAlive(cstAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASurfaceTexture_detachFromGLContext(st *ASurfaceTexture) int32 {
	cst, cstAllocMap := (*C.ASurfaceTexture)(unsafe.Pointer(st)), cgoAllocsUnknown
	__ret := C.ASurfaceTexture_detachFromGLContext(cst)
	runtime.KeepAlive(cstAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASurfaceTexture_getTimestamp(st *ASurfaceTexture) int64 {
	cst, cstAllocMap := (*C.ASurfaceTexture)(unsafe.Pointer(st)), cgoAllocsUnknown
	__ret := C.ASurfaceTexture_getTimestamp(cst)
	runtime.KeepAlive(cstAllocMap)
	__v := (int64)(__ret)
	return __v
}

func ASurfaceTexture_getTransformMatrix(st *ASurfaceTexture, mtx *[16]float32) {
	cst, cstAllocMap := (*C.ASurfaceTexture)(unsafe.Pointer(st)), cgoAllocsUnknown
	cmtx, cmtxAllocMap := (*C.float)(unsafe.Pointer(&mtx[0])), cgoAllocsUnknown
	C.ASurfaceTexture_getTransformMatrix(cst, cmtx)
	runtime.KeepAlive(cmtxAllocMap)
	runtime.KeepAlive(cstAllocMap)
}

func ASurfaceTexture_release(st *ASurfaceTexture) {
	cst, cstAllocMap := (*C.ASurfaceTexture)(unsafe.Pointer(st)), cgoAllocsUnknown
	C.ASurfaceTexture_release(cst)
	runtime.KeepAlive(cstAllocMap)
}

func ASurfaceTexture_updateTexImage(st *ASurfaceTexture) int32 {
	cst, cstAllocMap := (*C.ASurfaceTexture)(unsafe.Pointer(st)), cgoAllocsUnknown
	__ret := C.ASurfaceTexture_updateTexImage(cst)
	runtime.KeepAlive(cstAllocMap)
	__v := (int32)(__ret)
	return __v
}
