// Code generated by capigen. DO NOT EDIT.

package egl

/*
#cgo LDFLAGS: -lEGL -landroid -lnativewindow
#include "EGL/egl.h"
#include "android/native_window.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

type ANativeWindow C.ANativeWindow

type ANativeWindow_Buffer C.ANativeWindow_Buffer

type EGLAttrib int64

type EGLBoolean uint32

type EGLClientBuffer unsafe.Pointer

type EGLConfig unsafe.Pointer

type EGLContext unsafe.Pointer

type EGLDisplay unsafe.Pointer

type EGLImage unsafe.Pointer

type EGLSurface unsafe.Pointer

type EGLSync unsafe.Pointer

type EGLTime C.EGLTime

type EGLenum uint32

type ARect C.ARect

type EGLNativeDisplayType C.EGLNativeDisplayType

type EGLNativePixmapType C.EGLNativePixmapType

type EGLNativeWindowType C.EGLNativeWindowType

type EGLint C.EGLint

type PFNEGLBINDAPIPROC func()

type PFNEGLBINDTEXIMAGEPROC func()

type PFNEGLCHOOSECONFIGPROC func()

type PFNEGLCLIENTWAITSYNCPROC func()

type PFNEGLCOPYBUFFERSPROC func()

type PFNEGLCREATECONTEXTPROC func()

type PFNEGLCREATEIMAGEPROC func()

type PFNEGLCREATEPBUFFERFROMCLIENTBUFFERPROC func()

type PFNEGLCREATEPBUFFERSURFACEPROC func()

type PFNEGLCREATEPIXMAPSURFACEPROC func()

type PFNEGLCREATEPLATFORMPIXMAPSURFACEPROC func()

type PFNEGLCREATEPLATFORMWINDOWSURFACEPROC func()

type PFNEGLCREATESYNCPROC func()

type PFNEGLCREATEWINDOWSURFACEPROC func()

type PFNEGLDESTROYCONTEXTPROC func()

type PFNEGLDESTROYIMAGEPROC func()

type PFNEGLDESTROYSURFACEPROC func()

type PFNEGLDESTROYSYNCPROC func()

type PFNEGLGETCONFIGATTRIBPROC func()

type PFNEGLGETCONFIGSPROC func()

type PFNEGLGETCURRENTCONTEXTPROC func()

type PFNEGLGETCURRENTDISPLAYPROC func()

type PFNEGLGETCURRENTSURFACEPROC func()

type PFNEGLGETDISPLAYPROC func()

type PFNEGLGETERRORPROC func()

type PFNEGLGETPLATFORMDISPLAYPROC func()

type PFNEGLGETPROCADDRESSPROC func()

type PFNEGLGETSYNCATTRIBPROC func()

type PFNEGLINITIALIZEPROC func()

type PFNEGLMAKECURRENTPROC func()

type PFNEGLQUERYAPIPROC func()

type PFNEGLQUERYCONTEXTPROC func()

type PFNEGLQUERYSTRINGPROC func()

type PFNEGLQUERYSURFACEPROC func()

type PFNEGLRELEASETEXIMAGEPROC func()

type PFNEGLRELEASETHREADPROC func()

type PFNEGLSURFACEATTRIBPROC func()

type PFNEGLSWAPBUFFERSPROC func()

type PFNEGLSWAPINTERVALPROC func()

type PFNEGLTERMINATEPROC func()

type PFNEGLWAITCLIENTPROC func()

type PFNEGLWAITGLPROC func()

type PFNEGLWAITNATIVEPROC func()

type PFNEGLWAITSYNCPROC func()

type EglMustCastToProperFunctionPointerType func()
