// Code generated by idiomgen. DO NOT EDIT.

package thermal

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/thermal"
)

// Manager wraps the NDK AThermalManager handle.
type Manager struct {
	ptr *capi.AThermalManager
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *Manager) cptr() *capi.AThermalManager {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewManager creates a new Manager.
func NewManager() *Manager {
	return &Manager{ptr: capi.AThermal_acquireManager()}
}

// Close releases the underlying NDK handle.
func (h *Manager) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.AThermal_releaseManager(h.ptr)
	h.ptr = nil
	return nil
}

// NewManagerFromPointer wraps a raw AThermalManager pointer.
func NewManagerFromPointer(ptr unsafe.Pointer) *Manager {
	return &Manager{ptr: (*capi.AThermalManager)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Manager) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// CurrentStatus returns the value directly.
func (h *Manager) CurrentStatus() ThermalStatus {
	return (ThermalStatus)(capi.AThermal_getCurrentThermalStatus(h.ptr))
}

// AThermal_getThermalHeadroom returns the value directly.
func (h *Manager) AThermal_getThermalHeadroom(forecastSeconds int32) float32 {
	return (float32)(capi.AThermal_getThermalHeadroom(h.ptr, forecastSeconds))
}
