// Code generated by idiomgen. DO NOT EDIT.

package trace

import (
	capi "github.com/AndroidGoLab/ndk/capi/trace"
)

// BeginAsyncSection calls the underlying C function.
func BeginAsyncSection(sectionName string, cookie int32) {
	capi.ATrace_beginAsyncSection(sectionName, cookie)
}

// BeginSection calls the underlying C function.
func BeginSection(sectionName string) {
	capi.ATrace_beginSection(sectionName)
}

// EndAsyncSection calls the underlying C function.
func EndAsyncSection(sectionName string, cookie int32) {
	capi.ATrace_endAsyncSection(sectionName, cookie)
}

// EndSection calls the underlying C function.
func EndSection() {
	capi.ATrace_endSection()
}

// IsEnabled calls the underlying C function.
func IsEnabled() bool {
	return (bool)(capi.ATrace_isEnabled())
}

// SetCounter calls the underlying C function.
func SetCounter(counterName string, counterValue int64) {
	capi.ATrace_setCounter(counterName, counterValue)
}
