// Code generated by idiomgen. DO NOT EDIT.

package midi

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/midi"
)

// InputPort wraps the NDK AMidiInputPort handle.
type InputPort struct {
	ptr *capi.AMidiInputPort
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *InputPort) cptr() *capi.AMidiInputPort {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close releases the underlying NDK handle.
func (h *InputPort) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.AMidiInputPort_close(h.ptr)
	h.ptr = nil
	return nil
}

// NewInputPortFromPointer wraps a raw AMidiInputPort pointer.
func NewInputPortFromPointer(ptr unsafe.Pointer) *InputPort {
	return &InputPort{ptr: (*capi.AMidiInputPort)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *InputPort) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *InputPort) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewInputPortFromUintPtr wraps a uintptr as a InputPort.
// The caller must ensure ptr points to a valid AMidiInputPort.
func NewInputPortFromUintPtr(ptr uintptr) *InputPort {
	return &InputPort{ptr: (*capi.AMidiInputPort)(unsafe.Pointer(ptr))}
}

// Send calls the underlying NDK function.
func (h *InputPort) Send(buffer *uint8, numBytes uint64) error {
	return result(capi.AMidiInputPort_send(h.ptr, buffer, numBytes))
}

// SendWithTimestamp returns the value directly.
func (h *InputPort) SendWithTimestamp(buffer *uint8, numBytes uint64, timestamp int64) int64 {
	return (int64)(capi.AMidiInputPort_sendWithTimestamp(h.ptr, buffer, numBytes, timestamp))
}
