// Code generated by idiomgen. DO NOT EDIT.

package midi

type MidiDevice_Protocol int32

const (
	AMIDI_DEVICE_PROTOCOL_UMP_USE_MIDI_CI                      MidiDevice_Protocol = 0
	AMIDI_DEVICE_PROTOCOL_UMP_MIDI_1_0_UP_TO_64_BITS           MidiDevice_Protocol = 1
	AMIDI_DEVICE_PROTOCOL_UMP_MIDI_1_0_UP_TO_64_BITS_AND_JRTS  MidiDevice_Protocol = 2
	AMIDI_DEVICE_PROTOCOL_UMP_MIDI_1_0_UP_TO_128_BITS          MidiDevice_Protocol = 3
	AMIDI_DEVICE_PROTOCOL_UMP_MIDI_1_0_UP_TO_128_BITS_AND_JRTS MidiDevice_Protocol = 4
	AMIDI_DEVICE_PROTOCOL_UMP_MIDI_2_0                         MidiDevice_Protocol = 17
	AMIDI_DEVICE_PROTOCOL_UMP_MIDI_2_0_AND_JRTS                MidiDevice_Protocol = 18
	AMIDI_DEVICE_PROTOCOL_UNKNOWN                              MidiDevice_Protocol = -1
)
