// Code generated by idiomgen. DO NOT EDIT.

package asset

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/asset"
)

// Dir wraps the NDK AAssetDir handle.
type Dir struct {
	ptr *capi.AAssetDir
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *Dir) cptr() *capi.AAssetDir {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close releases the underlying NDK handle.
func (h *Dir) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.AAssetDir_close(h.ptr)
	h.ptr = nil
	return nil
}

// NewDirFromPointer wraps a raw AAssetDir pointer.
func NewDirFromPointer(ptr unsafe.Pointer) *Dir {
	return &Dir{ptr: (*capi.AAssetDir)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Dir) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *Dir) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewDirFromUintPtr wraps a uintptr as a Dir.
// The caller must ensure ptr points to a valid AAssetDir.
func NewDirFromUintPtr(ptr uintptr) *Dir {
	return &Dir{ptr: (*capi.AAssetDir)(unsafe.Pointer(ptr))}
}

// NextFileName returns the value directly.
func (h *Dir) NextFileName() string {
	return (string)(capi.AAssetDir_getNextFileName(h.ptr))
}

// Rewind calls the underlying NDK function.
func (h *Dir) Rewind() {
	capi.AAssetDir_rewind(h.ptr)
}
