// Code generated by idiomgen. DO NOT EDIT.

package asset

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/asset"
)

// Dir wraps the NDK AAssetDir handle.
type Dir struct {
	ptr *capi.AAssetDir
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *Dir) cptr() *capi.AAssetDir {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close releases the underlying NDK handle.
func (h *Dir) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.AAssetDir_close(h.ptr)
	h.ptr = nil
	return nil
}

// NewDirFromPointer wraps a raw AAssetDir pointer.
func NewDirFromPointer(ptr unsafe.Pointer) *Dir {
	return &Dir{ptr: (*capi.AAssetDir)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Dir) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// NextFileName returns the value directly.
func (h *Dir) NextFileName() string {
	return (string)(capi.AAssetDir_getNextFileName(h.ptr))
}

// Rewind calls the underlying NDK function.
func (h *Dir) Rewind() {
	capi.AAssetDir_rewind(h.ptr)
}
