// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/media"
)

// CodecVideoCapabilities wraps the NDK ACodecVideoCapabilities handle.
type CodecVideoCapabilities struct {
	ptr *capi.ACodecVideoCapabilities
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *CodecVideoCapabilities) cptr() *capi.ACodecVideoCapabilities {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewCodecVideoCapabilitiesFromPointer wraps a raw ACodecVideoCapabilities pointer.
func NewCodecVideoCapabilitiesFromPointer(ptr unsafe.Pointer) *CodecVideoCapabilities {
	return &CodecVideoCapabilities{ptr: (*capi.ACodecVideoCapabilities)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *CodecVideoCapabilities) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *CodecVideoCapabilities) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewCodecVideoCapabilitiesFromUintPtr wraps a uintptr as a CodecVideoCapabilities.
// The caller must ensure ptr points to a valid ACodecVideoCapabilities.
func NewCodecVideoCapabilitiesFromUintPtr(ptr uintptr) *CodecVideoCapabilities {
	return &CodecVideoCapabilities{ptr: (*capi.ACodecVideoCapabilities)(unsafe.Pointer(ptr))}
}
