// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/media"
)

// CodecPerformancePoint wraps the NDK ACodecPerformancePoint handle.
type CodecPerformancePoint struct {
	ptr *capi.ACodecPerformancePoint
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *CodecPerformancePoint) cptr() *capi.ACodecPerformancePoint {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewCodecPerformancePointFromPointer wraps a raw ACodecPerformancePoint pointer.
func NewCodecPerformancePointFromPointer(ptr unsafe.Pointer) *CodecPerformancePoint {
	return &CodecPerformancePoint{ptr: (*capi.ACodecPerformancePoint)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *CodecPerformancePoint) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
