// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/media"
)

// Crypto wraps the NDK AMediaCrypto handle.
type Crypto struct {
	ptr *capi.AMediaCrypto
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *Crypto) cptr() *capi.AMediaCrypto {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewCrypto creates a new Crypto.
func NewCrypto(uuid AMediaUUID, initData unsafe.Pointer, initDataSize uint64) *Crypto {
	return &Crypto{ptr: capi.AMediaCrypto_new(uuid, initData, initDataSize)}
}

// Close releases the underlying NDK handle.
func (h *Crypto) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.AMediaCrypto_delete(h.ptr)
	h.ptr = nil
	return nil
}

// NewCryptoFromPointer wraps a raw AMediaCrypto pointer.
func NewCryptoFromPointer(ptr unsafe.Pointer) *Crypto {
	return &Crypto{ptr: (*capi.AMediaCrypto)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Crypto) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *Crypto) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewCryptoFromUintPtr wraps a uintptr as a Crypto.
// The caller must ensure ptr points to a valid AMediaCrypto.
func NewCryptoFromUintPtr(ptr uintptr) *Crypto {
	return &Crypto{ptr: (*capi.AMediaCrypto)(unsafe.Pointer(ptr))}
}
