// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/media"
)

// DoubleRange wraps the NDK ADoubleRange handle.
type DoubleRange struct {
	ptr *capi.ADoubleRange
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *DoubleRange) cptr() *capi.ADoubleRange {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewDoubleRangeFromPointer wraps a raw ADoubleRange pointer.
func NewDoubleRangeFromPointer(ptr unsafe.Pointer) *DoubleRange {
	return &DoubleRange{ptr: (*capi.ADoubleRange)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *DoubleRange) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
