// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/media"
)

// Extractor wraps the NDK AMediaExtractor handle.
type Extractor struct {
	ptr *capi.AMediaExtractor
}


// NewExtractor creates a new Extractor.
func NewExtractor() *Extractor {
	return &Extractor{ptr: capi.AMediaExtractor_new()}
}



// Close releases the underlying NDK handle.
func (h *Extractor) Close() error {
	if h.ptr == nil {
		return nil
	}
	err := result(int32(capi.AMediaExtractor_delete(h.ptr)))
	h.ptr = nil
	return err
}


// NewExtractorFromPointer wraps a raw AMediaExtractor pointer.
func NewExtractorFromPointer(ptr unsafe.Pointer) *Extractor {
	return &Extractor{ptr: (*capi.AMediaExtractor)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Extractor) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// SampleTime returns the value directly.
func (h *Extractor) SampleTime() int64 {
	return (int64)(capi.AMediaExtractor_getSampleTime(h.ptr))
}

// TrackCount returns the value directly.
func (h *Extractor) TrackCount() uint64 {
	return (uint64)(capi.AMediaExtractor_getTrackCount(h.ptr))
}

// SelectTrack calls the underlying NDK function.
func (h *Extractor) SelectTrack(idx uint64) error {
	return result(int32(capi.AMediaExtractor_selectTrack(h.ptr, idx)))
}

// SetDataSourceFd calls the underlying NDK function.
func (h *Extractor) SetDataSourceFd(fd int32, offset Off64_t, length Off64_t) error {
	return result(int32(capi.AMediaExtractor_setDataSourceFd(h.ptr, fd, capi.Off64_t(offset), capi.Off64_t(length))))
}


