// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/media"
)

// ImageCropRect wraps the NDK AImageCropRect handle.
type ImageCropRect struct {
	ptr *capi.AImageCropRect
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *ImageCropRect) cptr() *capi.AImageCropRect {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewImageCropRectFromPointer wraps a raw AImageCropRect pointer.
func NewImageCropRectFromPointer(ptr unsafe.Pointer) *ImageCropRect {
	return &ImageCropRect{ptr: (*capi.AImageCropRect)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *ImageCropRect) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *ImageCropRect) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewImageCropRectFromUintPtr wraps a uintptr as a ImageCropRect.
// The caller must ensure ptr points to a valid AImageCropRect.
func NewImageCropRectFromUintPtr(ptr uintptr) *ImageCropRect {
	return &ImageCropRect{ptr: (*capi.AImageCropRect)(unsafe.Pointer(ptr))}
}
