// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/media"
)

// ImageReader_BufferRemovedListener wraps the NDK AImageReader_BufferRemovedListener handle.
type ImageReader_BufferRemovedListener struct {
	ptr *capi.AImageReader_BufferRemovedListener
}

// NewImageReader_BufferRemovedListenerFromPointer wraps a raw AImageReader_BufferRemovedListener pointer.
func NewImageReader_BufferRemovedListenerFromPointer(ptr unsafe.Pointer) *ImageReader_BufferRemovedListener {
	return &ImageReader_BufferRemovedListener{ptr: (*capi.AImageReader_BufferRemovedListener)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *ImageReader_BufferRemovedListener) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
