// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/media"
)

// Image wraps the NDK AImage handle.
type Image struct {
	ptr *capi.AImage
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *Image) cptr() *capi.AImage {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close releases the underlying NDK handle.
func (h *Image) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.AImage_delete(h.ptr)
	h.ptr = nil
	return nil
}

// NewImageFromPointer wraps a raw AImage pointer.
func NewImageFromPointer(ptr unsafe.Pointer) *Image {
	return &Image{ptr: (*capi.AImage)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Image) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *Image) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewImageFromUintPtr wraps a uintptr as a Image.
// The caller must ensure ptr points to a valid AImage.
func NewImageFromUintPtr(ptr uintptr) *Image {
	return &Image{ptr: (*capi.AImage)(unsafe.Pointer(ptr))}
}

// DeleteAsync calls the underlying NDK function.
func (h *Image) DeleteAsync(releaseFenceFd int32) {
	capi.AImage_deleteAsync(h.ptr, releaseFenceFd)
}

// Format calls the underlying NDK function.
func (h *Image) Format(format *int32) error {
	return result(capi.AImage_getFormat(h.ptr, format))
}

// Height calls the underlying NDK function.
func (h *Image) Height(height *int32) error {
	return result(capi.AImage_getHeight(h.ptr, height))
}

// NumberOfPlanes calls the underlying NDK function.
func (h *Image) NumberOfPlanes(numPlanes *int32) error {
	return result(capi.AImage_getNumberOfPlanes(h.ptr, numPlanes))
}

// PlaneData calls the underlying NDK function.
func (h *Image) PlaneData(planeIdx int32) (*uint8, int32, error) {
	var dataPtr *uint8
	var dataLengthPtr int32
	ret := capi.AImage_getPlaneData(h.ptr, planeIdx, &dataPtr, &dataLengthPtr)
	if err := result(ret); err != nil {
		return nil, 0, err
	}
	return dataPtr, dataLengthPtr, nil
}

// PlanePixelStride calls the underlying NDK function.
func (h *Image) PlanePixelStride(planeIdx int32, pixelStride *int32) error {
	return result(capi.AImage_getPlanePixelStride(h.ptr, planeIdx, pixelStride))
}

// PlaneRowStride calls the underlying NDK function.
func (h *Image) PlaneRowStride(planeIdx int32, rowStride *int32) error {
	return result(capi.AImage_getPlaneRowStride(h.ptr, planeIdx, rowStride))
}

// Timestamp calls the underlying NDK function.
func (h *Image) Timestamp(timestampNs *int64) error {
	return result(capi.AImage_getTimestamp(h.ptr, timestampNs))
}

// Width calls the underlying NDK function.
func (h *Image) Width(width *int32) error {
	return result(capi.AImage_getWidth(h.ptr, width))
}
