// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/media"
)

// ImageReader wraps the NDK AImageReader handle.
type ImageReader struct {
	ptr *capi.AImageReader
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *ImageReader) cptr() *capi.AImageReader {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close releases the underlying NDK handle.
func (h *ImageReader) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.AImageReader_delete(h.ptr)
	h.ptr = nil
	return nil
}

// NewImageReaderFromPointer wraps a raw AImageReader pointer.
func NewImageReaderFromPointer(ptr unsafe.Pointer) *ImageReader {
	return &ImageReader{ptr: (*capi.AImageReader)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *ImageReader) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// AcquireLatestImage calls the underlying NDK function.
func (h *ImageReader) AcquireLatestImage() (*Image, error) {
	var imagePtr *capi.AImage
	ret := capi.AImageReader_acquireLatestImage(h.ptr, &imagePtr)
	if err := result(ret); err != nil {
		return nil, err
	}
	return &Image{ptr: imagePtr}, nil
}

// AcquireNextImage calls the underlying NDK function.
func (h *ImageReader) AcquireNextImage() (*Image, error) {
	var imagePtr *capi.AImage
	ret := capi.AImageReader_acquireNextImage(h.ptr, &imagePtr)
	if err := result(ret); err != nil {
		return nil, err
	}
	return &Image{ptr: imagePtr}, nil
}

// Format calls the underlying NDK function.
func (h *ImageReader) Format(format *int32) error {
	return result(capi.AImageReader_getFormat(h.ptr, format))
}

// Height calls the underlying NDK function.
func (h *ImageReader) Height(height *int32) error {
	return result(capi.AImageReader_getHeight(h.ptr, height))
}

// MaxImages calls the underlying NDK function.
func (h *ImageReader) MaxImages(maxImages *int32) error {
	return result(capi.AImageReader_getMaxImages(h.ptr, maxImages))
}

// Width calls the underlying NDK function.
func (h *ImageReader) Width(width *int32) error {
	return result(capi.AImageReader_getWidth(h.ptr, width))
}

// Window calls the underlying NDK function.
func (h *ImageReader) Window() (*Window, error) {
	var windowPtr *capi.ANativeWindow
	ret := capi.AImageReader_getWindow(h.ptr, &windowPtr)
	if err := result(ret); err != nil {
		return nil, err
	}
	return &Window{ptr: windowPtr}, nil
}

// NewImageReader calls the underlying C function.
func NewImageReader(width int32, height int32, format int32, maxImages int32) (*ImageReader, error) {
	var readerPtr *capi.AImageReader
	ret := capi.AImageReader_new(width, height, format, maxImages, &readerPtr)
	if err := result(ret); err != nil {
		return nil, err
	}
	return &ImageReader{ptr: readerPtr}, nil
}

// NewImageReaderWithUsage calls the underlying C function.
func NewImageReaderWithUsage(width int32, height int32, format int32, usage uint64, maxImages int32) (*ImageReader, error) {
	var readerPtr *capi.AImageReader
	ret := capi.AImageReader_newWithUsage(width, height, format, usage, maxImages, &readerPtr)
	if err := result(ret); err != nil {
		return nil, err
	}
	return &ImageReader{ptr: readerPtr}, nil
}
