// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/media"
)

// ImageReader wraps the NDK AImageReader handle.
type ImageReader struct {
	ptr *capi.AImageReader
}

// Close releases the underlying NDK handle.
func (h *ImageReader) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.AImageReader_delete(h.ptr)
	h.ptr = nil
	return nil
}

// NewImageReaderFromPointer wraps a raw AImageReader pointer.
func NewImageReaderFromPointer(ptr unsafe.Pointer) *ImageReader {
	return &ImageReader{ptr: (*capi.AImageReader)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *ImageReader) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// Format calls the underlying NDK function.
func (h *ImageReader) Format(format *int32) error {
	return result(int32(capi.AImageReader_getFormat(h.ptr, format)))
}

// Height calls the underlying NDK function.
func (h *ImageReader) Height(height *int32) error {
	return result(int32(capi.AImageReader_getHeight(h.ptr, height)))
}

// MaxImages calls the underlying NDK function.
func (h *ImageReader) MaxImages(maxImages *int32) error {
	return result(int32(capi.AImageReader_getMaxImages(h.ptr, maxImages)))
}

// Width calls the underlying NDK function.
func (h *ImageReader) Width(width *int32) error {
	return result(int32(capi.AImageReader_getWidth(h.ptr, width)))
}
