// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/media"
)

// IntRange wraps the NDK AIntRange handle.
type IntRange struct {
	ptr *capi.AIntRange
}

// NewIntRangeFromPointer wraps a raw AIntRange pointer.
func NewIntRangeFromPointer(ptr unsafe.Pointer) *IntRange {
	return &IntRange{ptr: (*capi.AIntRange)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *IntRange) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
