// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/media"
)

// MediaDrmKeyStatus wraps the NDK AMediaDrmKeyStatus handle.
type MediaDrmKeyStatus struct {
	ptr *capi.AMediaDrmKeyStatus
}

// NewMediaDrmKeyStatusFromPointer wraps a raw AMediaDrmKeyStatus pointer.
func NewMediaDrmKeyStatusFromPointer(ptr unsafe.Pointer) *MediaDrmKeyStatus {
	return &MediaDrmKeyStatus{ptr: (*capi.AMediaDrmKeyStatus)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *MediaDrmKeyStatus) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
