// Code generated by idiomgen. DO NOT EDIT.

package media

type MediaDrmKeyStatusType int32

const (
	KEY_STATUS_TYPE_USABLE           MediaDrmKeyStatusType = 0
	KEY_STATUS_TYPE_EXPIRED          MediaDrmKeyStatusType = 1
	KEY_STATUS_TYPE_OUTPUTNOTALLOWED MediaDrmKeyStatusType = 2
	KEY_STATUS_TYPE_STATUSPENDING    MediaDrmKeyStatusType = 3
	KEY_STATUS_TYPE_INTERNALERROR    MediaDrmKeyStatusType = 4
)
