// Code generated by idiomgen. DO NOT EDIT.

package media

type MediaDrmKeyType int32

const (
	KEY_TYPE_STREAMING MediaDrmKeyType = 1
	KEY_TYPE_OFFLINE   MediaDrmKeyType = 2
	KEY_TYPE_RELEASE   MediaDrmKeyType = 3
)
