// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/media"
)

// MediaCodecCryptoInfo wraps the NDK AMediaCodecCryptoInfo handle.
type MediaCodecCryptoInfo struct {
	ptr *capi.AMediaCodecCryptoInfo
}

// NewMediaCodecCryptoInfo creates a new MediaCodecCryptoInfo.
func NewMediaCodecCryptoInfo(numsubsamples int32, key *[16]uint8, iv *[16]uint8, mode cryptoinfo_mode_t, clearbytes *uint64, encryptedbytes *uint64) *MediaCodecCryptoInfo {
	return &MediaCodecCryptoInfo{ptr: capi.AMediaCodecCryptoInfo_new(numsubsamples, key, iv, capi.Cryptoinfo_mode_t(mode), clearbytes, encryptedbytes)}
}

// Close releases the underlying NDK handle.
func (h *MediaCodecCryptoInfo) Close() error {
	if h.ptr == nil {
		return nil
	}
	err := result(int32(capi.AMediaCodecCryptoInfo_delete(h.ptr)))
	h.ptr = nil
	return err
}

// NewMediaCodecCryptoInfoFromPointer wraps a raw AMediaCodecCryptoInfo pointer.
func NewMediaCodecCryptoInfoFromPointer(ptr unsafe.Pointer) *MediaCodecCryptoInfo {
	return &MediaCodecCryptoInfo{ptr: (*capi.AMediaCodecCryptoInfo)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *MediaCodecCryptoInfo) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// GetNumSubSamples returns the value directly.
func (h *MediaCodecCryptoInfo) GetNumSubSamples() uint64 {
	return (uint64)(capi.AMediaCodecCryptoInfo_getNumSubSamples(h.ptr))
}

// SetPattern calls the underlying NDK function.
func (h *MediaCodecCryptoInfo) SetPattern(pattern *cryptoinfo_pattern_t) {
	capi.AMediaCodecCryptoInfo_setPattern(h.ptr, pattern.ptr)
}
