// Code generated by idiomgen. DO NOT EDIT.

package media

type MediaCodecType int32

const (
	AMediaCodecType_INVALID_CODEC_INFO          MediaCodecType = 0
	AMediaCodecType_SOFTWARE_ONLY               MediaCodecType = 1
	AMediaCodecType_HARDWARE_ACCELERATED        MediaCodecType = 2
	AMediaCodecType_SOFTWARE_WITH_DEVICE_ACCESS MediaCodecType = 3
)
