// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/media"
)

// MediaCodecBufferInfo wraps the NDK AMediaCodecBufferInfo handle.
type MediaCodecBufferInfo struct {
	ptr *capi.AMediaCodecBufferInfo
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *MediaCodecBufferInfo) cptr() *capi.AMediaCodecBufferInfo {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewMediaCodecBufferInfoFromPointer wraps a raw AMediaCodecBufferInfo pointer.
func NewMediaCodecBufferInfoFromPointer(ptr unsafe.Pointer) *MediaCodecBufferInfo {
	return &MediaCodecBufferInfo{ptr: (*capi.AMediaCodecBufferInfo)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *MediaCodecBufferInfo) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *MediaCodecBufferInfo) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewMediaCodecBufferInfoFromUintPtr wraps a uintptr as a MediaCodecBufferInfo.
// The caller must ensure ptr points to a valid AMediaCodecBufferInfo.
func NewMediaCodecBufferInfoFromUintPtr(ptr uintptr) *MediaCodecBufferInfo {
	return &MediaCodecBufferInfo{ptr: (*capi.AMediaCodecBufferInfo)(unsafe.Pointer(ptr))}
}
