// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/media"
)

// Muxer wraps the NDK AMediaMuxer handle.
type Muxer struct {
	ptr *capi.AMediaMuxer
}

// Close releases the underlying NDK handle.
func (h *Muxer) Close() error {
	if h.ptr == nil {
		return nil
	}
	err := result(int32(capi.AMediaMuxer_delete(h.ptr)))
	h.ptr = nil
	return err
}

// NewMuxerFromPointer wraps a raw AMediaMuxer pointer.
func NewMuxerFromPointer(ptr unsafe.Pointer) *Muxer {
	return &Muxer{ptr: (*capi.AMediaMuxer)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Muxer) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// GetTrackCount returns the value directly.
func (h *Muxer) GetTrackCount() int64 {
	return (int64)(capi.AMediaMuxer_getTrackCount(h.ptr))
}

// GetTrackFormat creates a new Format from this Muxer.
func (h *Muxer) GetTrackFormat(idx uint64) *Format {
	return &Format{ptr: capi.AMediaMuxer_getTrackFormat(h.ptr, idx)}
}

// Start calls the underlying NDK function.
func (h *Muxer) Start() error {
	return result(int32(capi.AMediaMuxer_start(h.ptr)))
}

// Stop calls the underlying NDK function.
func (h *Muxer) Stop() error {
	return result(int32(capi.AMediaMuxer_stop(h.ptr)))
}
