// Code generated by idiomgen. DO NOT EDIT.

package media

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/media"
)

// PsshEntry wraps the NDK PsshEntry handle.
type PsshEntry struct {
	ptr *capi.PsshEntry
}

// NewPsshEntryFromPointer wraps a raw PsshEntry pointer.
func NewPsshEntryFromPointer(ptr unsafe.Pointer) *PsshEntry {
	return &PsshEntry{ptr: (*capi.PsshEntry)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *PsshEntry) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
