// Code generated by idiomgen. DO NOT EDIT.

package media

type SeekMode int32

const (
	AMEDIAEXTRACTOR_SEEK_PREVIOUS_SYNC SeekMode = 0
	AMEDIAEXTRACTOR_SEEK_NEXT_SYNC     SeekMode = 1
	AMEDIAEXTRACTOR_SEEK_CLOSEST_SYNC  SeekMode = 2
)
