// Code generated by idiomgen. DO NOT EDIT.

package hint

import (
	"time"
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/performancehint"
)

// Manager wraps the NDK APerformanceHintManager handle.
type Manager struct {
	ptr *capi.APerformanceHintManager
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *Manager) cptr() *capi.APerformanceHintManager {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewManagerFromPointer wraps a raw APerformanceHintManager pointer.
func NewManagerFromPointer(ptr unsafe.Pointer) *Manager {
	return &Manager{ptr: (*capi.APerformanceHintManager)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Manager) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *Manager) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewManagerFromUintPtr wraps a uintptr as a Manager.
// The caller must ensure ptr points to a valid APerformanceHintManager.
func NewManagerFromUintPtr(ptr uintptr) *Manager {
	return &Manager{ptr: (*capi.APerformanceHintManager)(unsafe.Pointer(ptr))}
}

// CreateSession creates a new Session from this Manager.
func (h *Manager) CreateSession(threadIds *int32, size uint64, initialTargetWorkDuration time.Duration) *Session {
	return &Session{ptr: capi.APerformanceHint_createSession(h.ptr, threadIds, size, int64(initialTargetWorkDuration.Nanoseconds()))}
}

// PreferredUpdateRateNanos returns the value directly.
func (h *Manager) PreferredUpdateRateNanos() int64 {
	return (int64)(capi.APerformanceHint_getPreferredUpdateRateNanos(h.ptr))
}

// APerformanceHint_getManager calls the underlying C function.
func APerformanceHint_getManager() *Manager {
	return &Manager{ptr: capi.APerformanceHint_getManager()}
}
