// Code generated by idiomgen. DO NOT EDIT.

package hint

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/performancehint"
)

// Session wraps the NDK APerformanceHintSession handle.
type Session struct {
	ptr *capi.APerformanceHintSession
}

// Close releases the underlying NDK handle.
func (h *Session) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.APerformanceHint_closeSession(h.ptr)
	h.ptr = nil
	return nil
}

// NewSessionFromPointer wraps a raw APerformanceHintSession pointer.
func NewSessionFromPointer(ptr unsafe.Pointer) *Session {
	return &Session{ptr: (*capi.APerformanceHintSession)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Session) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// ReportActualWorkDuration calls the underlying NDK function.
func (h *Session) ReportActualWorkDuration(actualDurationNanos int64) error {
	return result(int32(capi.APerformanceHint_reportActualWorkDuration(h.ptr, actualDurationNanos)))
}

// UpdateTargetWorkDuration calls the underlying NDK function.
func (h *Session) UpdateTargetWorkDuration(targetDurationNanos int64) error {
	return result(int32(capi.APerformanceHint_updateTargetWorkDuration(h.ptr, targetDurationNanos)))
}
