// Code generated by idiomgen. DO NOT EDIT.

package hint

import (
	"time"
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/performancehint"
)

// Session wraps the NDK APerformanceHintSession handle.
type Session struct {
	ptr *capi.APerformanceHintSession
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *Session) cptr() *capi.APerformanceHintSession {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close releases the underlying NDK handle.
func (h *Session) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.APerformanceHint_closeSession(h.ptr)
	h.ptr = nil
	return nil
}

// NewSessionFromPointer wraps a raw APerformanceHintSession pointer.
func NewSessionFromPointer(ptr unsafe.Pointer) *Session {
	return &Session{ptr: (*capi.APerformanceHintSession)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Session) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// ReportActualWorkDuration calls the underlying NDK function.
func (h *Session) ReportActualWorkDuration(actualDuration time.Duration) error {
	return result(capi.APerformanceHint_reportActualWorkDuration(h.ptr, int64(actualDuration.Nanoseconds())))
}

// APerformanceHint_reportActualWorkDuration2 calls the underlying NDK function.
func (h *Session) APerformanceHint_reportActualWorkDuration2(workDuration *WorkDuration) error {
	return result(capi.APerformanceHint_reportActualWorkDuration2(h.ptr, workDuration.cptr()))
}

// APerformanceHint_setPreferPowerEfficiency calls the underlying NDK function.
func (h *Session) APerformanceHint_setPreferPowerEfficiency(enabled bool) error {
	return result(capi.APerformanceHint_setPreferPowerEfficiency(h.ptr, enabled))
}

// APerformanceHint_setThreads calls the underlying NDK function.
func (h *Session) APerformanceHint_setThreads(threadIds *Pid_t, size uint64) error {
	return result(capi.APerformanceHint_setThreads(h.ptr, (*capi.Pid_t)(threadIds), size))
}

// UpdateTargetWorkDuration calls the underlying NDK function.
func (h *Session) UpdateTargetWorkDuration(targetDuration time.Duration) error {
	return result(capi.APerformanceHint_updateTargetWorkDuration(h.ptr, int64(targetDuration.Nanoseconds())))
}
