// Code generated by idiomgen. DO NOT EDIT.

package audio

import "fmt"

type Direction int32

const (
	Output Direction = 0
	Input  Direction = 1
)

func (v Direction) String() string {
	switch v {
	case Output:
		return "Output"
	case Input:
		return "Input"
	default:
		return fmt.Sprintf("Direction(%d)", int(v))
	}
}
