// Code generated by idiomgen. DO NOT EDIT.

package audio

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/aaudio"
)

// StreamBuilder wraps the NDK AAudioStreamBuilder handle.
type StreamBuilder struct {
	ptr *capi.AAudioStreamBuilder
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *StreamBuilder) cptr() *capi.AAudioStreamBuilder {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewStreamBuilder creates a new StreamBuilder.
func NewStreamBuilder() (*StreamBuilder, error) {
	var ptr *capi.AAudioStreamBuilder
	if err := result(capi.AAudio_createStreamBuilder(&ptr)); err != nil {
		return nil, err
	}
	return &StreamBuilder{ptr: ptr}, nil
}

// Close releases the underlying NDK handle.
func (h *StreamBuilder) Close() error {
	if h.ptr == nil {
		return nil
	}
	err := result(capi.AAudioStreamBuilder_delete(h.ptr))
	h.ptr = nil
	return err
}

// NewStreamBuilderFromPointer wraps a raw AAudioStreamBuilder pointer.
func NewStreamBuilderFromPointer(ptr unsafe.Pointer) *StreamBuilder {
	return &StreamBuilder{ptr: (*capi.AAudioStreamBuilder)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *StreamBuilder) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// Open creates a new Stream from this StreamBuilder.
func (h *StreamBuilder) Open() (*Stream, error) {
	var ptr *capi.AAudioStream
	if err := result(capi.AAudioStreamBuilder_openStream(h.ptr, &ptr)); err != nil {
		return nil, err
	}
	return &Stream{ptr: ptr}, nil
}

// SetAttributionTag calls the underlying NDK function.
func (h *StreamBuilder) SetAttributionTag(attributionTag string) {
	capi.AAudioStreamBuilder_setAttributionTag(h.ptr, attributionTag)
}

// SetBufferCapacityInFrames sets a property and returns the receiver for chaining.
func (h *StreamBuilder) SetBufferCapacityInFrames(numFrames int32) *StreamBuilder {
	capi.AAudioStreamBuilder_setBufferCapacityInFrames(h.ptr, numFrames)
	return h
}

// SetChannelCount sets a property and returns the receiver for chaining.
func (h *StreamBuilder) SetChannelCount(channelCount int32) *StreamBuilder {
	capi.AAudioStreamBuilder_setChannelCount(h.ptr, channelCount)
	return h
}

// SetDeviceID sets a property and returns the receiver for chaining.
func (h *StreamBuilder) SetDeviceID(deviceID int32) *StreamBuilder {
	capi.AAudioStreamBuilder_setDeviceId(h.ptr, deviceID)
	return h
}

// SetDirection sets a property and returns the receiver for chaining.
func (h *StreamBuilder) SetDirection(direction Direction) *StreamBuilder {
	capi.AAudioStreamBuilder_setDirection(h.ptr, capi.Aaudio_direction_t(direction))
	return h
}

// SetFormat sets a property and returns the receiver for chaining.
func (h *StreamBuilder) SetFormat(format Format) *StreamBuilder {
	capi.AAudioStreamBuilder_setFormat(h.ptr, capi.Aaudio_format_t(format))
	return h
}

// SetFramesPerDataCallback calls the underlying NDK function.
func (h *StreamBuilder) SetFramesPerDataCallback(numFrames int32) {
	capi.AAudioStreamBuilder_setFramesPerDataCallback(h.ptr, numFrames)
}

// SetIsContentSpatialized calls the underlying NDK function.
func (h *StreamBuilder) SetIsContentSpatialized(isSpatialized bool) {
	capi.AAudioStreamBuilder_setIsContentSpatialized(h.ptr, isSpatialized)
}

// SetPackageName calls the underlying NDK function.
func (h *StreamBuilder) SetPackageName(packageName string) {
	capi.AAudioStreamBuilder_setPackageName(h.ptr, packageName)
}

// SetPerformanceMode sets a property and returns the receiver for chaining.
func (h *StreamBuilder) SetPerformanceMode(mode PerformanceMode) *StreamBuilder {
	capi.AAudioStreamBuilder_setPerformanceMode(h.ptr, capi.Aaudio_performance_mode_t(mode))
	return h
}

// SetPrivacySensitive calls the underlying NDK function.
func (h *StreamBuilder) SetPrivacySensitive(privacySensitive bool) {
	capi.AAudioStreamBuilder_setPrivacySensitive(h.ptr, privacySensitive)
}

// SetSampleRate sets a property and returns the receiver for chaining.
func (h *StreamBuilder) SetSampleRate(sampleRate int32) *StreamBuilder {
	capi.AAudioStreamBuilder_setSampleRate(h.ptr, sampleRate)
	return h
}

// SetSamplesPerFrame calls the underlying NDK function.
func (h *StreamBuilder) SetSamplesPerFrame(samplesPerFrame int32) {
	capi.AAudioStreamBuilder_setSamplesPerFrame(h.ptr, samplesPerFrame)
}

// SetSharingMode sets a property and returns the receiver for chaining.
func (h *StreamBuilder) SetSharingMode(sharingMode SharingMode) *StreamBuilder {
	capi.AAudioStreamBuilder_setSharingMode(h.ptr, capi.Aaudio_sharing_mode_t(sharingMode))
	return h
}
