// Code generated by idiomgen. DO NOT EDIT.

package audio

import "fmt"

type StreamState int32

const (
	Uninitialized StreamState = 0
	Unknown       StreamState = 1
	Open          StreamState = 2
	Starting      StreamState = 3
	Started       StreamState = 4
	Pausing       StreamState = 5
	Paused        StreamState = 6
	Flushing      StreamState = 7
	Flushed       StreamState = 8
	Stopping      StreamState = 9
	Stopped       StreamState = 10
	Closing       StreamState = 11
	Closed        StreamState = 12
	Disconnected  StreamState = 13
)

func (v StreamState) String() string {
	switch v {
	case Uninitialized:
		return "Uninitialized"
	case Unknown:
		return "Unknown"
	case Open:
		return "Open"
	case Starting:
		return "Starting"
	case Started:
		return "Started"
	case Pausing:
		return "Pausing"
	case Paused:
		return "Paused"
	case Flushing:
		return "Flushing"
	case Flushed:
		return "Flushed"
	case Stopping:
		return "Stopping"
	case Stopped:
		return "Stopped"
	case Closing:
		return "Closing"
	case Closed:
		return "Closed"
	case Disconnected:
		return "Disconnected"
	default:
		return fmt.Sprintf("StreamState(%d)", int(v))
	}
}
