// Code generated by idiomgen. DO NOT EDIT.

package nativeactivity

/*
#include "android/native_activity.h"
#include <stdlib.h>
#include "cgo_helpers.h"

extern void bridgeInstallLifecycleCallbacks(ANativeActivity* activity);
*/
import "C"

import "unsafe"

//export ANativeActivity_onCreate
func ANativeActivity_onCreate(
	activity *C.ANativeActivity,
	savedState unsafe.Pointer,
	savedStateSize C.size_t,
) {
	C.bridgeInstallLifecycleCallbacks(activity)
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnCreate
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity))
	}

}

//export goBridge_Lifecycle_OnStart
func goBridge_Lifecycle_OnStart(activity *C.ANativeActivity) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnStart
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity))
	}
}

//export goBridge_Lifecycle_OnResume
func goBridge_Lifecycle_OnResume(activity *C.ANativeActivity) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnResume
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity))
	}
}

//export goBridge_Lifecycle_OnSaveInstanceState
func goBridge_Lifecycle_OnSaveInstanceState(activity *C.ANativeActivity, outSize *C.uint64_t) unsafe.Pointer {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnSaveInstanceState
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity), unsafe.Pointer(outSize))
	}
	return nil
}

//export goBridge_Lifecycle_OnPause
func goBridge_Lifecycle_OnPause(activity *C.ANativeActivity) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnPause
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity))
	}
}

//export goBridge_Lifecycle_OnStop
func goBridge_Lifecycle_OnStop(activity *C.ANativeActivity) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnStop
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity))
	}
}

//export goBridge_Lifecycle_OnDestroy
func goBridge_Lifecycle_OnDestroy(activity *C.ANativeActivity) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnDestroy
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity))
	}
}

//export goBridge_Lifecycle_OnWindowFocusChanged
func goBridge_Lifecycle_OnWindowFocusChanged(activity *C.ANativeActivity, hasFocus C.int32_t) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnWindowFocusChanged
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity), int32(hasFocus))
	}
}

//export goBridge_Lifecycle_OnNativeWindowCreated
func goBridge_Lifecycle_OnNativeWindowCreated(activity *C.ANativeActivity, window *C.ANativeWindow) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnNativeWindowCreated
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity), unsafe.Pointer(window))
	}
}

//export goBridge_Lifecycle_OnNativeWindowResized
func goBridge_Lifecycle_OnNativeWindowResized(activity *C.ANativeActivity, window *C.ANativeWindow) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnNativeWindowResized
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity), unsafe.Pointer(window))
	}
}

//export goBridge_Lifecycle_OnNativeWindowRedrawNeeded
func goBridge_Lifecycle_OnNativeWindowRedrawNeeded(activity *C.ANativeActivity, window *C.ANativeWindow) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnNativeWindowRedrawNeeded
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity), unsafe.Pointer(window))
	}
}

//export goBridge_Lifecycle_OnNativeWindowDestroyed
func goBridge_Lifecycle_OnNativeWindowDestroyed(activity *C.ANativeActivity, window *C.ANativeWindow) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnNativeWindowDestroyed
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity), unsafe.Pointer(window))
	}
}

//export goBridge_Lifecycle_OnInputQueueCreated
func goBridge_Lifecycle_OnInputQueueCreated(activity *C.ANativeActivity, queue *C.AInputQueue) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnInputQueueCreated
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity), unsafe.Pointer(queue))
	}
}

//export goBridge_Lifecycle_OnInputQueueDestroyed
func goBridge_Lifecycle_OnInputQueueDestroyed(activity *C.ANativeActivity, queue *C.AInputQueue) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnInputQueueDestroyed
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity), unsafe.Pointer(queue))
	}
}

//export goBridge_Lifecycle_OnContentRectChanged
func goBridge_Lifecycle_OnContentRectChanged(activity *C.ANativeActivity, rect *C.ARect) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnContentRectChanged
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity), unsafe.Pointer(rect))
	}
}

//export goBridge_Lifecycle_OnConfigurationChanged
func goBridge_Lifecycle_OnConfigurationChanged(activity *C.ANativeActivity) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnConfigurationChanged
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity))
	}
}

//export goBridge_Lifecycle_OnLowMemory
func goBridge_Lifecycle_OnLowMemory(activity *C.ANativeActivity) {
	bridgeLifecycleMu.Lock()
	cb := bridgeLifecycleCB.OnLowMemory
	bridgeLifecycleMu.Unlock()
	if cb != nil {
		cb(unsafe.Pointer(activity))
	}
}
