// Code generated by capigen. DO NOT EDIT.

package nativeactivity

/*
#cgo LDFLAGS: -landroid
#include "android/native_activity.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

type ANativeActivity C.ANativeActivity

type ANativeActivityCallbacks C.ANativeActivityCallbacks

type AAssetManager C.AAssetManager

type JNIEnv C.JNIEnv

type JavaVM C.JavaVM

type Jobject C.jobject
