// Code generated by capigen. DO NOT EDIT.

package persistablebundle

/*
#cgo LDFLAGS: -lbinder_ndk
#include "android/persistable_bundle.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

var _ runtime.Error
var _ unsafe.Pointer

func APersistableBundle_delete(pBundle *APersistableBundle) {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	C.APersistableBundle_delete(cpBundle)
	runtime.KeepAlive(cpBundleAllocMap)
}

func APersistableBundle_dup(pBundle *APersistableBundle) *APersistableBundle {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	__ret := C.APersistableBundle_dup(cpBundle)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (*APersistableBundle)(unsafe.Pointer(__ret))
	return __v
}

func APersistableBundle_erase(pBundle *APersistableBundle, key string) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	__ret := C.APersistableBundle_erase(cpBundle, ckey)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getBoolean(pBundle *APersistableBundle, key string, val *bool) bool {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cval, cvalAllocMap := (*C._Bool)(unsafe.Pointer(val)), cgoAllocsUnknown
	__ret := C.APersistableBundle_getBoolean(cpBundle, ckey, cval)
	runtime.KeepAlive(cvalAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (bool)(__ret)
	return __v
}

func APersistableBundle_getBooleanKeys(pBundle *APersistableBundle, outKeys *string, bufferSizeBytes int32, stringAllocator APersistableBundle_stringAllocator, context unsafe.Pointer) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	cstringAllocator, cstringAllocatorAllocMap := stringAllocator.PassValue()
	ccontext, ccontextAllocMap := context, cgoAllocsUnknown
	__ret := C.APersistableBundle_getBooleanKeys(cpBundle, (**C.char)(unsafe.Pointer(outKeys)), cbufferSizeBytes, cstringAllocator, ccontext)
	runtime.KeepAlive(ccontextAllocMap)
	runtime.KeepAlive(cstringAllocatorAllocMap)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getBooleanVector(pBundle *APersistableBundle, key string, buffer *bool, bufferSizeBytes int32) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cbuffer, cbufferAllocMap := (*C._Bool)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	__ret := C.APersistableBundle_getBooleanVector(cpBundle, ckey, cbuffer, cbufferSizeBytes)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cbufferAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getBooleanVectorKeys(pBundle *APersistableBundle, outKeys *string, bufferSizeBytes int32, stringAllocator APersistableBundle_stringAllocator, context unsafe.Pointer) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	cstringAllocator, cstringAllocatorAllocMap := stringAllocator.PassValue()
	ccontext, ccontextAllocMap := context, cgoAllocsUnknown
	__ret := C.APersistableBundle_getBooleanVectorKeys(cpBundle, (**C.char)(unsafe.Pointer(outKeys)), cbufferSizeBytes, cstringAllocator, ccontext)
	runtime.KeepAlive(ccontextAllocMap)
	runtime.KeepAlive(cstringAllocatorAllocMap)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getDouble(pBundle *APersistableBundle, key string, val *float64) bool {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cval, cvalAllocMap := (*C.double)(unsafe.Pointer(val)), cgoAllocsUnknown
	__ret := C.APersistableBundle_getDouble(cpBundle, ckey, cval)
	runtime.KeepAlive(cvalAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (bool)(__ret)
	return __v
}

func APersistableBundle_getDoubleKeys(pBundle *APersistableBundle, outKeys *string, bufferSizeBytes int32, stringAllocator APersistableBundle_stringAllocator, context unsafe.Pointer) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	cstringAllocator, cstringAllocatorAllocMap := stringAllocator.PassValue()
	ccontext, ccontextAllocMap := context, cgoAllocsUnknown
	__ret := C.APersistableBundle_getDoubleKeys(cpBundle, (**C.char)(unsafe.Pointer(outKeys)), cbufferSizeBytes, cstringAllocator, ccontext)
	runtime.KeepAlive(ccontextAllocMap)
	runtime.KeepAlive(cstringAllocatorAllocMap)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getDoubleVector(pBundle *APersistableBundle, key string, buffer *float64, bufferSizeBytes int32) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cbuffer, cbufferAllocMap := (*C.double)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	__ret := C.APersistableBundle_getDoubleVector(cpBundle, ckey, cbuffer, cbufferSizeBytes)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cbufferAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getDoubleVectorKeys(pBundle *APersistableBundle, outKeys *string, bufferSizeBytes int32, stringAllocator APersistableBundle_stringAllocator, context unsafe.Pointer) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	cstringAllocator, cstringAllocatorAllocMap := stringAllocator.PassValue()
	ccontext, ccontextAllocMap := context, cgoAllocsUnknown
	__ret := C.APersistableBundle_getDoubleVectorKeys(cpBundle, (**C.char)(unsafe.Pointer(outKeys)), cbufferSizeBytes, cstringAllocator, ccontext)
	runtime.KeepAlive(ccontextAllocMap)
	runtime.KeepAlive(cstringAllocatorAllocMap)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getInt(pBundle *APersistableBundle, key string, val *int32) bool {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cval, cvalAllocMap := (*C.int)(unsafe.Pointer(val)), cgoAllocsUnknown
	__ret := C.APersistableBundle_getInt(cpBundle, ckey, cval)
	runtime.KeepAlive(cvalAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (bool)(__ret)
	return __v
}

func APersistableBundle_getIntKeys(pBundle *APersistableBundle, outKeys *string, bufferSizeBytes int32, stringAllocator APersistableBundle_stringAllocator, context unsafe.Pointer) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	cstringAllocator, cstringAllocatorAllocMap := stringAllocator.PassValue()
	ccontext, ccontextAllocMap := context, cgoAllocsUnknown
	__ret := C.APersistableBundle_getIntKeys(cpBundle, (**C.char)(unsafe.Pointer(outKeys)), cbufferSizeBytes, cstringAllocator, ccontext)
	runtime.KeepAlive(ccontextAllocMap)
	runtime.KeepAlive(cstringAllocatorAllocMap)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getIntVector(pBundle *APersistableBundle, key string, buffer *int32, bufferSizeBytes int32) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cbuffer, cbufferAllocMap := (*C.int)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	__ret := C.APersistableBundle_getIntVector(cpBundle, ckey, cbuffer, cbufferSizeBytes)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cbufferAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getIntVectorKeys(pBundle *APersistableBundle, outKeys *string, bufferSizeBytes int32, stringAllocator APersistableBundle_stringAllocator, context unsafe.Pointer) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	cstringAllocator, cstringAllocatorAllocMap := stringAllocator.PassValue()
	ccontext, ccontextAllocMap := context, cgoAllocsUnknown
	__ret := C.APersistableBundle_getIntVectorKeys(cpBundle, (**C.char)(unsafe.Pointer(outKeys)), cbufferSizeBytes, cstringAllocator, ccontext)
	runtime.KeepAlive(ccontextAllocMap)
	runtime.KeepAlive(cstringAllocatorAllocMap)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getLong(pBundle *APersistableBundle, key string, val *int64) bool {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cval, cvalAllocMap := (*C.int64_t)(unsafe.Pointer(val)), cgoAllocsUnknown
	__ret := C.APersistableBundle_getLong(cpBundle, ckey, cval)
	runtime.KeepAlive(cvalAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (bool)(__ret)
	return __v
}

func APersistableBundle_getLongKeys(pBundle *APersistableBundle, outKeys *string, bufferSizeBytes int32, stringAllocator APersistableBundle_stringAllocator, context unsafe.Pointer) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	cstringAllocator, cstringAllocatorAllocMap := stringAllocator.PassValue()
	ccontext, ccontextAllocMap := context, cgoAllocsUnknown
	__ret := C.APersistableBundle_getLongKeys(cpBundle, (**C.char)(unsafe.Pointer(outKeys)), cbufferSizeBytes, cstringAllocator, ccontext)
	runtime.KeepAlive(ccontextAllocMap)
	runtime.KeepAlive(cstringAllocatorAllocMap)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getLongVector(pBundle *APersistableBundle, key string, buffer *int64, bufferSizeBytes int32) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cbuffer, cbufferAllocMap := (*C.int64_t)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	__ret := C.APersistableBundle_getLongVector(cpBundle, ckey, cbuffer, cbufferSizeBytes)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cbufferAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getLongVectorKeys(pBundle *APersistableBundle, outKeys *string, bufferSizeBytes int32, stringAllocator APersistableBundle_stringAllocator, context unsafe.Pointer) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	cstringAllocator, cstringAllocatorAllocMap := stringAllocator.PassValue()
	ccontext, ccontextAllocMap := context, cgoAllocsUnknown
	__ret := C.APersistableBundle_getLongVectorKeys(cpBundle, (**C.char)(unsafe.Pointer(outKeys)), cbufferSizeBytes, cstringAllocator, ccontext)
	runtime.KeepAlive(ccontextAllocMap)
	runtime.KeepAlive(cstringAllocatorAllocMap)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getPersistableBundle(pBundle *APersistableBundle, key string, outBundle **APersistableBundle) bool {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	coutBundle, coutBundleAllocMap := (**C.APersistableBundle)(unsafe.Pointer(outBundle)), cgoAllocsUnknown
	var pinnercoutBundle runtime.Pinner
	pinnercoutBundle.Pin(outBundle)
	if outBundle != nil {
		pinnercoutBundle.Pin(unsafe.Pointer(*outBundle))
	}
	defer pinnercoutBundle.Unpin()
	__ret := C.APersistableBundle_getPersistableBundle(cpBundle, ckey, coutBundle)
	runtime.KeepAlive(coutBundleAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (bool)(__ret)
	return __v
}

func APersistableBundle_getPersistableBundleKeys(pBundle *APersistableBundle, outKeys *string, bufferSizeBytes int32, stringAllocator APersistableBundle_stringAllocator, context unsafe.Pointer) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	cstringAllocator, cstringAllocatorAllocMap := stringAllocator.PassValue()
	ccontext, ccontextAllocMap := context, cgoAllocsUnknown
	__ret := C.APersistableBundle_getPersistableBundleKeys(cpBundle, (**C.char)(unsafe.Pointer(outKeys)), cbufferSizeBytes, cstringAllocator, ccontext)
	runtime.KeepAlive(ccontextAllocMap)
	runtime.KeepAlive(cstringAllocatorAllocMap)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getString(pBundle *APersistableBundle, key string, val *string, stringAllocator APersistableBundle_stringAllocator, context unsafe.Pointer) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cstringAllocator, cstringAllocatorAllocMap := stringAllocator.PassValue()
	ccontext, ccontextAllocMap := context, cgoAllocsUnknown
	__ret := C.APersistableBundle_getString(cpBundle, ckey, (**C.char)(unsafe.Pointer(val)), cstringAllocator, ccontext)
	runtime.KeepAlive(ccontextAllocMap)
	runtime.KeepAlive(cstringAllocatorAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getStringKeys(pBundle *APersistableBundle, outKeys *string, bufferSizeBytes int32, stringAllocator APersistableBundle_stringAllocator, context unsafe.Pointer) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	cstringAllocator, cstringAllocatorAllocMap := stringAllocator.PassValue()
	ccontext, ccontextAllocMap := context, cgoAllocsUnknown
	__ret := C.APersistableBundle_getStringKeys(cpBundle, (**C.char)(unsafe.Pointer(outKeys)), cbufferSizeBytes, cstringAllocator, ccontext)
	runtime.KeepAlive(ccontextAllocMap)
	runtime.KeepAlive(cstringAllocatorAllocMap)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getStringVector(pBundle *APersistableBundle, key string, buffer *string, bufferSizeBytes int32, stringAllocator APersistableBundle_stringAllocator, context unsafe.Pointer) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	cstringAllocator, cstringAllocatorAllocMap := stringAllocator.PassValue()
	ccontext, ccontextAllocMap := context, cgoAllocsUnknown
	__ret := C.APersistableBundle_getStringVector(cpBundle, ckey, (**C.char)(unsafe.Pointer(buffer)), cbufferSizeBytes, cstringAllocator, ccontext)
	runtime.KeepAlive(ccontextAllocMap)
	runtime.KeepAlive(cstringAllocatorAllocMap)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_getStringVectorKeys(pBundle *APersistableBundle, outKeys *string, bufferSizeBytes int32, stringAllocator APersistableBundle_stringAllocator, context unsafe.Pointer) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	cbufferSizeBytes, cbufferSizeBytesAllocMap := (C.int)(bufferSizeBytes), cgoAllocsUnknown
	cstringAllocator, cstringAllocatorAllocMap := stringAllocator.PassValue()
	ccontext, ccontextAllocMap := context, cgoAllocsUnknown
	__ret := C.APersistableBundle_getStringVectorKeys(cpBundle, (**C.char)(unsafe.Pointer(outKeys)), cbufferSizeBytes, cstringAllocator, ccontext)
	runtime.KeepAlive(ccontextAllocMap)
	runtime.KeepAlive(cstringAllocatorAllocMap)
	runtime.KeepAlive(cbufferSizeBytesAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_isEqual(lhs *APersistableBundle, rhs *APersistableBundle) bool {
	clhs, clhsAllocMap := (*C.APersistableBundle)(unsafe.Pointer(lhs)), cgoAllocsUnknown
	crhs, crhsAllocMap := (*C.APersistableBundle)(unsafe.Pointer(rhs)), cgoAllocsUnknown
	__ret := C.APersistableBundle_isEqual(clhs, crhs)
	runtime.KeepAlive(crhsAllocMap)
	runtime.KeepAlive(clhsAllocMap)
	__v := (bool)(__ret)
	return __v
}

func APersistableBundle_new() *APersistableBundle {
	__ret := C.APersistableBundle_new()
	__v := (*APersistableBundle)(unsafe.Pointer(__ret))
	return __v
}

func APersistableBundle_putBoolean(pBundle *APersistableBundle, key string, val bool) {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cval, cvalAllocMap := (C._Bool)(val), cgoAllocsUnknown
	C.APersistableBundle_putBoolean(cpBundle, ckey, cval)
	runtime.KeepAlive(cvalAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
}

func APersistableBundle_putBooleanVector(pBundle *APersistableBundle, key string, vec *bool, num int32) {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cvec, cvecAllocMap := (*C._Bool)(unsafe.Pointer(vec)), cgoAllocsUnknown
	cnum, cnumAllocMap := (C.int)(num), cgoAllocsUnknown
	C.APersistableBundle_putBooleanVector(cpBundle, ckey, cvec, cnum)
	runtime.KeepAlive(cnumAllocMap)
	runtime.KeepAlive(cvecAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
}

func APersistableBundle_putDouble(pBundle *APersistableBundle, key string, val float64) {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cval, cvalAllocMap := (C.double)(val), cgoAllocsUnknown
	C.APersistableBundle_putDouble(cpBundle, ckey, cval)
	runtime.KeepAlive(cvalAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
}

func APersistableBundle_putDoubleVector(pBundle *APersistableBundle, key string, vec *float64, num int32) {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cvec, cvecAllocMap := (*C.double)(unsafe.Pointer(vec)), cgoAllocsUnknown
	cnum, cnumAllocMap := (C.int)(num), cgoAllocsUnknown
	C.APersistableBundle_putDoubleVector(cpBundle, ckey, cvec, cnum)
	runtime.KeepAlive(cnumAllocMap)
	runtime.KeepAlive(cvecAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
}

func APersistableBundle_putInt(pBundle *APersistableBundle, key string, val int32) {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cval, cvalAllocMap := (C.int)(val), cgoAllocsUnknown
	C.APersistableBundle_putInt(cpBundle, ckey, cval)
	runtime.KeepAlive(cvalAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
}

func APersistableBundle_putIntVector(pBundle *APersistableBundle, key string, vec *int32, num int32) {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cvec, cvecAllocMap := (*C.int)(unsafe.Pointer(vec)), cgoAllocsUnknown
	cnum, cnumAllocMap := (C.int)(num), cgoAllocsUnknown
	C.APersistableBundle_putIntVector(cpBundle, ckey, cvec, cnum)
	runtime.KeepAlive(cnumAllocMap)
	runtime.KeepAlive(cvecAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
}

func APersistableBundle_putLong(pBundle *APersistableBundle, key string, val int64) {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cval, cvalAllocMap := (C.int64_t)(val), cgoAllocsUnknown
	C.APersistableBundle_putLong(cpBundle, ckey, cval)
	runtime.KeepAlive(cvalAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
}

func APersistableBundle_putLongVector(pBundle *APersistableBundle, key string, vec *int64, num int32) {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cvec, cvecAllocMap := (*C.int64_t)(unsafe.Pointer(vec)), cgoAllocsUnknown
	cnum, cnumAllocMap := (C.int)(num), cgoAllocsUnknown
	C.APersistableBundle_putLongVector(cpBundle, ckey, cvec, cnum)
	runtime.KeepAlive(cnumAllocMap)
	runtime.KeepAlive(cvecAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
}

func APersistableBundle_putPersistableBundle(pBundle *APersistableBundle, key string, val *APersistableBundle) {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cval, cvalAllocMap := (*C.APersistableBundle)(unsafe.Pointer(val)), cgoAllocsUnknown
	C.APersistableBundle_putPersistableBundle(cpBundle, ckey, cval)
	runtime.KeepAlive(cvalAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
}

func APersistableBundle_putString(pBundle *APersistableBundle, key string, val string) {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cval, cvalAllocMap := UnpackPCharString(val)
	C.APersistableBundle_putString(cpBundle, ckey, cval)
	runtime.KeepAlive(cvalAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
}

func APersistableBundle_putStringVector(pBundle *APersistableBundle, key string, vec *string, num int32) {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	ckey, ckeyAllocMap := UnpackPCharString(key)
	cnum, cnumAllocMap := (C.int)(num), cgoAllocsUnknown
	C.APersistableBundle_putStringVector(cpBundle, ckey, (**C.char)(unsafe.Pointer(vec)), cnum)
	runtime.KeepAlive(cnumAllocMap)
	runtime.KeepAlive(ckeyAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
}

func APersistableBundle_readFromParcel(parcel *AParcel, outPBundle **APersistableBundle) Binder_status_t {
	cparcel, cparcelAllocMap := (*C.AParcel)(unsafe.Pointer(parcel)), cgoAllocsUnknown
	coutPBundle, coutPBundleAllocMap := (**C.APersistableBundle)(unsafe.Pointer(outPBundle)), cgoAllocsUnknown
	var pinnercoutPBundle runtime.Pinner
	pinnercoutPBundle.Pin(outPBundle)
	if outPBundle != nil {
		pinnercoutPBundle.Pin(unsafe.Pointer(*outPBundle))
	}
	defer pinnercoutPBundle.Unpin()
	__ret := C.APersistableBundle_readFromParcel(cparcel, coutPBundle)
	runtime.KeepAlive(coutPBundleAllocMap)
	runtime.KeepAlive(cparcelAllocMap)
	__v := (Binder_status_t)(__ret)
	return __v
}

func APersistableBundle_size(pBundle *APersistableBundle) int32 {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	__ret := C.APersistableBundle_size(cpBundle)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (int32)(__ret)
	return __v
}

func APersistableBundle_writeToParcel(pBundle *APersistableBundle, parcel *AParcel) Binder_status_t {
	cpBundle, cpBundleAllocMap := (*C.APersistableBundle)(unsafe.Pointer(pBundle)), cgoAllocsUnknown
	cparcel, cparcelAllocMap := (*C.AParcel)(unsafe.Pointer(parcel)), cgoAllocsUnknown
	__ret := C.APersistableBundle_writeToParcel(cpBundle, cparcel)
	runtime.KeepAlive(cparcelAllocMap)
	runtime.KeepAlive(cpBundleAllocMap)
	__v := (Binder_status_t)(__ret)
	return __v
}
