package headerspec

import (
	"crypto/md5"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// GenerateCapiPackage generates a complete capi/ Go package from the manifest
// and extracted declarations. It writes doc.go, types.go, const.go,
// cgo_helpers.go, cgo_helpers.h, and functions.go into outDir.
func GenerateCapiPackage(
	manifest *Manifest,
	decls *Declarations,
	outDir string,
) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("creating output directory %s: %w", outDir, err)
	}

	pkgName := manifest.Generator.PackageName
	preamble := buildCGoPreamble(manifest)

	// Index typedefs for lookup during function generation.
	typedefByName := indexTypedefs(decls)

	// Index which typedef names are enum typedefs (for typed const blocks).
	enumTypedefSet := buildEnumTypedefSet(decls)

	// Collect callback typedefs.
	var callbacks []TypedefInfo
	for _, td := range decls.Typedefs {
		if td.IsFuncPtr {
			callbacks = append(callbacks, td)
		}
	}

	files := map[string]string{}

	files["doc.go"] = generateDocGo(pkgName, manifest.Generator.PackageDescription)
	files["types.go"] = generateTypesGo(pkgName, preamble, decls, callbacks)
	files["const.go"] = generateConstGo(pkgName, preamble, decls, enumTypedefSet)
	files["cgo_helpers.go"] = generateCgoHelpersGo(pkgName, preamble, decls, callbacks, typedefByName)
	files["cgo_helpers.h"] = generateCgoHelpersH(manifest, callbacks)
	files[pkgName+".go"] = generateFunctionsGo(pkgName, preamble, decls, typedefByName, callbacks)

	for name, content := range files {
		path := filepath.Join(outDir, name)

		// Format Go files with go/format; leave .h files as-is.
		if strings.HasSuffix(name, ".go") {
			formatted, err := format.Source([]byte(content))
			if err != nil {
				// Write the unformatted file for debugging, then return the error.
				_ = os.WriteFile(path, []byte(content), 0644)
				return fmt.Errorf("formatting %s: %w", name, err)
			}
			content = string(formatted)
		}

		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
	}

	return nil
}

// buildCGoPreamble constructs the CGo comment block with LDFLAGS and includes.
func buildCGoPreamble(manifest *Manifest) string {
	var sb strings.Builder
	sb.WriteString("/*\n")

	for _, fg := range manifest.Generator.FlagGroups {
		sb.WriteString("#cgo ")
		sb.WriteString(fg.Name)
		sb.WriteString(": ")
		sb.WriteString(strings.Join(fg.Flags, " "))
		sb.WriteString("\n")
	}

	for _, inc := range manifest.Generator.Includes {
		fmt.Fprintf(&sb, "#include \"%s\"\n", inc)
	}
	sb.WriteString("#include <stdlib.h>\n")
	sb.WriteString("#include \"cgo_helpers.h\"\n")
	sb.WriteString("*/")

	return sb.String()
}

// indexTypedefs creates a map from typedef name to TypedefInfo.
func indexTypedefs(decls *Declarations) map[string]*TypedefInfo {
	m := make(map[string]*TypedefInfo, len(decls.Typedefs))
	for i := range decls.Typedefs {
		m[decls.Typedefs[i].Name] = &decls.Typedefs[i]
	}
	return m
}

// buildEnumTypedefSet returns the set of typedef names that are enum typedefs.
func buildEnumTypedefSet(decls *Declarations) map[string]bool {
	set := make(map[string]bool)
	for _, ei := range decls.Enums {
		if ei.TypedefName != "" {
			set[ei.TypedefName] = true
		}
	}
	return set
}

const generatedHeader = "// Code generated by headerspec. DO NOT EDIT.\n\n"

// generateDocGo generates the doc.go file content.
func generateDocGo(pkgName string, description string) string {
	var sb strings.Builder
	sb.WriteString(generatedHeader)
	if description != "" {
		fmt.Fprintf(&sb, "/*\n%s\n*/\n", description)
	}
	fmt.Fprintf(&sb, "package %s\n", pkgName)
	return sb.String()
}

// generateTypesGo generates types.go with opaque struct aliases, complete struct
// aliases, and callback func type declarations.
func generateTypesGo(
	pkgName string,
	preamble string,
	decls *Declarations,
	callbacks []TypedefInfo,
) string {
	// Check if any callback param uses unsafe.Pointer.
	needsUnsafe := false
	for _, cb := range callbacks {
		for _, p := range cb.FuncParams {
			goType := cTypeToGoType(p.Type)
			if goType == "unsafe.Pointer" {
				needsUnsafe = true
				break
			}
		}
		if needsUnsafe {
			break
		}
	}

	var sb strings.Builder
	sb.WriteString(generatedHeader)
	fmt.Fprintf(&sb, "package %s\n\n", pkgName)
	sb.WriteString(preamble)
	sb.WriteString("\nimport \"C\"\n")
	if needsUnsafe {
		sb.WriteString("import \"unsafe\"\n")
	}
	sb.WriteString("\n")

	callbackSet := make(map[string]bool, len(callbacks))
	for _, cb := range callbacks {
		callbackSet[cb.Name] = true
	}

	// Write opaque struct type aliases and complete struct aliases.
	for _, td := range decls.Typedefs {
		if td.IsFuncPtr {
			continue
		}
		if td.IsEnumTypedef {
			continue // Handled in const.go as typed enums.
		}
		if td.IsOpaqueStruct {
			fmt.Fprintf(&sb, "type %s C.%s\n\n", td.Name, td.Name)
			continue
		}

		// Non-opaque struct typedef: type alias to C type.
		if strings.HasPrefix(td.UnderlyingType, "struct ") {
			fmt.Fprintf(&sb, "type %s C.%s\n\n", td.Name, td.Name)
			continue
		}

		// Skip plain integer/bool typedefs that will be handled as enum
		// base types in const.go, or are just type aliases.
		// Only emit struct-like typedefs here.
	}

	// Write complete structs that are NOT typedefs (e.g. directly declared structs).
	for _, si := range decls.Structs {
		if si.IsComplete {
			// Check if a typedef already covers this struct.
			alreadyCovered := false
			for _, td := range decls.Typedefs {
				if td.Name == si.Name {
					alreadyCovered = true
					break
				}
			}
			if !alreadyCovered {
				fmt.Fprintf(&sb, "type %s C.%s\n\n", si.Name, si.Name)
			}
		}
	}

	// Write callback func types.
	for _, cb := range callbacks {
		fmt.Fprintf(&sb, "type %s %s\n\n", cb.Name, callbackGoFuncType(cb, decls))
	}

	return sb.String()
}

// callbackGoFuncType builds the Go function type signature for a callback typedef.
func callbackGoFuncType(td TypedefInfo, decls *Declarations) string {
	var sb strings.Builder
	sb.WriteString("func(")
	for i, p := range td.FuncParams {
		if i > 0 {
			sb.WriteString(", ")
		}
		name := p.Name
		if name == "" {
			name = fmt.Sprintf("p%d", i)
		}
		goType := cTypeToGoType(p.Type)
		fmt.Fprintf(&sb, "%s %s", name, goType)
	}
	sb.WriteString(")")

	retType := cTypeToGoType(td.FuncReturn)
	if retType != "" {
		fmt.Fprintf(&sb, " %s", retType)
	}

	return sb.String()
}

// generateConstGo generates const.go with enum constant blocks.
func generateConstGo(
	pkgName string,
	preamble string,
	decls *Declarations,
	enumTypedefSet map[string]bool,
) string {
	var sb strings.Builder
	sb.WriteString(generatedHeader)
	fmt.Fprintf(&sb, "package %s\n\n", pkgName)
	sb.WriteString(preamble)
	sb.WriteString("\nimport \"C\"\n\n")

	for _, ei := range decls.Enums {
		groupName := ei.TypedefName
		if groupName == "" {
			groupName = ei.Name
		}
		if groupName == "" {
			groupName = deriveEnumGroupName(ei.Constants)
		}
		if groupName == "" || len(ei.Constants) == 0 {
			continue
		}

		isTypedEnum := enumTypedefSet[groupName]

		if isTypedEnum {
			// Emit Go type for the enum typedef.
			goBaseType := enumBaseGoType(ei.FixedType)
			fmt.Fprintf(&sb, "type %s %s\n\n", groupName, goBaseType)

			// Typed const block.
			sb.WriteString("const (\n")
			for _, c := range ei.Constants {
				fmt.Fprintf(&sb, "\t%s %s = %d\n", c.Name, groupName, c.Value)
			}
			sb.WriteString(")\n\n")
		} else {
			// Untyped const block.
			sb.WriteString("const (\n")
			for _, c := range ei.Constants {
				fmt.Fprintf(&sb, "\t%s = %d\n", c.Name, c.Value)
			}
			sb.WriteString(")\n\n")
		}
	}

	return sb.String()
}

// enumBaseGoType converts a C enum fixed type to a Go type.
// If empty (no fixed type), defaults to int32 (C enum default).
func enumBaseGoType(fixedType string) string {
	if fixedType == "" {
		return "int32"
	}
	return cTypeToGoType(fixedType)
}

// generateCgoHelpersGo generates cgo_helpers.go with CgoAllocMap, SliceHeader,
// callback proxy infrastructure, and string/slice helper functions.
func generateCgoHelpersGo(
	pkgName string,
	preamble string,
	decls *Declarations,
	callbacks []TypedefInfo,
	typedefByName map[string]*TypedefInfo,
) string {
	hasStrHelper := needsStringHelper(decls)

	var sb strings.Builder
	sb.WriteString(generatedHeader)
	fmt.Fprintf(&sb, "package %s\n\n", pkgName)
	sb.WriteString(preamble)
	sb.WriteString("\nimport \"C\"\n")
	sb.WriteString("import (\n")
	if hasStrHelper {
		sb.WriteString("\t\"runtime\"\n")
	}
	sb.WriteString("\t\"sync\"\n")
	sb.WriteString("\t\"unsafe\"\n")
	sb.WriteString(")\n\n")

	// CgoAllocMap.
	sb.WriteString(cgoAllocMapCode)

	// SliceHeader.
	sb.WriteString(sliceHeaderCode)

	// Callback proxy code for each callback typedef.
	for _, cb := range callbacks {
		sb.WriteString(generateCallbackProxy(cb, decls, typedefByName))
	}

	// UnpackPCharString helper (for string parameters).
	if hasStrHelper {
		sb.WriteString(unpackPCharStringCode)
	}

	return sb.String()
}

const cgoAllocMapCode = `// CgoAllocMap stores pointers to C allocated memory for future reference.
type CgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(CgoAllocMap)

func (a *CgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *CgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *CgoAllocMap) Borrow(b *CgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *CgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

`

const sliceHeaderCode = `type SliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

`

const unpackPCharStringCode = `// UnpackPCharString copies the data from Go string as *C.char.
func UnpackPCharString(str string) (*C.char, *CgoAllocMap) {
	allocs := new(CgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *CgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CString(str))
	allocs.Add(mem0)
	return (*C.char)(mem0), allocs
}

`

// needsStringHelper returns true if any function has a string parameter.
func needsStringHelper(decls *Declarations) bool {
	for _, fn := range decls.Functions {
		for _, p := range fn.Params {
			cType := stripNullabilityAnnotations(p.Type)
			if cType == "const char *" || cType == "char *" || cType == "const char *const" {
				return true
			}
		}
	}
	return false
}

// callbackHashSuffix computes the 8-hex-digit hash suffix used for callback
// proxy names (matching c-for-go's CRC32-based naming).
func callbackHashSuffix(name string) string {
	h := md5.Sum([]byte(name))
	return fmt.Sprintf("%x", h[:4])
}

// generateCallbackProxy generates PassRef, PassValue, NewXRef, and the
// //export proxy function for a single callback typedef.
func generateCallbackProxy(
	cb TypedefInfo,
	decls *Declarations,
	typedefByName map[string]*TypedefInfo,
) string {
	hash := callbackHashSuffix(cb.Name)
	upperHash := strings.ToUpper(hash)
	lowerHash := strings.ToLower(hash)
	varName := unexport(cb.Name) + upperHash + "Func"
	proxyExportName := cb.Name + upperHash
	proxyCName := cb.Name + "_" + lowerHash

	var sb strings.Builder

	// PassRef method.
	fmt.Fprintf(&sb, "func (x %s) PassRef() (ref *C.%s, allocs *CgoAllocMap) {\n", cb.Name, cb.Name)
	sb.WriteString("\tif x == nil {\n\t\treturn nil, nil\n\t}\n")
	fmt.Fprintf(&sb, "\tif %s == nil {\n\t\t%s = x\n\t}\n", varName, varName)
	fmt.Fprintf(&sb, "\treturn (*C.%s)(C.%s), nil\n", cb.Name, proxyCName)
	sb.WriteString("}\n\n")

	// PassValue method.
	fmt.Fprintf(&sb, "func (x %s) PassValue() (ref C.%s, allocs *CgoAllocMap) {\n", cb.Name, cb.Name)
	sb.WriteString("\tif x == nil {\n\t\treturn nil, nil\n\t}\n")
	fmt.Fprintf(&sb, "\tif %s == nil {\n\t\t%s = x\n\t}\n", varName, varName)
	fmt.Fprintf(&sb, "\treturn (C.%s)(C.%s), nil\n", cb.Name, proxyCName)
	sb.WriteString("}\n\n")

	// NewXRef function.
	fmt.Fprintf(&sb, "func New%sRef(ref unsafe.Pointer) *%s {\n", cb.Name, cb.Name)
	fmt.Fprintf(&sb, "\treturn (*%s)(ref)\n", cb.Name)
	sb.WriteString("}\n\n")

	// //export proxy function.
	fmt.Fprintf(&sb, "//export %s\n", proxyExportName)
	fmt.Fprintf(&sb, "func %s(", proxyExportName)

	// Build proxy parameters with C types.
	for i, p := range cb.FuncParams {
		if i > 0 {
			sb.WriteString(", ")
		}
		name := p.Name
		if name == "" {
			name = fmt.Sprintf("p%d", i)
		}
		cParamType := callbackProxyCParamType(p.Type)
		fmt.Fprintf(&sb, "c%s %s", name, cParamType)
	}
	sb.WriteString(")")

	// Return type.
	retCType := callbackProxyCReturnType(cb.FuncReturn)
	if retCType != "" {
		fmt.Fprintf(&sb, " %s", retCType)
	}
	sb.WriteString(" {\n")

	// Body: convert C params to Go and call the stored function.
	fmt.Fprintf(&sb, "\tif %s != nil {\n", varName)
	var argNames []string
	for i, p := range cb.FuncParams {
		name := p.Name
		if name == "" {
			name = fmt.Sprintf("p%d", i)
		}
		goVarName := name + lowerHash
		convCode := callbackParamConversion(name, goVarName, p.Type, lowerHash, decls, typedefByName)
		sb.WriteString(convCode)
		argNames = append(argNames, goVarName)
	}

	callExpr := fmt.Sprintf("%s(%s)", varName, strings.Join(argNames, ", "))
	goRetType := cTypeToGoType(cb.FuncReturn)
	if goRetType != "" {
		fmt.Fprintf(&sb, "\t\tret%s := %s\n", lowerHash, callExpr)
		retConv := goToCReturn(lowerHash, cb.FuncReturn)
		fmt.Fprintf(&sb, "\t\tret, _ := %s, cgoAllocsUnknown\n", retConv)
		sb.WriteString("\t\treturn ret\n")
	} else {
		fmt.Fprintf(&sb, "\t\t%s\n", callExpr)
		sb.WriteString("\t\treturn\n")
	}
	sb.WriteString("\t}\n")
	sb.WriteString("\tpanic(\"callback func has not been set (race?)\")\n")
	sb.WriteString("}\n\n")

	// Variable to store the callback.
	fmt.Fprintf(&sb, "var %s %s\n\n", varName, cb.Name)

	return sb.String()
}

// callbackProxyCParamType returns the CGo type to use for a callback proxy
// parameter given the original C type.
func callbackProxyCParamType(cType string) string {
	cType = stripNullabilityAnnotations(cType)

	switch cType {
	case "void *", "const void *":
		return "unsafe.Pointer"
	case "const char *", "char *":
		return "*C.char"
	}

	if strings.HasSuffix(cType, " **") {
		base := strings.TrimSuffix(cType, " **")
		base = strings.TrimPrefix(base, "const ")
		base = strings.TrimSpace(base)
		return "**C." + base
	}

	if strings.HasSuffix(cType, " *") || strings.HasSuffix(cType, "*") {
		base := strings.TrimSuffix(cType, " *")
		base = strings.TrimSuffix(base, "*")
		base = strings.TrimPrefix(base, "const ")
		base = strings.TrimPrefix(base, "struct ")
		base = strings.TrimSpace(base)
		return "*C." + base
	}

	// Scalar types.
	return goTypeToCGoType(cTypeToGoType(cType), cType)
}

// callbackProxyCReturnType returns the CGo return type for a callback proxy.
func callbackProxyCReturnType(cType string) string {
	goType := cTypeToGoType(cType)
	if goType == "" {
		return ""
	}
	return goTypeToCGoType(goType, cType)
}

// callbackParamConversion generates code to convert a C callback parameter
// to its Go equivalent.
func callbackParamConversion(
	paramName string,
	goVarName string,
	cType string,
	hashSuffix string,
	decls *Declarations,
	typedefByName map[string]*TypedefInfo,
) string {
	cType = stripNullabilityAnnotations(cType)

	switch cType {
	case "void *", "const void *":
		return fmt.Sprintf("\t\t%s := (unsafe.Pointer)(unsafe.Pointer(c%s))\n", goVarName, paramName)
	case "const char *", "char *":
		return fmt.Sprintf("\t\t%s := C.GoString(c%s)\n", goVarName, paramName)
	}

	if strings.HasSuffix(cType, " *") || strings.HasSuffix(cType, "*") {
		base := strings.TrimSuffix(cType, " *")
		base = strings.TrimSuffix(base, "*")
		base = strings.TrimPrefix(base, "const ")
		base = strings.TrimPrefix(base, "struct ")
		base = strings.TrimSpace(base)

		goBase := cTypeToGoType(base)

		// Check if this is an opaque struct pointer.
		if td, ok := typedefByName[base]; ok && td.IsOpaqueStruct {
			return fmt.Sprintf("\t\t%s := (*%s)(unsafe.Pointer(c%s))\n", goVarName, goBase, paramName)
		}

		// For other struct pointers, use the SliceHeader trick (matching c-for-go).
		return fmt.Sprintf("\t\t%s := (*%s)(unsafe.Pointer(c%s))\n", goVarName, goBase, paramName)
	}

	// Scalar conversion.
	goType := cTypeToGoType(cType)
	return fmt.Sprintf("\t\t%s := (%s)(c%s)\n", goVarName, goType, paramName)
}

// goToCReturn generates the expression to convert a Go return value to the C type.
func goToCReturn(hashSuffix string, cType string) string {
	goType := cTypeToGoType(cType)
	cgoType := goTypeToCGoType(goType, cType)
	return fmt.Sprintf("(%s)(ret%s)", cgoType, hashSuffix)
}

// generateCgoHelpersH generates the cgo_helpers.h file with C callback proxy declarations.
func generateCgoHelpersH(
	manifest *Manifest,
	callbacks []TypedefInfo,
) string {
	var sb strings.Builder
	sb.WriteString(generatedHeader)

	for _, inc := range manifest.Generator.Includes {
		fmt.Fprintf(&sb, "#include \"%s\"\n", inc)
	}
	sb.WriteString("#include <stdlib.h>\n")
	sb.WriteString("#pragma once\n\n")
	sb.WriteString("#define __CGOGEN 1\n\n")

	for _, cb := range callbacks {
		hash := callbackHashSuffix(cb.Name)
		lowerHash := strings.ToLower(hash)
		proxyCName := cb.Name + "_" + lowerHash

		cRetType := cTypeToHReturnType(cb.FuncReturn)

		fmt.Fprintf(&sb, "// %s is a proxy for callback %s.\n", proxyCName, cb.Name)
		fmt.Fprintf(&sb, "%s %s(", cRetType, proxyCName)

		for i, p := range cb.FuncParams {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(callbackHParamDecl(p, i))
		}
		sb.WriteString(");\n\n")
	}

	return sb.String()
}

// cTypeToHReturnType converts a C type to its representation in the .h file.
func cTypeToHReturnType(cType string) string {
	cType = stripNullabilityAnnotations(cType)
	if cType == "" || cType == "void" {
		return "void"
	}
	return cType
}

// callbackHParamDecl formats one parameter for the C header declaration.
func callbackHParamDecl(p ParamInfo, index int) string {
	cType := stripNullabilityAnnotations(p.Type)
	name := p.Name
	if name == "" {
		name = fmt.Sprintf("p%d", index)
	}

	// Map C types to their header representation.
	switch cType {
	case "void *", "const void *":
		return "void* " + name
	case "const char *", "char *":
		return "char* " + name
	}

	// Pointer types.
	if strings.HasSuffix(cType, " **") {
		base := strings.TrimSuffix(cType, " **")
		return base + "** " + name
	}
	if strings.HasSuffix(cType, " *") {
		base := strings.TrimSuffix(cType, " *")
		return base + "* " + name
	}

	// Map standard C integer types to their long forms for the header.
	headerType := cTypeToHeaderType(cType)
	return headerType + " " + name
}

// cTypeToHeaderType maps C types to their header-file representation.
func cTypeToHeaderType(cType string) string {
	switch cType {
	case "int32_t":
		return "int"
	case "uint32_t":
		return "unsigned int"
	case "int64_t":
		return "long int"
	case "uint64_t":
		return "unsigned long int"
	case "int16_t":
		return "short int"
	case "uint16_t":
		return "unsigned short int"
	case "int8_t":
		return "signed char"
	case "uint8_t":
		return "unsigned char"
	case "size_t":
		return "unsigned long int"
	case "ssize_t":
		return "long int"
	case "float":
		return "float"
	case "double":
		return "double"
	case "_Bool", "bool":
		return "_Bool"
	case "int":
		return "int"
	}
	return cType
}

// generateFunctionsGo generates the functions.go file with wrapper functions.
func generateFunctionsGo(
	pkgName string,
	preamble string,
	decls *Declarations,
	typedefByName map[string]*TypedefInfo,
	callbacks []TypedefInfo,
) string {
	callbackSet := make(map[string]bool, len(callbacks))
	for _, cb := range callbacks {
		callbackSet[cb.Name] = true
	}

	var sb strings.Builder
	sb.WriteString(generatedHeader)
	fmt.Fprintf(&sb, "package %s\n\n", pkgName)
	sb.WriteString(preamble)
	sb.WriteString("\nimport \"C\"\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"runtime\"\n")
	sb.WriteString("\t\"unsafe\"\n")
	sb.WriteString(")\n\n")

	// Suppress unused import warnings.
	sb.WriteString("var _ runtime.Error\n")
	sb.WriteString("var _ unsafe.Pointer\n\n")

	for _, fn := range decls.Functions {
		sb.WriteString(generateFunction(fn, typedefByName, callbackSet))
	}

	return sb.String()
}

// generateFunction generates a single Go wrapper function.
func generateFunction(
	fn FuncDecl,
	typedefByName map[string]*TypedefInfo,
	callbackSet map[string]bool,
) string {
	var sb strings.Builder

	goParams := buildGoParams(fn.Params, typedefByName, callbackSet)
	goRetType := funcReturnGoType(fn.ReturnType, typedefByName)

	// Function signature.
	fmt.Fprintf(&sb, "func %s(", fn.Name)
	for i, p := range goParams {
		if i > 0 {
			sb.WriteString(", ")
		}
		fmt.Fprintf(&sb, "%s %s", p.name, p.goType)
	}
	sb.WriteString(")")
	if goRetType != "" {
		fmt.Fprintf(&sb, " %s", goRetType)
	}
	sb.WriteString(" {\n")

	// Convert parameters.
	var cArgNames []string
	var keepAliveNames []string

	for _, p := range goParams {
		conv := paramConversion(p, typedefByName, callbackSet)
		sb.WriteString(conv.code)
		cArgNames = append(cArgNames, conv.cVarName)
		keepAliveNames = append(keepAliveNames, conv.keepAliveName)
	}

	// Call C function.
	callExpr := fmt.Sprintf("C.%s(%s)", fn.Name, strings.Join(cArgNames, ", "))

	if goRetType != "" {
		fmt.Fprintf(&sb, "\t__ret := %s\n", callExpr)
	} else {
		fmt.Fprintf(&sb, "\t%s\n", callExpr)
	}

	// runtime.KeepAlive calls in reverse order (matching c-for-go).
	for i := len(keepAliveNames) - 1; i >= 0; i-- {
		if keepAliveNames[i] != "" {
			fmt.Fprintf(&sb, "\truntime.KeepAlive(%s)\n", keepAliveNames[i])
		}
	}

	// Convert and return.
	if goRetType != "" {
		retConv := returnConversion(fn.ReturnType, goRetType, typedefByName)
		sb.WriteString(retConv)
	}

	sb.WriteString("}\n\n")
	return sb.String()
}

type goParam struct {
	name         string
	goType       string
	origCType    string
	isCallback   bool
	isSlice      bool
	isString     bool
	isPtr        bool
	isDoublePtr  bool
	isUnsafePtr  bool
	sliceElemGo  string
	ptrBaseGo    string
	doublePtrGo  string
}

// buildGoParams converts C parameters to Go parameter descriptors.
func buildGoParams(
	params []ParamInfo,
	typedefByName map[string]*TypedefInfo,
	callbackSet map[string]bool,
) []goParam {
	var result []goParam
	for _, p := range params {
		gp := classifyParam(p, typedefByName, callbackSet)
		result = append(result, gp)
	}
	return result
}

// classifyParam determines the Go type and conversion strategy for a parameter.
func classifyParam(
	p ParamInfo,
	typedefByName map[string]*TypedefInfo,
	callbackSet map[string]bool,
) goParam {
	cType := stripNullabilityAnnotations(p.Type)
	gp := goParam{
		name:      p.Name,
		origCType: cType,
	}

	// void * / const void *
	if cType == "void *" || cType == "const void *" {
		gp.goType = "unsafe.Pointer"
		gp.isUnsafePtr = true
		return gp
	}

	// void **
	if cType == "void **" {
		gp.goType = "[]unsafe.Pointer"
		gp.isSlice = true
		gp.sliceElemGo = "unsafe.Pointer"
		return gp
	}

	// const char * / char *
	if cType == "const char *" || cType == "char *" || cType == "const char *const" {
		gp.goType = "string"
		gp.isString = true
		return gp
	}

	// Double pointer: X **
	if strings.HasSuffix(cType, " **") || (strings.HasSuffix(cType, "**") && !strings.Contains(cType, "(")) {
		base := strings.TrimSuffix(cType, "**")
		base = strings.TrimSuffix(base, " ")
		base = strings.TrimPrefix(base, "const ")
		base = strings.TrimSpace(base)
		goBase := cTypeToGoType(base)
		gp.goType = "**" + goBase
		gp.isDoublePtr = true
		gp.doublePtrGo = goBase
		return gp
	}

	// Single pointer to typedef.
	if strings.HasSuffix(cType, " *") {
		base := strings.TrimSuffix(cType, " *")
		base = strings.TrimPrefix(base, "const ")
		base = strings.TrimSpace(base)

		// Check if base is an opaque struct typedef.
		if td, ok := typedefByName[base]; ok {
			if td.IsOpaqueStruct {
				gp.goType = "*" + base
				gp.isPtr = true
				gp.ptrBaseGo = base
				return gp
			}
			if td.IsEnumTypedef {
				// Pointer to enum typedef → slice.
				gp.goType = "[]" + base
				gp.isSlice = true
				gp.sliceElemGo = base
				return gp
			}
			// Pointer to struct typedef (complete struct).
			if strings.HasPrefix(td.UnderlyingType, "struct ") {
				gp.goType = "*" + base
				gp.isPtr = true
				gp.ptrBaseGo = base
				return gp
			}
		}

		// Pointer to scalar types become slices.
		goBase := cTypeToGoType(base)
		if isScalarGoType(goBase) {
			gp.goType = "[]" + goBase
			gp.isSlice = true
			gp.sliceElemGo = goBase
			return gp
		}

		// Pointer to non-scalar: use pointer.
		gp.goType = "*" + goBase
		gp.isPtr = true
		gp.ptrBaseGo = goBase
		return gp
	}

	// Check if it's a callback type.
	if callbackSet[cType] {
		gp.goType = cType
		gp.isCallback = true
		return gp
	}

	// Check if it's a typedef.
	if td, ok := typedefByName[cType]; ok {
		if td.IsEnumTypedef {
			gp.goType = cType
			return gp
		}
		if td.IsOpaqueStruct || strings.HasPrefix(td.UnderlyingType, "struct ") {
			gp.goType = cType
			return gp
		}
	}

	// Plain scalar.
	gp.goType = cTypeToGoType(cType)
	return gp
}

type conversionResult struct {
	code          string
	cVarName      string
	keepAliveName string
}

// paramConversion generates the Go→C conversion code for one parameter.
func paramConversion(
	p goParam,
	typedefByName map[string]*TypedefInfo,
	callbackSet map[string]bool,
) conversionResult {
	cVar := "c" + p.name
	allocVar := cVar + "AllocMap"

	if p.isUnsafePtr {
		return conversionResult{
			code:          fmt.Sprintf("\t%s, %s := %s, cgoAllocsUnknown\n", cVar, allocVar, p.name),
			cVarName:      cVar,
			keepAliveName: allocVar,
		}
	}

	if p.isString {
		return conversionResult{
			code:          fmt.Sprintf("\t%s, %s := UnpackPCharString(%s)\n", cVar, allocVar, p.name),
			cVarName:      cVar,
			keepAliveName: allocVar,
		}
	}

	if p.isCallback {
		return conversionResult{
			code:          fmt.Sprintf("\t%s, %s := %s.PassValue()\n", cVar, allocVar, p.name),
			cVarName:      cVar,
			keepAliveName: allocVar,
		}
	}

	if p.isDoublePtr {
		cgoType := goToCGoPtrType(p.doublePtrGo, p.origCType, typedefByName)
		// Double pointers are cast inline through unsafe.Pointer.
		return conversionResult{
			code:          "",
			cVarName:      fmt.Sprintf("(%s)(unsafe.Pointer(%s))", cgoType, p.name),
			keepAliveName: "",
		}
	}

	if p.isSlice {
		cgoElem := sliceElemToCGoType(p.sliceElemGo, p.origCType)
		code := fmt.Sprintf("\t%s, %s := (*%s)(unsafe.Pointer((*SliceHeader)(unsafe.Pointer(&%s)).Data)), cgoAllocsUnknown\n",
			cVar, allocVar, cgoElem, p.name)
		return conversionResult{
			code:          code,
			cVarName:      cVar,
			keepAliveName: allocVar,
		}
	}

	if p.isPtr {
		cgoType := goToCGoType(p.ptrBaseGo, p.origCType, typedefByName)
		code := fmt.Sprintf("\t%s, %s := (%s)(unsafe.Pointer(%s)), cgoAllocsUnknown\n",
			cVar, allocVar, cgoType, p.name)
		return conversionResult{
			code:          code,
			cVarName:      cVar,
			keepAliveName: allocVar,
		}
	}

	// Scalar conversion.
	cgoType := scalarGoToCGoType(p.goType, p.origCType)
	code := fmt.Sprintf("\t%s, %s := (%s)(%s), cgoAllocsUnknown\n",
		cVar, allocVar, cgoType, p.name)
	return conversionResult{
		code:          code,
		cVarName:      cVar,
		keepAliveName: allocVar,
	}
}

// sliceElemToCGoType maps a Go slice element type to the corresponding C type
// for pointer dereferencing.
func sliceElemToCGoType(goElemType string, origCType string) string {
	// Determine the base C type from the original pointer type.
	cBase := strings.TrimSuffix(origCType, " *")
	cBase = strings.TrimSuffix(cBase, "*")
	cBase = strings.TrimPrefix(cBase, "const ")
	cBase = strings.TrimSpace(cBase)

	switch cBase {
	case "int", "int32_t":
		if cBase == "int" {
			return "C.int"
		}
		return "C.int32_t"
	case "uint32_t":
		return "C.uint32_t"
	case "int64_t":
		return "C.int64_t"
	case "uint64_t":
		return "C.uint64_t"
	case "int16_t":
		return "C.int16_t"
	case "uint16_t":
		return "C.uint16_t"
	case "int8_t":
		return "C.int8_t"
	case "uint8_t":
		return "C.uint8_t"
	case "float":
		return "C.float"
	case "double":
		return "C.double"
	case "size_t":
		return "C.size_t"
	case "ssize_t":
		return "C.ssize_t"
	case "void":
		return "unsafe.Pointer"
	}

	// Default: use the C type name directly.
	return "C." + cBase
}

// goToCGoType maps a Go pointer base type + original C type to a CGo pointer type.
func goToCGoType(goBase string, origCType string, typedefByName map[string]*TypedefInfo) string {
	// Extract the base C type.
	cBase := strings.TrimSuffix(origCType, " *")
	cBase = strings.TrimSuffix(cBase, "*")
	cBase = strings.TrimPrefix(cBase, "const ")
	cBase = strings.TrimPrefix(cBase, "struct ")
	cBase = strings.TrimSpace(cBase)

	return "*C." + cBase
}

// goToCGoPtrType maps a double-pointer Go type to the CGo expression.
func goToCGoPtrType(goBase string, origCType string, typedefByName map[string]*TypedefInfo) string {
	cBase := strings.TrimSuffix(origCType, " **")
	cBase = strings.TrimSuffix(cBase, "**")
	cBase = strings.TrimPrefix(cBase, "const ")
	cBase = strings.TrimSpace(cBase)

	return "**C." + cBase
}

// scalarGoToCGoType maps a Go scalar type + original C type to the CGo cast type.
func scalarGoToCGoType(goType string, origCType string) string {
	origCType = stripNullabilityAnnotations(origCType)

	switch origCType {
	case "int":
		return "C.int"
	case "unsigned int", "unsigned":
		return "C.uint"
	case "int32_t":
		return "C.int32_t"
	case "uint32_t":
		return "C.uint32_t"
	case "int64_t":
		return "C.int64_t"
	case "uint64_t":
		return "C.uint64_t"
	case "int16_t":
		return "C.int16_t"
	case "uint16_t":
		return "C.uint16_t"
	case "int8_t":
		return "C.int8_t"
	case "uint8_t":
		return "C.uint8_t"
	case "float":
		return "C.float"
	case "double":
		return "C.double"
	case "size_t":
		return "C.size_t"
	case "ssize_t":
		return "C.ssize_t"
	case "_Bool", "bool":
		return "C._Bool"
	case "long":
		return "C.long"
	case "unsigned long":
		return "C.ulong"
	case "long long":
		return "C.longlong"
	case "unsigned long long":
		return "C.ulonglong"
	}

	// For typedef types (like Camera_status_t), cast to the C type.
	return "C." + origCType
}

// goTypeToCGoType maps a Go type to the CGo type expression for use in
// callback proxy conversions.
func goTypeToCGoType(goType string, origCType string) string {
	origCType = stripNullabilityAnnotations(origCType)

	// If the original C type is known, prefer that mapping.
	switch origCType {
	case "int":
		return "C.int"
	case "unsigned int", "unsigned":
		return "C.uint"
	case "int32_t":
		return "C.int32_t"
	case "uint32_t":
		return "C.uint32_t"
	case "int64_t":
		return "C.int64_t"
	case "uint64_t":
		return "C.uint64_t"
	case "int16_t":
		return "C.int16_t"
	case "uint16_t":
		return "C.uint16_t"
	case "int8_t":
		return "C.int8_t"
	case "uint8_t":
		return "C.uint8_t"
	case "float":
		return "C.float"
	case "double":
		return "C.double"
	case "size_t":
		return "C.size_t"
	case "ssize_t":
		return "C.ssize_t"
	case "_Bool", "bool":
		return "C._Bool"
	}

	// Fall back to Go type mapping.
	switch goType {
	case "int32":
		return "C.int"
	case "uint32":
		return "C.uint"
	case "int64":
		return "C.long"
	case "uint64":
		return "C.ulong"
	case "int16":
		return "C.short"
	case "uint16":
		return "C.ushort"
	case "int8":
		return "C.schar"
	case "uint8":
		return "C.uchar"
	case "float32":
		return "C.float"
	case "float64":
		return "C.double"
	case "bool":
		return "C._Bool"
	}

	return "C." + goType
}

// funcReturnGoType determines the Go return type for a function.
func funcReturnGoType(
	cRetType string,
	typedefByName map[string]*TypedefInfo,
) string {
	cRetType = stripNullabilityAnnotations(cRetType)

	if cRetType == "" || cRetType == "void" {
		return ""
	}

	// Pointer to opaque struct.
	if strings.HasSuffix(cRetType, " *") {
		base := strings.TrimSuffix(cRetType, " *")
		base = strings.TrimPrefix(base, "const ")
		base = strings.TrimPrefix(base, "struct ")
		base = strings.TrimSpace(base)

		if td, ok := typedefByName[base]; ok && td.IsOpaqueStruct {
			return "*" + base
		}
		return "*" + cTypeToGoType(base)
	}

	// Check for typedef types (enum typedefs get their own Go type).
	if td, ok := typedefByName[cRetType]; ok {
		if td.IsEnumTypedef {
			return cRetType
		}
	}

	return cTypeToGoType(cRetType)
}

// returnConversion generates code to convert a C return value to Go.
func returnConversion(
	cRetType string,
	goRetType string,
	typedefByName map[string]*TypedefInfo,
) string {
	cRetType = stripNullabilityAnnotations(cRetType)

	// Pointer return: reinterpret the C pointer via unsafe.Pointer.
	// The pattern *(**ALooper)(unsafe.Pointer(&__ret)) takes the address of
	// the *C.ALooper value, casts to **ALooper, and dereferences to get *ALooper.
	if strings.HasPrefix(goRetType, "*") {
		return fmt.Sprintf("\t__v := *(*%s)(unsafe.Pointer(&__ret))\n\treturn __v\n", goRetType)
	}

	// Bool return.
	if goRetType == "bool" {
		return "\t__v := (bool)(__ret)\n\treturn __v\n"
	}

	// Enum typedef or scalar return.
	return fmt.Sprintf("\t__v := (%s)(__ret)\n\treturn __v\n", goRetType)
}

// unexport returns the unexported version of a Go identifier.
func unexport(name string) string {
	if len(name) == 0 {
		return name
	}
	first := strings.ToLower(name[:1])
	return first + name[1:]
}



