// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: emulator_controller.proto

package emupb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioFormat_SampleFormat int32

const (
	AudioFormat_AUD_FMT_U8  AudioFormat_SampleFormat = 0
	AudioFormat_AUD_FMT_S16 AudioFormat_SampleFormat = 1
)

// Enum value maps for AudioFormat_SampleFormat.
var (
	AudioFormat_SampleFormat_name = map[int32]string{
		0: "AUD_FMT_U8",
		1: "AUD_FMT_S16",
	}
	AudioFormat_SampleFormat_value = map[string]int32{
		"AUD_FMT_U8":  0,
		"AUD_FMT_S16": 1,
	}
)

func (x AudioFormat_SampleFormat) Enum() *AudioFormat_SampleFormat {
	p := new(AudioFormat_SampleFormat)
	*p = x
	return p
}

func (x AudioFormat_SampleFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioFormat_SampleFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_emulator_controller_proto_enumTypes[0].Descriptor()
}

func (AudioFormat_SampleFormat) Type() protoreflect.EnumType {
	return &file_emulator_controller_proto_enumTypes[0]
}

func (x AudioFormat_SampleFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioFormat_SampleFormat.Descriptor instead.
func (AudioFormat_SampleFormat) EnumDescriptor() ([]byte, []int) {
	return file_emulator_controller_proto_rawDescGZIP(), []int{0, 0}
}

type AudioFormat_Channels int32

const (
	AudioFormat_Mono   AudioFormat_Channels = 0
	AudioFormat_Stereo AudioFormat_Channels = 1
)

// Enum value maps for AudioFormat_Channels.
var (
	AudioFormat_Channels_name = map[int32]string{
		0: "Mono",
		1: "Stereo",
	}
	AudioFormat_Channels_value = map[string]int32{
		"Mono":   0,
		"Stereo": 1,
	}
)

func (x AudioFormat_Channels) Enum() *AudioFormat_Channels {
	p := new(AudioFormat_Channels)
	*p = x
	return p
}

func (x AudioFormat_Channels) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioFormat_Channels) Descriptor() protoreflect.EnumDescriptor {
	return file_emulator_controller_proto_enumTypes[1].Descriptor()
}

func (AudioFormat_Channels) Type() protoreflect.EnumType {
	return &file_emulator_controller_proto_enumTypes[1]
}

func (x AudioFormat_Channels) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioFormat_Channels.Descriptor instead.
func (AudioFormat_Channels) EnumDescriptor() ([]byte, []int) {
	return file_emulator_controller_proto_rawDescGZIP(), []int{0, 1}
}

type AudioFormat struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	SamplingRate  uint64                   `protobuf:"varint,1,opt,name=samplingRate,proto3" json:"samplingRate,omitempty"`
	Channels      AudioFormat_Channels     `protobuf:"varint,2,opt,name=channels,proto3,enum=android.emulation.control.AudioFormat_Channels" json:"channels,omitempty"`
	Format        AudioFormat_SampleFormat `protobuf:"varint,3,opt,name=format,proto3,enum=android.emulation.control.AudioFormat_SampleFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFormat) Reset() {
	*x = AudioFormat{}
	mi := &file_emulator_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFormat) ProtoMessage() {}

func (x *AudioFormat) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFormat.ProtoReflect.Descriptor instead.
func (*AudioFormat) Descriptor() ([]byte, []int) {
	return file_emulator_controller_proto_rawDescGZIP(), []int{0}
}

func (x *AudioFormat) GetSamplingRate() uint64 {
	if x != nil {
		return x.SamplingRate
	}
	return 0
}

func (x *AudioFormat) GetChannels() AudioFormat_Channels {
	if x != nil {
		return x.Channels
	}
	return AudioFormat_Mono
}

func (x *AudioFormat) GetFormat() AudioFormat_SampleFormat {
	if x != nil {
		return x.Format
	}
	return AudioFormat_AUD_FMT_U8
}

type AudioPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        *AudioFormat           `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Audio         []byte                 `protobuf:"bytes,3,opt,name=audio,proto3" json:"audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioPacket) Reset() {
	*x = AudioPacket{}
	mi := &file_emulator_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioPacket) ProtoMessage() {}

func (x *AudioPacket) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioPacket.ProtoReflect.Descriptor instead.
func (*AudioPacket) Descriptor() ([]byte, []int) {
	return file_emulator_controller_proto_rawDescGZIP(), []int{1}
}

func (x *AudioPacket) GetFormat() *AudioFormat {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *AudioPacket) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AudioPacket) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

var File_emulator_controller_proto protoreflect.FileDescriptor

const file_emulator_controller_proto_rawDesc = "" +
	"\n" +
	"\x19emulator_controller.proto\x12\x19android.emulation.control\x1a\x1bgoogle/protobuf/empty.proto\"\x9e\x02\n" +
	"\vAudioFormat\x12\"\n" +
	"\fsamplingRate\x18\x01 \x01(\x04R\fsamplingRate\x12K\n" +
	"\bchannels\x18\x02 \x01(\x0e2/.android.emulation.control.AudioFormat.ChannelsR\bchannels\x12K\n" +
	"\x06format\x18\x03 \x01(\x0e23.android.emulation.control.AudioFormat.SampleFormatR\x06format\"/\n" +
	"\fSampleFormat\x12\x0e\n" +
	"\n" +
	"AUD_FMT_U8\x10\x00\x12\x0f\n" +
	"\vAUD_FMT_S16\x10\x01\" \n" +
	"\bChannels\x12\b\n" +
	"\x04Mono\x10\x00\x12\n" +
	"\n" +
	"\x06Stereo\x10\x01\"\x81\x01\n" +
	"\vAudioPacket\x12>\n" +
	"\x06format\x18\x01 \x01(\v2&.android.emulation.control.AudioFormatR\x06format\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12\x14\n" +
	"\x05audio\x18\x03 \x01(\fR\x05audio2g\n" +
	"\x12EmulatorController\x12Q\n" +
	"\vinjectAudio\x12&.android.emulation.control.AudioPacket\x1a\x16.google.protobuf.Empty\"\x00(\x01B?Z=github.com/AndroidGoLab/ndk/tests/e2e/audio-inject/proto/emupbb\x06proto3"

var (
	file_emulator_controller_proto_rawDescOnce sync.Once
	file_emulator_controller_proto_rawDescData []byte
)

func file_emulator_controller_proto_rawDescGZIP() []byte {
	file_emulator_controller_proto_rawDescOnce.Do(func() {
		file_emulator_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emulator_controller_proto_rawDesc), len(file_emulator_controller_proto_rawDesc)))
	})
	return file_emulator_controller_proto_rawDescData
}

var file_emulator_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_emulator_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_emulator_controller_proto_goTypes = []any{
	(AudioFormat_SampleFormat)(0), // 0: android.emulation.control.AudioFormat.SampleFormat
	(AudioFormat_Channels)(0),     // 1: android.emulation.control.AudioFormat.Channels
	(*AudioFormat)(nil),           // 2: android.emulation.control.AudioFormat
	(*AudioPacket)(nil),           // 3: android.emulation.control.AudioPacket
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_emulator_controller_proto_depIdxs = []int32{
	1, // 0: android.emulation.control.AudioFormat.channels:type_name -> android.emulation.control.AudioFormat.Channels
	0, // 1: android.emulation.control.AudioFormat.format:type_name -> android.emulation.control.AudioFormat.SampleFormat
	2, // 2: android.emulation.control.AudioPacket.format:type_name -> android.emulation.control.AudioFormat
	3, // 3: android.emulation.control.EmulatorController.injectAudio:input_type -> android.emulation.control.AudioPacket
	4, // 4: android.emulation.control.EmulatorController.injectAudio:output_type -> google.protobuf.Empty
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_emulator_controller_proto_init() }
func file_emulator_controller_proto_init() {
	if File_emulator_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emulator_controller_proto_rawDesc), len(file_emulator_controller_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emulator_controller_proto_goTypes,
		DependencyIndexes: file_emulator_controller_proto_depIdxs,
		EnumInfos:         file_emulator_controller_proto_enumTypes,
		MessageInfos:      file_emulator_controller_proto_msgTypes,
	}.Build()
	File_emulator_controller_proto = out.File
	file_emulator_controller_proto_goTypes = nil
	file_emulator_controller_proto_depIdxs = nil
}
