// Code generated by idiomgen. DO NOT EDIT.

package storage

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/storage"
)

// Manager wraps the NDK AStorageManager handle.
type Manager struct {
	ptr *capi.AStorageManager
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *Manager) cptr() *capi.AStorageManager {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewManager creates a new Manager.
func NewManager() *Manager {
	return &Manager{ptr: capi.AStorageManager_new()}
}

// Close releases the underlying NDK handle.
func (h *Manager) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.AStorageManager_delete(h.ptr)
	h.ptr = nil
	return nil
}

// NewManagerFromPointer wraps a raw AStorageManager pointer.
func NewManagerFromPointer(ptr unsafe.Pointer) *Manager {
	return &Manager{ptr: (*capi.AStorageManager)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Manager) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// MountedObbPath returns the value directly.
func (h *Manager) MountedObbPath(filename string) string {
	return (string)(capi.AStorageManager_getMountedObbPath(h.ptr, filename))
}

// IsObbMounted returns the value directly.
func (h *Manager) IsObbMounted(filename string) int32 {
	return (int32)(capi.AStorageManager_isObbMounted(h.ptr, filename))
}

// MountObb calls the underlying NDK function.
func (h *Manager) MountObb(filename string, key string, cb AStorageManager_obbCallbackFunc, data unsafe.Pointer) {
	capi.AStorageManager_mountObb(h.ptr, filename, key, capi.AStorageManager_obbCallbackFunc(cb), data)
}

// UnmountObb calls the underlying NDK function.
func (h *Manager) UnmountObb(filename string, force int32, cb AStorageManager_obbCallbackFunc, data unsafe.Pointer) {
	capi.AStorageManager_unmountObb(h.ptr, filename, force, capi.AStorageManager_obbCallbackFunc(cb), data)
}
