// Code generated by idiomgen. DO NOT EDIT.

package config

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/configuration"
)

// Config wraps the NDK AConfiguration handle.
type Config struct {
	ptr *capi.AConfiguration
}

// NewConfig creates a new Config.
func NewConfig() *Config {
	return &Config{ptr: capi.AConfiguration_new()}
}

// Close releases the underlying NDK handle.
func (h *Config) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.AConfiguration_delete(h.ptr)
	h.ptr = nil
	return nil
}

// NewConfigFromPointer wraps a raw AConfiguration pointer.
func NewConfigFromPointer(ptr unsafe.Pointer) *Config {
	return &Config{ptr: (*capi.AConfiguration)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Config) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// Country calls the underlying NDK function.
func (h *Config) Country(outCountry string) {
	capi.AConfiguration_getCountry(h.ptr, outCountry)
}

// Density returns the value directly.
func (h *Config) Density() int32 {
	return (int32)(capi.AConfiguration_getDensity(h.ptr))
}

// Language calls the underlying NDK function.
func (h *Config) Language(outLanguage string) {
	capi.AConfiguration_getLanguage(h.ptr, outLanguage)
}

// Orientation returns the value directly.
func (h *Config) Orientation() int32 {
	return (int32)(capi.AConfiguration_getOrientation(h.ptr))
}

// ScreenHeightDp returns the value directly.
func (h *Config) ScreenHeightDp() int32 {
	return (int32)(capi.AConfiguration_getScreenHeightDp(h.ptr))
}

// ScreenSize returns the value directly.
func (h *Config) ScreenSize() int32 {
	return (int32)(capi.AConfiguration_getScreenSize(h.ptr))
}

// ScreenWidthDp returns the value directly.
func (h *Config) ScreenWidthDp() int32 {
	return (int32)(capi.AConfiguration_getScreenWidthDp(h.ptr))
}

// SdkVersion returns the value directly.
func (h *Config) SdkVersion() int32 {
	return (int32)(capi.AConfiguration_getSdkVersion(h.ptr))
}
