// Code generated by capigen. DO NOT EDIT.

package binder

/*
#cgo LDFLAGS: -lbinder_ndk
#include "android/binder_ibinder.h"
#include "android/binder_parcel.h"
#include "android/binder_status.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"sync"
	"unsafe"
)

// CgoAllocMap stores pointers to C allocated memory for future reference.
type CgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(CgoAllocMap)

func (a *CgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *CgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *CgoAllocMap) Borrow(b *CgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *CgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

type SliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

func (x AIBinder_Class_onCreate) PassRef() (ref *C.AIBinder_Class_onCreate, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aIBinder_Class_onCreateAE3E288CFunc == nil {
		aIBinder_Class_onCreateAE3E288CFunc = x
	}
	return (*C.AIBinder_Class_onCreate)(C.AIBinder_Class_onCreate_ae3e288c), nil
}

func (x AIBinder_Class_onCreate) PassValue() (ref C.AIBinder_Class_onCreate, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aIBinder_Class_onCreateAE3E288CFunc == nil {
		aIBinder_Class_onCreateAE3E288CFunc = x
	}
	return (C.AIBinder_Class_onCreate)(C.AIBinder_Class_onCreate_ae3e288c), nil
}

func NewAIBinder_Class_onCreateRef(ref unsafe.Pointer) *AIBinder_Class_onCreate {
	return (*AIBinder_Class_onCreate)(ref)
}

//export AIBinder_Class_onCreateAE3E288C
func AIBinder_Class_onCreateAE3E288C(cargs unsafe.Pointer) unsafe.Pointer {
	if aIBinder_Class_onCreateAE3E288CFunc != nil {
		argsae3e288c := (unsafe.Pointer)(unsafe.Pointer(cargs))
		retae3e288c := aIBinder_Class_onCreateAE3E288CFunc(argsae3e288c)
		ret, _ := (unsafe.Pointer)(retae3e288c), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aIBinder_Class_onCreateAE3E288CFunc AIBinder_Class_onCreate

func (x AIBinder_Class_onDestroy) PassRef() (ref *C.AIBinder_Class_onDestroy, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aIBinder_Class_onDestroy2C719D10Func == nil {
		aIBinder_Class_onDestroy2C719D10Func = x
	}
	return (*C.AIBinder_Class_onDestroy)(C.AIBinder_Class_onDestroy_2c719d10), nil
}

func (x AIBinder_Class_onDestroy) PassValue() (ref C.AIBinder_Class_onDestroy, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aIBinder_Class_onDestroy2C719D10Func == nil {
		aIBinder_Class_onDestroy2C719D10Func = x
	}
	return (C.AIBinder_Class_onDestroy)(C.AIBinder_Class_onDestroy_2c719d10), nil
}

func NewAIBinder_Class_onDestroyRef(ref unsafe.Pointer) *AIBinder_Class_onDestroy {
	return (*AIBinder_Class_onDestroy)(ref)
}

//export AIBinder_Class_onDestroy2C719D10
func AIBinder_Class_onDestroy2C719D10(cuserData unsafe.Pointer) {
	if aIBinder_Class_onDestroy2C719D10Func != nil {
		userData2c719d10 := (unsafe.Pointer)(unsafe.Pointer(cuserData))
		aIBinder_Class_onDestroy2C719D10Func(userData2c719d10)
		return
	}
	panic("callback func has not been set (race?)")
}

var aIBinder_Class_onDestroy2C719D10Func AIBinder_Class_onDestroy

func (x AIBinder_Class_onTransact) PassRef() (ref *C.AIBinder_Class_onTransact, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aIBinder_Class_onTransact4C5B3F35Func == nil {
		aIBinder_Class_onTransact4C5B3F35Func = x
	}
	return (*C.AIBinder_Class_onTransact)(C.AIBinder_Class_onTransact_4c5b3f35), nil
}

func (x AIBinder_Class_onTransact) PassValue() (ref C.AIBinder_Class_onTransact, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aIBinder_Class_onTransact4C5B3F35Func == nil {
		aIBinder_Class_onTransact4C5B3F35Func = x
	}
	return (C.AIBinder_Class_onTransact)(C.AIBinder_Class_onTransact_4c5b3f35), nil
}

func NewAIBinder_Class_onTransactRef(ref unsafe.Pointer) *AIBinder_Class_onTransact {
	return (*AIBinder_Class_onTransact)(ref)
}

//export AIBinder_Class_onTransact4C5B3F35
func AIBinder_Class_onTransact4C5B3F35(cbinder *C.AIBinder, ccode C.transaction_code_t, cin *C.AParcel, cout *C.AParcel) C.binder_status_t {
	if aIBinder_Class_onTransact4C5B3F35Func != nil {
		binder4c5b3f35 := (*AIBinder)(unsafe.Pointer(cbinder))
		code4c5b3f35 := (Transaction_code_t)(ccode)
		in4c5b3f35 := (*AParcel)(unsafe.Pointer(cin))
		out4c5b3f35 := (*AParcel)(unsafe.Pointer(cout))
		ret4c5b3f35 := aIBinder_Class_onTransact4C5B3F35Func(binder4c5b3f35, code4c5b3f35, in4c5b3f35, out4c5b3f35)
		ret, _ := (C.binder_status_t)(ret4c5b3f35), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aIBinder_Class_onTransact4C5B3F35Func AIBinder_Class_onTransact

func (x AIBinder_DeathRecipient_onBinderDied) PassRef() (ref *C.AIBinder_DeathRecipient_onBinderDied, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aIBinder_DeathRecipient_onBinderDied7D6F4F1BFunc == nil {
		aIBinder_DeathRecipient_onBinderDied7D6F4F1BFunc = x
	}
	return (*C.AIBinder_DeathRecipient_onBinderDied)(C.AIBinder_DeathRecipient_onBinderDied_7d6f4f1b), nil
}

func (x AIBinder_DeathRecipient_onBinderDied) PassValue() (ref C.AIBinder_DeathRecipient_onBinderDied, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aIBinder_DeathRecipient_onBinderDied7D6F4F1BFunc == nil {
		aIBinder_DeathRecipient_onBinderDied7D6F4F1BFunc = x
	}
	return (C.AIBinder_DeathRecipient_onBinderDied)(C.AIBinder_DeathRecipient_onBinderDied_7d6f4f1b), nil
}

func NewAIBinder_DeathRecipient_onBinderDiedRef(ref unsafe.Pointer) *AIBinder_DeathRecipient_onBinderDied {
	return (*AIBinder_DeathRecipient_onBinderDied)(ref)
}

//export AIBinder_DeathRecipient_onBinderDied7D6F4F1B
func AIBinder_DeathRecipient_onBinderDied7D6F4F1B() {
	if aIBinder_DeathRecipient_onBinderDied7D6F4F1BFunc != nil {
		aIBinder_DeathRecipient_onBinderDied7D6F4F1BFunc()
		return
	}
	panic("callback func has not been set (race?)")
}

var aIBinder_DeathRecipient_onBinderDied7D6F4F1BFunc AIBinder_DeathRecipient_onBinderDied

func (x AIBinder_DeathRecipient_onBinderUnlinked) PassRef() (ref *C.AIBinder_DeathRecipient_onBinderUnlinked, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aIBinder_DeathRecipient_onBinderUnlinked6D499F91Func == nil {
		aIBinder_DeathRecipient_onBinderUnlinked6D499F91Func = x
	}
	return (*C.AIBinder_DeathRecipient_onBinderUnlinked)(C.AIBinder_DeathRecipient_onBinderUnlinked_6d499f91), nil
}

func (x AIBinder_DeathRecipient_onBinderUnlinked) PassValue() (ref C.AIBinder_DeathRecipient_onBinderUnlinked, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aIBinder_DeathRecipient_onBinderUnlinked6D499F91Func == nil {
		aIBinder_DeathRecipient_onBinderUnlinked6D499F91Func = x
	}
	return (C.AIBinder_DeathRecipient_onBinderUnlinked)(C.AIBinder_DeathRecipient_onBinderUnlinked_6d499f91), nil
}

func NewAIBinder_DeathRecipient_onBinderUnlinkedRef(ref unsafe.Pointer) *AIBinder_DeathRecipient_onBinderUnlinked {
	return (*AIBinder_DeathRecipient_onBinderUnlinked)(ref)
}

//export AIBinder_DeathRecipient_onBinderUnlinked6D499F91
func AIBinder_DeathRecipient_onBinderUnlinked6D499F91() {
	if aIBinder_DeathRecipient_onBinderUnlinked6D499F91Func != nil {
		aIBinder_DeathRecipient_onBinderUnlinked6D499F91Func()
		return
	}
	panic("callback func has not been set (race?)")
}

var aIBinder_DeathRecipient_onBinderUnlinked6D499F91Func AIBinder_DeathRecipient_onBinderUnlinked

func (x AIBinder_onDump) PassRef() (ref *C.AIBinder_onDump, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aIBinder_onDump04709357Func == nil {
		aIBinder_onDump04709357Func = x
	}
	return (*C.AIBinder_onDump)(C.AIBinder_onDump_04709357), nil
}

func (x AIBinder_onDump) PassValue() (ref C.AIBinder_onDump, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aIBinder_onDump04709357Func == nil {
		aIBinder_onDump04709357Func = x
	}
	return (C.AIBinder_onDump)(C.AIBinder_onDump_04709357), nil
}

func NewAIBinder_onDumpRef(ref unsafe.Pointer) *AIBinder_onDump {
	return (*AIBinder_onDump)(ref)
}

//export AIBinder_onDump04709357
func AIBinder_onDump04709357(cbinder *C.AIBinder, cfd C.int, cargs **C.int8_t, cnumArgs C.uint) C.binder_status_t {
	if aIBinder_onDump04709357Func != nil {
		binder04709357 := (*AIBinder)(unsafe.Pointer(cbinder))
		fd04709357 := (int32)(cfd)
		args04709357 := (**int8)(unsafe.Pointer(cargs))
		numArgs04709357 := (uint32)(cnumArgs)
		ret04709357 := aIBinder_onDump04709357Func(binder04709357, fd04709357, args04709357, numArgs04709357)
		ret, _ := (C.binder_status_t)(ret04709357), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aIBinder_onDump04709357Func AIBinder_onDump

func (x AParcel_boolArrayAllocator) PassRef() (ref *C.AParcel_boolArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_boolArrayAllocator6CE04D29Func == nil {
		aParcel_boolArrayAllocator6CE04D29Func = x
	}
	return (*C.AParcel_boolArrayAllocator)(C.AParcel_boolArrayAllocator_6ce04d29), nil
}

func (x AParcel_boolArrayAllocator) PassValue() (ref C.AParcel_boolArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_boolArrayAllocator6CE04D29Func == nil {
		aParcel_boolArrayAllocator6CE04D29Func = x
	}
	return (C.AParcel_boolArrayAllocator)(C.AParcel_boolArrayAllocator_6ce04d29), nil
}

func NewAParcel_boolArrayAllocatorRef(ref unsafe.Pointer) *AParcel_boolArrayAllocator {
	return (*AParcel_boolArrayAllocator)(ref)
}

//export AParcel_boolArrayAllocator6CE04D29
func AParcel_boolArrayAllocator6CE04D29(carrayData unsafe.Pointer, clength C.int) C._Bool {
	if aParcel_boolArrayAllocator6CE04D29Func != nil {
		arrayData6ce04d29 := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		length6ce04d29 := (int32)(clength)
		ret6ce04d29 := aParcel_boolArrayAllocator6CE04D29Func(arrayData6ce04d29, length6ce04d29)
		ret, _ := (C._Bool)(ret6ce04d29), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_boolArrayAllocator6CE04D29Func AParcel_boolArrayAllocator

func (x AParcel_boolArrayGetter) PassRef() (ref *C.AParcel_boolArrayGetter, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_boolArrayGetter58F10D8EFunc == nil {
		aParcel_boolArrayGetter58F10D8EFunc = x
	}
	return (*C.AParcel_boolArrayGetter)(C.AParcel_boolArrayGetter_58f10d8e), nil
}

func (x AParcel_boolArrayGetter) PassValue() (ref C.AParcel_boolArrayGetter, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_boolArrayGetter58F10D8EFunc == nil {
		aParcel_boolArrayGetter58F10D8EFunc = x
	}
	return (C.AParcel_boolArrayGetter)(C.AParcel_boolArrayGetter_58f10d8e), nil
}

func NewAParcel_boolArrayGetterRef(ref unsafe.Pointer) *AParcel_boolArrayGetter {
	return (*AParcel_boolArrayGetter)(ref)
}

//export AParcel_boolArrayGetter58F10D8E
func AParcel_boolArrayGetter58F10D8E(carrayData unsafe.Pointer, cindex C.uint64_t) C._Bool {
	if aParcel_boolArrayGetter58F10D8EFunc != nil {
		arrayData58f10d8e := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		index58f10d8e := (uint64)(cindex)
		ret58f10d8e := aParcel_boolArrayGetter58F10D8EFunc(arrayData58f10d8e, index58f10d8e)
		ret, _ := (C._Bool)(ret58f10d8e), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_boolArrayGetter58F10D8EFunc AParcel_boolArrayGetter

func (x AParcel_boolArraySetter) PassRef() (ref *C.AParcel_boolArraySetter, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_boolArraySetterC31D06A6Func == nil {
		aParcel_boolArraySetterC31D06A6Func = x
	}
	return (*C.AParcel_boolArraySetter)(C.AParcel_boolArraySetter_c31d06a6), nil
}

func (x AParcel_boolArraySetter) PassValue() (ref C.AParcel_boolArraySetter, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_boolArraySetterC31D06A6Func == nil {
		aParcel_boolArraySetterC31D06A6Func = x
	}
	return (C.AParcel_boolArraySetter)(C.AParcel_boolArraySetter_c31d06a6), nil
}

func NewAParcel_boolArraySetterRef(ref unsafe.Pointer) *AParcel_boolArraySetter {
	return (*AParcel_boolArraySetter)(ref)
}

//export AParcel_boolArraySetterC31D06A6
func AParcel_boolArraySetterC31D06A6(carrayData unsafe.Pointer, cindex C.uint64_t, cvalue C._Bool) {
	if aParcel_boolArraySetterC31D06A6Func != nil {
		arrayDatac31d06a6 := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		indexc31d06a6 := (uint64)(cindex)
		valuec31d06a6 := (bool)(cvalue)
		aParcel_boolArraySetterC31D06A6Func(arrayDatac31d06a6, indexc31d06a6, valuec31d06a6)
		return
	}
	panic("callback func has not been set (race?)")
}

var aParcel_boolArraySetterC31D06A6Func AParcel_boolArraySetter

func (x AParcel_byteArrayAllocator) PassRef() (ref *C.AParcel_byteArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_byteArrayAllocator0F5D9BCBFunc == nil {
		aParcel_byteArrayAllocator0F5D9BCBFunc = x
	}
	return (*C.AParcel_byteArrayAllocator)(C.AParcel_byteArrayAllocator_0f5d9bcb), nil
}

func (x AParcel_byteArrayAllocator) PassValue() (ref C.AParcel_byteArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_byteArrayAllocator0F5D9BCBFunc == nil {
		aParcel_byteArrayAllocator0F5D9BCBFunc = x
	}
	return (C.AParcel_byteArrayAllocator)(C.AParcel_byteArrayAllocator_0f5d9bcb), nil
}

func NewAParcel_byteArrayAllocatorRef(ref unsafe.Pointer) *AParcel_byteArrayAllocator {
	return (*AParcel_byteArrayAllocator)(ref)
}

//export AParcel_byteArrayAllocator0F5D9BCB
func AParcel_byteArrayAllocator0F5D9BCB(carrayData unsafe.Pointer, clength C.int, coutBuffer **C.int8_t) C._Bool {
	if aParcel_byteArrayAllocator0F5D9BCBFunc != nil {
		arrayData0f5d9bcb := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		length0f5d9bcb := (int32)(clength)
		outBuffer0f5d9bcb := (**int8)(unsafe.Pointer(coutBuffer))
		ret0f5d9bcb := aParcel_byteArrayAllocator0F5D9BCBFunc(arrayData0f5d9bcb, length0f5d9bcb, outBuffer0f5d9bcb)
		ret, _ := (C._Bool)(ret0f5d9bcb), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_byteArrayAllocator0F5D9BCBFunc AParcel_byteArrayAllocator

func (x AParcel_charArrayAllocator) PassRef() (ref *C.AParcel_charArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_charArrayAllocatorE28A23C0Func == nil {
		aParcel_charArrayAllocatorE28A23C0Func = x
	}
	return (*C.AParcel_charArrayAllocator)(C.AParcel_charArrayAllocator_e28a23c0), nil
}

func (x AParcel_charArrayAllocator) PassValue() (ref C.AParcel_charArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_charArrayAllocatorE28A23C0Func == nil {
		aParcel_charArrayAllocatorE28A23C0Func = x
	}
	return (C.AParcel_charArrayAllocator)(C.AParcel_charArrayAllocator_e28a23c0), nil
}

func NewAParcel_charArrayAllocatorRef(ref unsafe.Pointer) *AParcel_charArrayAllocator {
	return (*AParcel_charArrayAllocator)(ref)
}

//export AParcel_charArrayAllocatorE28A23C0
func AParcel_charArrayAllocatorE28A23C0(carrayData unsafe.Pointer, clength C.int, coutBuffer **C.char16_t) C._Bool {
	if aParcel_charArrayAllocatorE28A23C0Func != nil {
		arrayDatae28a23c0 := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		lengthe28a23c0 := (int32)(clength)
		outBuffere28a23c0 := (**Char16_t)(unsafe.Pointer(coutBuffer))
		rete28a23c0 := aParcel_charArrayAllocatorE28A23C0Func(arrayDatae28a23c0, lengthe28a23c0, outBuffere28a23c0)
		ret, _ := (C._Bool)(rete28a23c0), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_charArrayAllocatorE28A23C0Func AParcel_charArrayAllocator

func (x AParcel_doubleArrayAllocator) PassRef() (ref *C.AParcel_doubleArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_doubleArrayAllocator0D8E072DFunc == nil {
		aParcel_doubleArrayAllocator0D8E072DFunc = x
	}
	return (*C.AParcel_doubleArrayAllocator)(C.AParcel_doubleArrayAllocator_0d8e072d), nil
}

func (x AParcel_doubleArrayAllocator) PassValue() (ref C.AParcel_doubleArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_doubleArrayAllocator0D8E072DFunc == nil {
		aParcel_doubleArrayAllocator0D8E072DFunc = x
	}
	return (C.AParcel_doubleArrayAllocator)(C.AParcel_doubleArrayAllocator_0d8e072d), nil
}

func NewAParcel_doubleArrayAllocatorRef(ref unsafe.Pointer) *AParcel_doubleArrayAllocator {
	return (*AParcel_doubleArrayAllocator)(ref)
}

//export AParcel_doubleArrayAllocator0D8E072D
func AParcel_doubleArrayAllocator0D8E072D(carrayData unsafe.Pointer, clength C.int, coutBuffer **C.double) C._Bool {
	if aParcel_doubleArrayAllocator0D8E072DFunc != nil {
		arrayData0d8e072d := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		length0d8e072d := (int32)(clength)
		outBuffer0d8e072d := (**float64)(unsafe.Pointer(coutBuffer))
		ret0d8e072d := aParcel_doubleArrayAllocator0D8E072DFunc(arrayData0d8e072d, length0d8e072d, outBuffer0d8e072d)
		ret, _ := (C._Bool)(ret0d8e072d), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_doubleArrayAllocator0D8E072DFunc AParcel_doubleArrayAllocator

func (x AParcel_floatArrayAllocator) PassRef() (ref *C.AParcel_floatArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_floatArrayAllocatorDDD314B6Func == nil {
		aParcel_floatArrayAllocatorDDD314B6Func = x
	}
	return (*C.AParcel_floatArrayAllocator)(C.AParcel_floatArrayAllocator_ddd314b6), nil
}

func (x AParcel_floatArrayAllocator) PassValue() (ref C.AParcel_floatArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_floatArrayAllocatorDDD314B6Func == nil {
		aParcel_floatArrayAllocatorDDD314B6Func = x
	}
	return (C.AParcel_floatArrayAllocator)(C.AParcel_floatArrayAllocator_ddd314b6), nil
}

func NewAParcel_floatArrayAllocatorRef(ref unsafe.Pointer) *AParcel_floatArrayAllocator {
	return (*AParcel_floatArrayAllocator)(ref)
}

//export AParcel_floatArrayAllocatorDDD314B6
func AParcel_floatArrayAllocatorDDD314B6(carrayData unsafe.Pointer, clength C.int, coutBuffer **C.float) C._Bool {
	if aParcel_floatArrayAllocatorDDD314B6Func != nil {
		arrayDataddd314b6 := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		lengthddd314b6 := (int32)(clength)
		outBufferddd314b6 := (**float32)(unsafe.Pointer(coutBuffer))
		retddd314b6 := aParcel_floatArrayAllocatorDDD314B6Func(arrayDataddd314b6, lengthddd314b6, outBufferddd314b6)
		ret, _ := (C._Bool)(retddd314b6), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_floatArrayAllocatorDDD314B6Func AParcel_floatArrayAllocator

func (x AParcel_int32ArrayAllocator) PassRef() (ref *C.AParcel_int32ArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_int32ArrayAllocator632DB075Func == nil {
		aParcel_int32ArrayAllocator632DB075Func = x
	}
	return (*C.AParcel_int32ArrayAllocator)(C.AParcel_int32ArrayAllocator_632db075), nil
}

func (x AParcel_int32ArrayAllocator) PassValue() (ref C.AParcel_int32ArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_int32ArrayAllocator632DB075Func == nil {
		aParcel_int32ArrayAllocator632DB075Func = x
	}
	return (C.AParcel_int32ArrayAllocator)(C.AParcel_int32ArrayAllocator_632db075), nil
}

func NewAParcel_int32ArrayAllocatorRef(ref unsafe.Pointer) *AParcel_int32ArrayAllocator {
	return (*AParcel_int32ArrayAllocator)(ref)
}

//export AParcel_int32ArrayAllocator632DB075
func AParcel_int32ArrayAllocator632DB075(carrayData unsafe.Pointer, clength C.int, coutBuffer **C.int) C._Bool {
	if aParcel_int32ArrayAllocator632DB075Func != nil {
		arrayData632db075 := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		length632db075 := (int32)(clength)
		outBuffer632db075 := (**int32)(unsafe.Pointer(coutBuffer))
		ret632db075 := aParcel_int32ArrayAllocator632DB075Func(arrayData632db075, length632db075, outBuffer632db075)
		ret, _ := (C._Bool)(ret632db075), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_int32ArrayAllocator632DB075Func AParcel_int32ArrayAllocator

func (x AParcel_int64ArrayAllocator) PassRef() (ref *C.AParcel_int64ArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_int64ArrayAllocatorE9CCD3BDFunc == nil {
		aParcel_int64ArrayAllocatorE9CCD3BDFunc = x
	}
	return (*C.AParcel_int64ArrayAllocator)(C.AParcel_int64ArrayAllocator_e9ccd3bd), nil
}

func (x AParcel_int64ArrayAllocator) PassValue() (ref C.AParcel_int64ArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_int64ArrayAllocatorE9CCD3BDFunc == nil {
		aParcel_int64ArrayAllocatorE9CCD3BDFunc = x
	}
	return (C.AParcel_int64ArrayAllocator)(C.AParcel_int64ArrayAllocator_e9ccd3bd), nil
}

func NewAParcel_int64ArrayAllocatorRef(ref unsafe.Pointer) *AParcel_int64ArrayAllocator {
	return (*AParcel_int64ArrayAllocator)(ref)
}

//export AParcel_int64ArrayAllocatorE9CCD3BD
func AParcel_int64ArrayAllocatorE9CCD3BD(carrayData unsafe.Pointer, clength C.int, coutBuffer **C.int64_t) C._Bool {
	if aParcel_int64ArrayAllocatorE9CCD3BDFunc != nil {
		arrayDatae9ccd3bd := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		lengthe9ccd3bd := (int32)(clength)
		outBuffere9ccd3bd := (**int64)(unsafe.Pointer(coutBuffer))
		rete9ccd3bd := aParcel_int64ArrayAllocatorE9CCD3BDFunc(arrayDatae9ccd3bd, lengthe9ccd3bd, outBuffere9ccd3bd)
		ret, _ := (C._Bool)(rete9ccd3bd), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_int64ArrayAllocatorE9CCD3BDFunc AParcel_int64ArrayAllocator

func (x AParcel_parcelableArrayAllocator) PassRef() (ref *C.AParcel_parcelableArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_parcelableArrayAllocator6A96D230Func == nil {
		aParcel_parcelableArrayAllocator6A96D230Func = x
	}
	return (*C.AParcel_parcelableArrayAllocator)(C.AParcel_parcelableArrayAllocator_6a96d230), nil
}

func (x AParcel_parcelableArrayAllocator) PassValue() (ref C.AParcel_parcelableArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_parcelableArrayAllocator6A96D230Func == nil {
		aParcel_parcelableArrayAllocator6A96D230Func = x
	}
	return (C.AParcel_parcelableArrayAllocator)(C.AParcel_parcelableArrayAllocator_6a96d230), nil
}

func NewAParcel_parcelableArrayAllocatorRef(ref unsafe.Pointer) *AParcel_parcelableArrayAllocator {
	return (*AParcel_parcelableArrayAllocator)(ref)
}

//export AParcel_parcelableArrayAllocator6A96D230
func AParcel_parcelableArrayAllocator6A96D230(carrayData unsafe.Pointer, clength C.int) C._Bool {
	if aParcel_parcelableArrayAllocator6A96D230Func != nil {
		arrayData6a96d230 := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		length6a96d230 := (int32)(clength)
		ret6a96d230 := aParcel_parcelableArrayAllocator6A96D230Func(arrayData6a96d230, length6a96d230)
		ret, _ := (C._Bool)(ret6a96d230), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_parcelableArrayAllocator6A96D230Func AParcel_parcelableArrayAllocator

func (x AParcel_readParcelableElement) PassRef() (ref *C.AParcel_readParcelableElement, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_readParcelableElementF5964747Func == nil {
		aParcel_readParcelableElementF5964747Func = x
	}
	return (*C.AParcel_readParcelableElement)(C.AParcel_readParcelableElement_f5964747), nil
}

func (x AParcel_readParcelableElement) PassValue() (ref C.AParcel_readParcelableElement, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_readParcelableElementF5964747Func == nil {
		aParcel_readParcelableElementF5964747Func = x
	}
	return (C.AParcel_readParcelableElement)(C.AParcel_readParcelableElement_f5964747), nil
}

func NewAParcel_readParcelableElementRef(ref unsafe.Pointer) *AParcel_readParcelableElement {
	return (*AParcel_readParcelableElement)(ref)
}

//export AParcel_readParcelableElementF5964747
func AParcel_readParcelableElementF5964747(cparcel *C.AParcel, carrayData unsafe.Pointer, cindex C.uint64_t) C.binder_status_t {
	if aParcel_readParcelableElementF5964747Func != nil {
		parcelf5964747 := (*AParcel)(unsafe.Pointer(cparcel))
		arrayDataf5964747 := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		indexf5964747 := (uint64)(cindex)
		retf5964747 := aParcel_readParcelableElementF5964747Func(parcelf5964747, arrayDataf5964747, indexf5964747)
		ret, _ := (C.binder_status_t)(retf5964747), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_readParcelableElementF5964747Func AParcel_readParcelableElement

func (x AParcel_stringAllocator) PassRef() (ref *C.AParcel_stringAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_stringAllocatorFED8100AFunc == nil {
		aParcel_stringAllocatorFED8100AFunc = x
	}
	return (*C.AParcel_stringAllocator)(C.AParcel_stringAllocator_fed8100a), nil
}

func (x AParcel_stringAllocator) PassValue() (ref C.AParcel_stringAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_stringAllocatorFED8100AFunc == nil {
		aParcel_stringAllocatorFED8100AFunc = x
	}
	return (C.AParcel_stringAllocator)(C.AParcel_stringAllocator_fed8100a), nil
}

func NewAParcel_stringAllocatorRef(ref unsafe.Pointer) *AParcel_stringAllocator {
	return (*AParcel_stringAllocator)(ref)
}

//export AParcel_stringAllocatorFED8100A
func AParcel_stringAllocatorFED8100A(cstringData unsafe.Pointer, clength C.int, cbuffer **C.int8_t) C._Bool {
	if aParcel_stringAllocatorFED8100AFunc != nil {
		stringDatafed8100a := (unsafe.Pointer)(unsafe.Pointer(cstringData))
		lengthfed8100a := (int32)(clength)
		bufferfed8100a := (**int8)(unsafe.Pointer(cbuffer))
		retfed8100a := aParcel_stringAllocatorFED8100AFunc(stringDatafed8100a, lengthfed8100a, bufferfed8100a)
		ret, _ := (C._Bool)(retfed8100a), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_stringAllocatorFED8100AFunc AParcel_stringAllocator

func (x AParcel_stringArrayAllocator) PassRef() (ref *C.AParcel_stringArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_stringArrayAllocatorA431F501Func == nil {
		aParcel_stringArrayAllocatorA431F501Func = x
	}
	return (*C.AParcel_stringArrayAllocator)(C.AParcel_stringArrayAllocator_a431f501), nil
}

func (x AParcel_stringArrayAllocator) PassValue() (ref C.AParcel_stringArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_stringArrayAllocatorA431F501Func == nil {
		aParcel_stringArrayAllocatorA431F501Func = x
	}
	return (C.AParcel_stringArrayAllocator)(C.AParcel_stringArrayAllocator_a431f501), nil
}

func NewAParcel_stringArrayAllocatorRef(ref unsafe.Pointer) *AParcel_stringArrayAllocator {
	return (*AParcel_stringArrayAllocator)(ref)
}

//export AParcel_stringArrayAllocatorA431F501
func AParcel_stringArrayAllocatorA431F501(carrayData unsafe.Pointer, clength C.int) C._Bool {
	if aParcel_stringArrayAllocatorA431F501Func != nil {
		arrayDataa431f501 := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		lengtha431f501 := (int32)(clength)
		reta431f501 := aParcel_stringArrayAllocatorA431F501Func(arrayDataa431f501, lengtha431f501)
		ret, _ := (C._Bool)(reta431f501), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_stringArrayAllocatorA431F501Func AParcel_stringArrayAllocator

func (x AParcel_stringArrayElementAllocator) PassRef() (ref *C.AParcel_stringArrayElementAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_stringArrayElementAllocator9AC166CAFunc == nil {
		aParcel_stringArrayElementAllocator9AC166CAFunc = x
	}
	return (*C.AParcel_stringArrayElementAllocator)(C.AParcel_stringArrayElementAllocator_9ac166ca), nil
}

func (x AParcel_stringArrayElementAllocator) PassValue() (ref C.AParcel_stringArrayElementAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_stringArrayElementAllocator9AC166CAFunc == nil {
		aParcel_stringArrayElementAllocator9AC166CAFunc = x
	}
	return (C.AParcel_stringArrayElementAllocator)(C.AParcel_stringArrayElementAllocator_9ac166ca), nil
}

func NewAParcel_stringArrayElementAllocatorRef(ref unsafe.Pointer) *AParcel_stringArrayElementAllocator {
	return (*AParcel_stringArrayElementAllocator)(ref)
}

//export AParcel_stringArrayElementAllocator9AC166CA
func AParcel_stringArrayElementAllocator9AC166CA(carrayData unsafe.Pointer, cindex C.uint64_t, clength C.int, cbuffer **C.int8_t) C._Bool {
	if aParcel_stringArrayElementAllocator9AC166CAFunc != nil {
		arrayData9ac166ca := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		index9ac166ca := (uint64)(cindex)
		length9ac166ca := (int32)(clength)
		buffer9ac166ca := (**int8)(unsafe.Pointer(cbuffer))
		ret9ac166ca := aParcel_stringArrayElementAllocator9AC166CAFunc(arrayData9ac166ca, index9ac166ca, length9ac166ca, buffer9ac166ca)
		ret, _ := (C._Bool)(ret9ac166ca), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_stringArrayElementAllocator9AC166CAFunc AParcel_stringArrayElementAllocator

func (x AParcel_stringArrayElementGetter) PassRef() (ref *C.AParcel_stringArrayElementGetter, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_stringArrayElementGetter6817B794Func == nil {
		aParcel_stringArrayElementGetter6817B794Func = x
	}
	return (*C.AParcel_stringArrayElementGetter)(C.AParcel_stringArrayElementGetter_6817b794), nil
}

func (x AParcel_stringArrayElementGetter) PassValue() (ref C.AParcel_stringArrayElementGetter, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_stringArrayElementGetter6817B794Func == nil {
		aParcel_stringArrayElementGetter6817B794Func = x
	}
	return (C.AParcel_stringArrayElementGetter)(C.AParcel_stringArrayElementGetter_6817b794), nil
}

func NewAParcel_stringArrayElementGetterRef(ref unsafe.Pointer) *AParcel_stringArrayElementGetter {
	return (*AParcel_stringArrayElementGetter)(ref)
}

//export AParcel_stringArrayElementGetter6817B794
func AParcel_stringArrayElementGetter6817B794(carrayData unsafe.Pointer, cindex C.uint64_t, coutLength *C.int) *C.int8_t {
	if aParcel_stringArrayElementGetter6817B794Func != nil {
		arrayData6817b794 := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		index6817b794 := (uint64)(cindex)
		outLength6817b794 := (*int32)(unsafe.Pointer(coutLength))
		ret6817b794 := aParcel_stringArrayElementGetter6817B794Func(arrayData6817b794, index6817b794, outLength6817b794)
		ret, _ := (*C.int8_t)(ret6817b794), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_stringArrayElementGetter6817B794Func AParcel_stringArrayElementGetter

func (x AParcel_uint32ArrayAllocator) PassRef() (ref *C.AParcel_uint32ArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_uint32ArrayAllocatorDFFAD45CFunc == nil {
		aParcel_uint32ArrayAllocatorDFFAD45CFunc = x
	}
	return (*C.AParcel_uint32ArrayAllocator)(C.AParcel_uint32ArrayAllocator_dffad45c), nil
}

func (x AParcel_uint32ArrayAllocator) PassValue() (ref C.AParcel_uint32ArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_uint32ArrayAllocatorDFFAD45CFunc == nil {
		aParcel_uint32ArrayAllocatorDFFAD45CFunc = x
	}
	return (C.AParcel_uint32ArrayAllocator)(C.AParcel_uint32ArrayAllocator_dffad45c), nil
}

func NewAParcel_uint32ArrayAllocatorRef(ref unsafe.Pointer) *AParcel_uint32ArrayAllocator {
	return (*AParcel_uint32ArrayAllocator)(ref)
}

//export AParcel_uint32ArrayAllocatorDFFAD45C
func AParcel_uint32ArrayAllocatorDFFAD45C(carrayData unsafe.Pointer, clength C.int, coutBuffer **C.uint) C._Bool {
	if aParcel_uint32ArrayAllocatorDFFAD45CFunc != nil {
		arrayDatadffad45c := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		lengthdffad45c := (int32)(clength)
		outBufferdffad45c := (**uint32)(unsafe.Pointer(coutBuffer))
		retdffad45c := aParcel_uint32ArrayAllocatorDFFAD45CFunc(arrayDatadffad45c, lengthdffad45c, outBufferdffad45c)
		ret, _ := (C._Bool)(retdffad45c), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_uint32ArrayAllocatorDFFAD45CFunc AParcel_uint32ArrayAllocator

func (x AParcel_uint64ArrayAllocator) PassRef() (ref *C.AParcel_uint64ArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_uint64ArrayAllocatorCF52B274Func == nil {
		aParcel_uint64ArrayAllocatorCF52B274Func = x
	}
	return (*C.AParcel_uint64ArrayAllocator)(C.AParcel_uint64ArrayAllocator_cf52b274), nil
}

func (x AParcel_uint64ArrayAllocator) PassValue() (ref C.AParcel_uint64ArrayAllocator, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_uint64ArrayAllocatorCF52B274Func == nil {
		aParcel_uint64ArrayAllocatorCF52B274Func = x
	}
	return (C.AParcel_uint64ArrayAllocator)(C.AParcel_uint64ArrayAllocator_cf52b274), nil
}

func NewAParcel_uint64ArrayAllocatorRef(ref unsafe.Pointer) *AParcel_uint64ArrayAllocator {
	return (*AParcel_uint64ArrayAllocator)(ref)
}

//export AParcel_uint64ArrayAllocatorCF52B274
func AParcel_uint64ArrayAllocatorCF52B274(carrayData unsafe.Pointer, clength C.int, coutBuffer **C.uint64_t) C._Bool {
	if aParcel_uint64ArrayAllocatorCF52B274Func != nil {
		arrayDatacf52b274 := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		lengthcf52b274 := (int32)(clength)
		outBuffercf52b274 := (**uint64)(unsafe.Pointer(coutBuffer))
		retcf52b274 := aParcel_uint64ArrayAllocatorCF52B274Func(arrayDatacf52b274, lengthcf52b274, outBuffercf52b274)
		ret, _ := (C._Bool)(retcf52b274), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_uint64ArrayAllocatorCF52B274Func AParcel_uint64ArrayAllocator

func (x AParcel_writeParcelableElement) PassRef() (ref *C.AParcel_writeParcelableElement, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_writeParcelableElement73CCA07CFunc == nil {
		aParcel_writeParcelableElement73CCA07CFunc = x
	}
	return (*C.AParcel_writeParcelableElement)(C.AParcel_writeParcelableElement_73cca07c), nil
}

func (x AParcel_writeParcelableElement) PassValue() (ref C.AParcel_writeParcelableElement, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aParcel_writeParcelableElement73CCA07CFunc == nil {
		aParcel_writeParcelableElement73CCA07CFunc = x
	}
	return (C.AParcel_writeParcelableElement)(C.AParcel_writeParcelableElement_73cca07c), nil
}

func NewAParcel_writeParcelableElementRef(ref unsafe.Pointer) *AParcel_writeParcelableElement {
	return (*AParcel_writeParcelableElement)(ref)
}

//export AParcel_writeParcelableElement73CCA07C
func AParcel_writeParcelableElement73CCA07C(cparcel *C.AParcel, carrayData unsafe.Pointer, cindex C.uint64_t) C.binder_status_t {
	if aParcel_writeParcelableElement73CCA07CFunc != nil {
		parcel73cca07c := (*AParcel)(unsafe.Pointer(cparcel))
		arrayData73cca07c := (unsafe.Pointer)(unsafe.Pointer(carrayData))
		index73cca07c := (uint64)(cindex)
		ret73cca07c := aParcel_writeParcelableElement73CCA07CFunc(parcel73cca07c, arrayData73cca07c, index73cca07c)
		ret, _ := (C.binder_status_t)(ret73cca07c), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aParcel_writeParcelableElement73CCA07CFunc AParcel_writeParcelableElement

// UnpackPCharString copies the data from Go string as *C.char.
func UnpackPCharString(str string) (*C.char, *CgoAllocMap) {
	allocs := new(CgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *CgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CString(str))
	allocs.Add(mem0)
	return (*C.char)(mem0), allocs
}
