// Code generated by idiomgen. DO NOT EDIT.

package persistablebundle

import (
	capi "github.com/AndroidGoLab/ndk/capi/persistablebundle"
)

// ReadFromParcel calls the underlying C function.
func ReadFromParcel(parcel *AParcel) (*PersistableBundle, error) {
	var outPBundlePtr *capi.APersistableBundle
	ret := capi.APersistableBundle_readFromParcel((*capi.AParcel)(parcel), &outPBundlePtr)
	if err := result(int32(ret)); err != nil {
		return nil, err
	}
	return &PersistableBundle{ptr: outPBundlePtr}, nil
}
