// Code generated by idiomgen. DO NOT EDIT.

package persistablebundle

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/persistablebundle"
)

// PersistableBundle wraps the NDK APersistableBundle handle.
type PersistableBundle struct {
	ptr *capi.APersistableBundle
}

// NewPersistableBundle creates a new PersistableBundle.
func NewPersistableBundle() *PersistableBundle {
	return &PersistableBundle{ptr: capi.APersistableBundle_new()}
}

// Close releases the underlying NDK handle.
func (h *PersistableBundle) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.APersistableBundle_delete(h.ptr)
	h.ptr = nil
	return nil
}

// NewPersistableBundleFromPointer wraps a raw APersistableBundle pointer.
func NewPersistableBundleFromPointer(ptr unsafe.Pointer) *PersistableBundle {
	return &PersistableBundle{ptr: (*capi.APersistableBundle)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *PersistableBundle) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// Dup creates a new PersistableBundle from this PersistableBundle.
func (h *PersistableBundle) Dup() *PersistableBundle {
	return &PersistableBundle{ptr: capi.APersistableBundle_dup(h.ptr)}
}

// Erase returns the value directly.
func (h *PersistableBundle) Erase(key string) int32 {
	return (int32)(capi.APersistableBundle_erase(h.ptr, key))
}

// GetBoolean returns the value directly.
func (h *PersistableBundle) GetBoolean(key string, val *bool) bool {
	return (bool)(capi.APersistableBundle_getBoolean(h.ptr, key, val))
}

// GetBooleanVector returns the value directly.
func (h *PersistableBundle) GetBooleanVector(key string, buffer *bool, bufferSizeBytes int32) int32 {
	return (int32)(capi.APersistableBundle_getBooleanVector(h.ptr, key, buffer, bufferSizeBytes))
}

// GetDouble returns the value directly.
func (h *PersistableBundle) GetDouble(key string, val *float64) bool {
	return (bool)(capi.APersistableBundle_getDouble(h.ptr, key, val))
}

// GetDoubleVector returns the value directly.
func (h *PersistableBundle) GetDoubleVector(key string, buffer *float64, bufferSizeBytes int32) int32 {
	return (int32)(capi.APersistableBundle_getDoubleVector(h.ptr, key, buffer, bufferSizeBytes))
}

// GetInt returns the value directly.
func (h *PersistableBundle) GetInt(key string, val *int32) bool {
	return (bool)(capi.APersistableBundle_getInt(h.ptr, key, val))
}

// GetIntVector returns the value directly.
func (h *PersistableBundle) GetIntVector(key string, buffer *int32, bufferSizeBytes int32) int32 {
	return (int32)(capi.APersistableBundle_getIntVector(h.ptr, key, buffer, bufferSizeBytes))
}

// GetLong returns the value directly.
func (h *PersistableBundle) GetLong(key string, val *int64) bool {
	return (bool)(capi.APersistableBundle_getLong(h.ptr, key, val))
}

// GetLongVector returns the value directly.
func (h *PersistableBundle) GetLongVector(key string, buffer *int64, bufferSizeBytes int32) int32 {
	return (int32)(capi.APersistableBundle_getLongVector(h.ptr, key, buffer, bufferSizeBytes))
}

// GetPersistableBundle calls the underlying NDK function.
func (h *PersistableBundle) GetPersistableBundle(key string) (*PersistableBundle, bool) {
	var outBundlePtr *capi.APersistableBundle
	ok := capi.APersistableBundle_getPersistableBundle(h.ptr, key, &outBundlePtr)
	if !ok {
		return nil, false
	}
	return &PersistableBundle{ptr: outBundlePtr}, true
}

// IsEqual returns the value directly.
func (h *PersistableBundle) IsEqual(rhs *PersistableBundle) bool {
	return (bool)(capi.APersistableBundle_isEqual(h.ptr, rhs.ptr))
}

// PutBoolean calls the underlying NDK function.
func (h *PersistableBundle) PutBoolean(key string, val bool) {
	capi.APersistableBundle_putBoolean(h.ptr, key, val)
}

// PutBooleanVector calls the underlying NDK function.
func (h *PersistableBundle) PutBooleanVector(key string, vec *bool, num int32) {
	capi.APersistableBundle_putBooleanVector(h.ptr, key, vec, num)
}

// PutDouble calls the underlying NDK function.
func (h *PersistableBundle) PutDouble(key string, val float64) {
	capi.APersistableBundle_putDouble(h.ptr, key, val)
}

// PutDoubleVector calls the underlying NDK function.
func (h *PersistableBundle) PutDoubleVector(key string, vec *float64, num int32) {
	capi.APersistableBundle_putDoubleVector(h.ptr, key, vec, num)
}

// PutInt calls the underlying NDK function.
func (h *PersistableBundle) PutInt(key string, val int32) {
	capi.APersistableBundle_putInt(h.ptr, key, val)
}

// PutIntVector calls the underlying NDK function.
func (h *PersistableBundle) PutIntVector(key string, vec *int32, num int32) {
	capi.APersistableBundle_putIntVector(h.ptr, key, vec, num)
}

// PutLong calls the underlying NDK function.
func (h *PersistableBundle) PutLong(key string, val int64) {
	capi.APersistableBundle_putLong(h.ptr, key, val)
}

// PutLongVector calls the underlying NDK function.
func (h *PersistableBundle) PutLongVector(key string, vec *int64, num int32) {
	capi.APersistableBundle_putLongVector(h.ptr, key, vec, num)
}

// PutPersistableBundle calls the underlying NDK function.
func (h *PersistableBundle) PutPersistableBundle(key string, val *PersistableBundle) {
	capi.APersistableBundle_putPersistableBundle(h.ptr, key, val.ptr)
}

// PutString calls the underlying NDK function.
func (h *PersistableBundle) PutString(key string, val string) {
	capi.APersistableBundle_putString(h.ptr, key, val)
}

// Size returns the value directly.
func (h *PersistableBundle) Size() int32 {
	return (int32)(capi.APersistableBundle_size(h.ptr))
}

// WriteToParcel calls the underlying NDK function.
func (h *PersistableBundle) WriteToParcel(parcel *AParcel) error {
	return result(int32(capi.APersistableBundle_writeToParcel(h.ptr, (*capi.AParcel)(parcel))))
}
