GENERATOR:
  PackageName: input
  PackageDescription: "Raw CGo bindings for Android input"
  PackageLicense: "Apache-2.0"
  Includes: ["android/input.h"]
  FlagGroups:
    - {name: LDFLAGS, flags: [-landroid]}
