// Code generated by idiomgen. DO NOT EDIT.

package nnapi

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/neuralnetworks"
)

// Device wraps the NDK ANeuralNetworksDevice handle.
type Device struct {
	ptr *capi.ANeuralNetworksDevice
}

// NewDeviceFromPointer wraps a raw ANeuralNetworksDevice pointer.
func NewDeviceFromPointer(ptr unsafe.Pointer) *Device {
	return &Device{ptr: (*capi.ANeuralNetworksDevice)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Device) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
