// Code generated by idiomgen. DO NOT EDIT.

package nnapi

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/neuralnetworks"
)

// Execution wraps the NDK ANeuralNetworksExecution handle.
type Execution struct {
	ptr *capi.ANeuralNetworksExecution
}



// NewExecutionFromPointer wraps a raw ANeuralNetworksExecution pointer.
func NewExecutionFromPointer(ptr unsafe.Pointer) *Execution {
	return &Execution{ptr: (*capi.ANeuralNetworksExecution)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Execution) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// Compute calls the underlying NDK function.
func (h *Execution) Compute() error {
	return result(int32(capi.ANeuralNetworksExecution_compute(h.ptr)))
}

// GetDuration calls the underlying NDK function.
func (h *Execution) GetDuration(durationCode int32, duration *uint64) error {
	return result(int32(capi.ANeuralNetworksExecution_getDuration(h.ptr, durationCode, duration)))
}

// SetMeasureTiming calls the underlying NDK function.
func (h *Execution) SetMeasureTiming(measure bool) error {
	return result(int32(capi.ANeuralNetworksExecution_setMeasureTiming(h.ptr, measure)))
}

// SetTimeout calls the underlying NDK function.
func (h *Execution) SetTimeout(duration uint64) error {
	return result(int32(capi.ANeuralNetworksExecution_setTimeout(h.ptr, duration)))
}


// StartCompute creates a new Event from this Execution.
func (h *Execution) StartCompute() (*Event, error) {
	var ptr *capi.ANeuralNetworksEvent
	if err := result(int32(capi.ANeuralNetworksExecution_startCompute(h.ptr, &ptr))); err != nil {
		return nil, err
	}
	return &Event{ptr: ptr}, nil
}



