// Code generated by idiomgen. DO NOT EDIT.

package nnapi

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/neuralnetworks"
)

// Memory wraps the NDK ANeuralNetworksMemory handle.
type Memory struct {
	ptr *capi.ANeuralNetworksMemory
}

// NewMemoryFromPointer wraps a raw ANeuralNetworksMemory pointer.
func NewMemoryFromPointer(ptr unsafe.Pointer) *Memory {
	return &Memory{ptr: (*capi.ANeuralNetworksMemory)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Memory) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
