// Code generated by capigen. DO NOT EDIT.

package media

/*
#cgo LDFLAGS: -lmediandk -Wl,--allow-shlib-undefined
#include "media/NdkImage.h"
#include "media/NdkImageReader.h"
#include "media/NdkMediaCodec.h"
#include "media/NdkMediaCodecInfo.h"
#include "media/NdkMediaDataSource.h"
#include "media/NdkMediaExtractor.h"
#include "media/NdkMediaFormat.h"
#include "media/NdkMediaMuxer.h"
#include "media/NdkMediaDrm.h"
#include "media/NdkMediaCrypto.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

type ABitrateMode int32

type ACodecAudioCapabilities C.ACodecAudioCapabilities

type ACodecEncoderCapabilities C.ACodecEncoderCapabilities

type ACodecPerformancePoint C.ACodecPerformancePoint

type ACodecVideoCapabilities C.ACodecVideoCapabilities

type ADoubleRange C.ADoubleRange

type AImage C.AImage

type AImageCropRect C.AImageCropRect

type AImageReader C.AImageReader

type AImageReader_BufferRemovedListener C.AImageReader_BufferRemovedListener

type AImageReader_ImageListener C.AImageReader_ImageListener

type AIntRange C.AIntRange

type AMediaCodec C.AMediaCodec

type AMediaCodecBufferInfo C.AMediaCodecBufferInfo

type AMediaCodecCryptoInfo C.AMediaCodecCryptoInfo

type AMediaCodecInfo C.AMediaCodecInfo

type AMediaCodecKind int32

type AMediaCodecOnAsyncNotifyCallback C.AMediaCodecOnAsyncNotifyCallback

type AMediaCodecType int32

type AMediaCrypto C.AMediaCrypto

type AMediaDataSource C.AMediaDataSource

type AMediaDrm C.AMediaDrm

type AMediaDrmByteArray C.AMediaDrmByteArray

type AMediaDrmEventType int32

type AMediaDrmKeyId AMediaDrmByteArray

type AMediaDrmKeyRequestType int32

type AMediaDrmKeySetId AMediaDrmByteArray

type AMediaDrmKeyStatus C.AMediaDrmKeyStatus

type AMediaDrmKeyStatusType int32

type AMediaDrmKeyType int32

type AMediaDrmKeyValue C.AMediaDrmKeyValue

type AMediaDrmScope AMediaDrmByteArray

type AMediaDrmSecureStop AMediaDrmByteArray

type AMediaDrmSessionId AMediaDrmByteArray

type AMediaExtractor C.AMediaExtractor

type AMediaFormat C.AMediaFormat

type AMediaMuxer C.AMediaMuxer

type AMediaUUID [16]uint8

type ANativeWindow C.ANativeWindow

type AppendMode int32

type OutputFormat int32

type PsshEntry C.PsshEntry

type PsshInfo C.PsshInfo

type SeekMode int32

type Cryptoinfo_mode_t int32

type Cryptoinfo_pattern_t C.cryptoinfo_pattern_t

type AMediaDrmKeyValuePair C.struct_AMediaDrmKeyValuePair

type AHardwareBuffer C.AHardwareBuffer

type Media_status_t C.media_status_t

type Off64_t C.off64_t

type Off_t C.off_t

type AImageReader_BufferRemovedCallback func(context unsafe.Pointer, reader *AImageReader, buffer *AHardwareBuffer)

type AImageReader_ImageCallback func(context unsafe.Pointer, reader *AImageReader)

type AMediaCodecOnAsyncError func(codec *AMediaCodec, userdata unsafe.Pointer, _error Media_status_t, actionCode int32, detail string)

type AMediaCodecOnAsyncFormatChanged func(codec *AMediaCodec, userdata unsafe.Pointer, format *AMediaFormat)

type AMediaCodecOnAsyncInputAvailable func(codec *AMediaCodec, userdata unsafe.Pointer, index int32)

type AMediaCodecOnAsyncOutputAvailable func(codec *AMediaCodec, userdata unsafe.Pointer, index int32, bufferInfo *AMediaCodecBufferInfo)

type AMediaCodecOnFrameRendered func(codec *AMediaCodec, userdata unsafe.Pointer, mediaTimeUs int64, systemNano int64)

type AMediaDataSourceClose func(userdata unsafe.Pointer)

type AMediaDataSourceGetAvailableSize func(userdata unsafe.Pointer, offset Off64_t) int64

type AMediaDataSourceGetSize func(userdata unsafe.Pointer) int64

type AMediaDataSourceReadAt func(userdata unsafe.Pointer, offset Off64_t, buffer unsafe.Pointer, size uint64) int64

type AMediaDrmEventListener func(p0 *AMediaDrm, sessionId *AMediaDrmSessionId, eventType AMediaDrmEventType, extra int32, data *uint8, dataSize uint64)

type AMediaDrmExpirationUpdateListener func(p0 *AMediaDrm, sessionId *AMediaDrmSessionId, expiryTimeInMS int64)

type AMediaDrmKeysChangeListener func(p0 *AMediaDrm, sessionId *AMediaDrmSessionId, keyStatus *AMediaDrmKeyStatus, numKeys uint64, hasNewUsableKey bool)
