// Code generated by idiomgen. DO NOT EDIT.

package egl

type NativeWindow_LegacyFormat int32

const (
	WINDOW_FORMAT_RGBA_8888 NativeWindow_LegacyFormat = 1
	WINDOW_FORMAT_RGBX_8888 NativeWindow_LegacyFormat = 2
	WINDOW_FORMAT_RGB_565   NativeWindow_LegacyFormat = 4
)
