// Code generated by capigen. DO NOT EDIT.

package multinetwork

/*
#cgo LDFLAGS: -landroid
#include "android/multinetwork.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

type Net_handle_t uint64

type Uid_t C.uid_t
