// Code generated by idiomgen. DO NOT EDIT.

package looper

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/looper"
)

// PollOnce calls the underlying C function.
func PollOnce(timeoutMillis int32, outFd *int32, outEvents *int32, outData *unsafe.Pointer) int32 {
	return (int32)(capi.ALooper_pollOnce(timeoutMillis, outFd, outEvents, outData))
}
