// Code generated by idiomgen. DO NOT EDIT.

package gles2

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/gles2"
)

// ActiveTexture calls the underlying C function.
func ActiveTexture(texture Enum) {
	capi.GlActiveTexture(capi.GLenum(texture))
}

// AttachShader calls the underlying C function.
func AttachShader(program GLuint, shader GLuint) {
	capi.GlAttachShader(capi.GLuint(program), capi.GLuint(shader))
}

// BindBuffer calls the underlying C function.
func BindBuffer(target Enum, buffer GLuint) {
	capi.GlBindBuffer(capi.GLenum(target), capi.GLuint(buffer))
}

// BindFramebuffer calls the underlying C function.
func BindFramebuffer(target Enum, framebuffer GLuint) {
	capi.GlBindFramebuffer(capi.GLenum(target), capi.GLuint(framebuffer))
}

// BindRenderbuffer calls the underlying C function.
func BindRenderbuffer(target Enum, renderbuffer GLuint) {
	capi.GlBindRenderbuffer(capi.GLenum(target), capi.GLuint(renderbuffer))
}

// BindTexture calls the underlying C function.
func BindTexture(target Enum, texture GLuint) {
	capi.GlBindTexture(capi.GLenum(target), capi.GLuint(texture))
}

// BlendFunc calls the underlying C function.
func BlendFunc(sfactor Enum, dfactor Enum) {
	capi.GlBlendFunc(capi.GLenum(sfactor), capi.GLenum(dfactor))
}

// BlendFuncSeparate calls the underlying C function.
func BlendFuncSeparate(sfactorRGB Enum, dfactorRGB Enum, sfactorAlpha Enum, dfactorAlpha Enum) {
	capi.GlBlendFuncSeparate(capi.GLenum(sfactorRGB), capi.GLenum(dfactorRGB), capi.GLenum(sfactorAlpha), capi.GLenum(dfactorAlpha))
}

// BufferData calls the underlying C function.
func BufferData(target Enum, size GLsizeiptr, data unsafe.Pointer, usage Enum) {
	capi.GlBufferData(capi.GLenum(target), capi.GLsizeiptr(size), data, capi.GLenum(usage))
}

// BufferSubData calls the underlying C function.
func BufferSubData(target Enum, offset GLintptr, size GLsizeiptr, data unsafe.Pointer) {
	capi.GlBufferSubData(capi.GLenum(target), capi.GLintptr(offset), capi.GLsizeiptr(size), data)
}

// CheckFramebufferStatus calls the underlying C function.
func CheckFramebufferStatus(target Enum) Enum {
	return (Enum)(capi.GlCheckFramebufferStatus(capi.GLenum(target)))
}

// Clear calls the underlying C function.
func Clear(mask Bitfield) {
	capi.GlClear(capi.GLbitfield(mask))
}

// ClearColor calls the underlying C function.
func ClearColor(red GLfloat, green GLfloat, blue GLfloat, alpha GLfloat) {
	capi.GlClearColor(capi.GLfloat(red), capi.GLfloat(green), capi.GLfloat(blue), capi.GLfloat(alpha))
}

// CompileShader calls the underlying C function.
func CompileShader(shader GLuint) {
	capi.GlCompileShader(capi.GLuint(shader))
}

// CreateProgram calls the underlying C function.
func CreateProgram() GLuint {
	return (GLuint)(capi.GlCreateProgram())
}

// CreateShader calls the underlying C function.
func CreateShader(_type Enum) GLuint {
	return (GLuint)(capi.GlCreateShader(capi.GLenum(_type)))
}

// DeleteBuffers calls the underlying C function.
func DeleteBuffers(n GLsizei, buffers *GLuint) {
	capi.GlDeleteBuffers(capi.GLsizei(n), (*capi.GLuint)(buffers))
}

// DeleteFramebuffers calls the underlying C function.
func DeleteFramebuffers(n GLsizei, framebuffers *GLuint) {
	capi.GlDeleteFramebuffers(capi.GLsizei(n), (*capi.GLuint)(framebuffers))
}

// DeleteProgram calls the underlying C function.
func DeleteProgram(program GLuint) {
	capi.GlDeleteProgram(capi.GLuint(program))
}

// DeleteRenderbuffers calls the underlying C function.
func DeleteRenderbuffers(n GLsizei, renderbuffers *GLuint) {
	capi.GlDeleteRenderbuffers(capi.GLsizei(n), (*capi.GLuint)(renderbuffers))
}

// DeleteShader calls the underlying C function.
func DeleteShader(shader GLuint) {
	capi.GlDeleteShader(capi.GLuint(shader))
}

// DeleteTextures calls the underlying C function.
func DeleteTextures(n GLsizei, textures *GLuint) {
	capi.GlDeleteTextures(capi.GLsizei(n), (*capi.GLuint)(textures))
}

// DepthFunc calls the underlying C function.
func DepthFunc(_func Enum) {
	capi.GlDepthFunc(capi.GLenum(_func))
}

// DepthMask calls the underlying C function.
func DepthMask(flag Boolean) {
	capi.GlDepthMask(capi.GLboolean(flag))
}

// Disable calls the underlying C function.
func Disable(cap Enum) {
	capi.GlDisable(capi.GLenum(cap))
}

// DisableVertexAttribArray calls the underlying C function.
func DisableVertexAttribArray(index GLuint) {
	capi.GlDisableVertexAttribArray(capi.GLuint(index))
}

// DrawArrays calls the underlying C function.
func DrawArrays(mode Enum, first GLint, count GLsizei) {
	capi.GlDrawArrays(capi.GLenum(mode), capi.GLint(first), capi.GLsizei(count))
}

// DrawElements calls the underlying C function.
func DrawElements(mode Enum, count GLsizei, _type Enum, indices unsafe.Pointer) {
	capi.GlDrawElements(capi.GLenum(mode), capi.GLsizei(count), capi.GLenum(_type), indices)
}

// Enable calls the underlying C function.
func Enable(cap Enum) {
	capi.GlEnable(capi.GLenum(cap))
}

// EnableVertexAttribArray calls the underlying C function.
func EnableVertexAttribArray(index GLuint) {
	capi.GlEnableVertexAttribArray(capi.GLuint(index))
}

// Finish calls the underlying C function.
func Finish() {
	capi.GlFinish()
}

// Flush calls the underlying C function.
func Flush() {
	capi.GlFlush()
}

// FramebufferRenderbuffer calls the underlying C function.
func FramebufferRenderbuffer(target Enum, attachment Enum, renderbuffertarget Enum, renderbuffer GLuint) {
	capi.GlFramebufferRenderbuffer(capi.GLenum(target), capi.GLenum(attachment), capi.GLenum(renderbuffertarget), capi.GLuint(renderbuffer))
}

// FramebufferTexture2D calls the underlying C function.
func FramebufferTexture2D(target Enum, attachment Enum, textarget Enum, texture GLuint, level GLint) {
	capi.GlFramebufferTexture2D(capi.GLenum(target), capi.GLenum(attachment), capi.GLenum(textarget), capi.GLuint(texture), capi.GLint(level))
}

// GenBuffers calls the underlying C function.
func GenBuffers(n GLsizei, buffers *GLuint) {
	capi.GlGenBuffers(capi.GLsizei(n), (*capi.GLuint)(buffers))
}

// GenFramebuffers calls the underlying C function.
func GenFramebuffers(n GLsizei, framebuffers *GLuint) {
	capi.GlGenFramebuffers(capi.GLsizei(n), (*capi.GLuint)(framebuffers))
}

// GenRenderbuffers calls the underlying C function.
func GenRenderbuffers(n GLsizei, renderbuffers *GLuint) {
	capi.GlGenRenderbuffers(capi.GLsizei(n), (*capi.GLuint)(renderbuffers))
}

// GenTextures calls the underlying C function.
func GenTextures(n GLsizei, textures *GLuint) {
	capi.GlGenTextures(capi.GLsizei(n), (*capi.GLuint)(textures))
}

// GetAttribLocation calls the underlying C function.
func GetAttribLocation(program GLuint, name *GLchar) GLint {
	return (GLint)(capi.GlGetAttribLocation(capi.GLuint(program), (*capi.GLchar)(name)))
}

// GetError calls the underlying C function.
func GetError() Enum {
	return (Enum)(capi.GlGetError())
}

// GetIntegerv calls the underlying C function.
func GetIntegerv(pname Enum, data *GLint) {
	capi.GlGetIntegerv(capi.GLenum(pname), (*capi.GLint)(data))
}

// GetProgramiv calls the underlying C function.
func GetProgramiv(program GLuint, pname Enum, params *GLint) {
	capi.GlGetProgramiv(capi.GLuint(program), capi.GLenum(pname), (*capi.GLint)(params))
}

// GetShaderiv calls the underlying C function.
func GetShaderiv(shader GLuint, pname Enum, params *GLint) {
	capi.GlGetShaderiv(capi.GLuint(shader), capi.GLenum(pname), (*capi.GLint)(params))
}

// GetString calls the underlying C function.
func GetString(name Enum) *GLubyte {
	return (*GLubyte)(capi.GlGetString(capi.GLenum(name)))
}

// GetUniformLocation calls the underlying C function.
func GetUniformLocation(program GLuint, name *GLchar) GLint {
	return (GLint)(capi.GlGetUniformLocation(capi.GLuint(program), (*capi.GLchar)(name)))
}

// LineWidth calls the underlying C function.
func LineWidth(width GLfloat) {
	capi.GlLineWidth(capi.GLfloat(width))
}

// LinkProgram calls the underlying C function.
func LinkProgram(program GLuint) {
	capi.GlLinkProgram(capi.GLuint(program))
}

// PixelStorei calls the underlying C function.
func PixelStorei(pname Enum, param GLint) {
	capi.GlPixelStorei(capi.GLenum(pname), capi.GLint(param))
}

// ReadPixels calls the underlying C function.
func ReadPixels(x GLint, y GLint, width GLsizei, height GLsizei, format Enum, _type Enum, pixels unsafe.Pointer) {
	capi.GlReadPixels(capi.GLint(x), capi.GLint(y), capi.GLsizei(width), capi.GLsizei(height), capi.GLenum(format), capi.GLenum(_type), pixels)
}

// RenderbufferStorage calls the underlying C function.
func RenderbufferStorage(target Enum, internalformat Enum, width GLsizei, height GLsizei) {
	capi.GlRenderbufferStorage(capi.GLenum(target), capi.GLenum(internalformat), capi.GLsizei(width), capi.GLsizei(height))
}

// Scissor calls the underlying C function.
func Scissor(x GLint, y GLint, width GLsizei, height GLsizei) {
	capi.GlScissor(capi.GLint(x), capi.GLint(y), capi.GLsizei(width), capi.GLsizei(height))
}

// ShaderSource calls the underlying C function.
func ShaderSource(shader GLuint, count GLsizei, string **GLchar, length *GLint) {
	capi.GlShaderSource(capi.GLuint(shader), capi.GLsizei(count), (**capi.GLchar)(string), (*capi.GLint)(length))
}

// StencilFunc calls the underlying C function.
func StencilFunc(_func Enum, ref GLint, mask GLuint) {
	capi.GlStencilFunc(capi.GLenum(_func), capi.GLint(ref), capi.GLuint(mask))
}

// StencilOp calls the underlying C function.
func StencilOp(fail Enum, zfail Enum, zpass Enum) {
	capi.GlStencilOp(capi.GLenum(fail), capi.GLenum(zfail), capi.GLenum(zpass))
}

// TexImage2D calls the underlying C function.
func TexImage2D(target Enum, level GLint, internalformat GLint, width GLsizei, height GLsizei, border GLint, format Enum, _type Enum, pixels unsafe.Pointer) {
	capi.GlTexImage2D(capi.GLenum(target), capi.GLint(level), capi.GLint(internalformat), capi.GLsizei(width), capi.GLsizei(height), capi.GLint(border), capi.GLenum(format), capi.GLenum(_type), pixels)
}

// TexParameteri calls the underlying C function.
func TexParameteri(target Enum, pname Enum, param GLint) {
	capi.GlTexParameteri(capi.GLenum(target), capi.GLenum(pname), capi.GLint(param))
}

// Uniform1f calls the underlying C function.
func Uniform1f(location GLint, v0 GLfloat) {
	capi.GlUniform1f(capi.GLint(location), capi.GLfloat(v0))
}

// Uniform1i calls the underlying C function.
func Uniform1i(location GLint, v0 GLint) {
	capi.GlUniform1i(capi.GLint(location), capi.GLint(v0))
}

// Uniform4fv calls the underlying C function.
func Uniform4fv(location GLint, count GLsizei, value *GLfloat) {
	capi.GlUniform4fv(capi.GLint(location), capi.GLsizei(count), (*capi.GLfloat)(value))
}

// UniformMatrix4fv calls the underlying C function.
func UniformMatrix4fv(location GLint, count GLsizei, transpose Boolean, value *GLfloat) {
	capi.GlUniformMatrix4fv(capi.GLint(location), capi.GLsizei(count), capi.GLboolean(transpose), (*capi.GLfloat)(value))
}

// UseProgram calls the underlying C function.
func UseProgram(program GLuint) {
	capi.GlUseProgram(capi.GLuint(program))
}

// VertexAttribPointer calls the underlying C function.
func VertexAttribPointer(index GLuint, size GLint, _type Enum, normalized Boolean, stride GLsizei, pointer unsafe.Pointer) {
	capi.GlVertexAttribPointer(capi.GLuint(index), capi.GLint(size), capi.GLenum(_type), capi.GLboolean(normalized), capi.GLsizei(stride), pointer)
}

// Viewport calls the underlying C function.
func Viewport(x GLint, y GLint, width GLsizei, height GLsizei) {
	capi.GlViewport(capi.GLint(x), capi.GLint(y), capi.GLsizei(width), capi.GLsizei(height))
}
