// Code generated by capigen. DO NOT EDIT.

package looper

/*
#cgo LDFLAGS: -landroid
#include "android/looper.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"sync"
	"unsafe"
)

// CgoAllocMap stores pointers to C allocated memory for future reference.
type CgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(CgoAllocMap)

func (a *CgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *CgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *CgoAllocMap) Borrow(b *CgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *CgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

type SliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

func (x ALooper_callbackFunc) PassRef() (ref *C.ALooper_callbackFunc, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aLooper_callbackFuncE9F631A5Func == nil {
		aLooper_callbackFuncE9F631A5Func = x
	}
	return (*C.ALooper_callbackFunc)(C.ALooper_callbackFunc_e9f631a5), nil
}

func (x ALooper_callbackFunc) PassValue() (ref C.ALooper_callbackFunc, allocs *CgoAllocMap) {
	if x == nil {
		return nil, nil
	}
	if aLooper_callbackFuncE9F631A5Func == nil {
		aLooper_callbackFuncE9F631A5Func = x
	}
	return (C.ALooper_callbackFunc)(C.ALooper_callbackFunc_e9f631a5), nil
}

func NewALooper_callbackFuncRef(ref unsafe.Pointer) *ALooper_callbackFunc {
	return (*ALooper_callbackFunc)(ref)
}

//export ALooper_callbackFuncE9F631A5
func ALooper_callbackFuncE9F631A5(cfd C.int, cevents C.int, cdata unsafe.Pointer) C.int {
	if aLooper_callbackFuncE9F631A5Func != nil {
		fde9f631a5 := (int32)(cfd)
		eventse9f631a5 := (int32)(cevents)
		datae9f631a5 := (unsafe.Pointer)(unsafe.Pointer(cdata))
		rete9f631a5 := aLooper_callbackFuncE9F631A5Func(fde9f631a5, eventse9f631a5, datae9f631a5)
		ret, _ := (C.int)(rete9f631a5), cgoAllocsUnknown
		return ret
	}
	panic("callback func has not been set (race?)")
}

var aLooper_callbackFuncE9F631A5Func ALooper_callbackFunc
