// Code generated by capigen. DO NOT EDIT.

package hardwarebuffer

/*
#cgo LDFLAGS: -lnativewindow
#include "android/hardware_buffer.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

var _ runtime.Error
var _ unsafe.Pointer

func AHardwareBuffer_acquire(buffer *AHardwareBuffer) {
	cbuffer, cbufferAllocMap := (*C.AHardwareBuffer)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	C.AHardwareBuffer_acquire(cbuffer)
	runtime.KeepAlive(cbufferAllocMap)
}

func AHardwareBuffer_allocate(desc *AHardwareBuffer_Desc, outBuffer **AHardwareBuffer) int32 {
	cdesc, cdescAllocMap := (*C.AHardwareBuffer_Desc)(unsafe.Pointer(desc)), cgoAllocsUnknown
	coutBuffer, coutBufferAllocMap := (**C.AHardwareBuffer)(unsafe.Pointer(outBuffer)), cgoAllocsUnknown
	var pinnercoutBuffer runtime.Pinner
	pinnercoutBuffer.Pin(outBuffer)
	if outBuffer != nil {
		pinnercoutBuffer.Pin(unsafe.Pointer(*outBuffer))
	}
	defer pinnercoutBuffer.Unpin()
	__ret := C.AHardwareBuffer_allocate(cdesc, coutBuffer)
	runtime.KeepAlive(coutBufferAllocMap)
	runtime.KeepAlive(cdescAllocMap)
	__v := (int32)(__ret)
	return __v
}

func AHardwareBuffer_describe(buffer *AHardwareBuffer, outDesc *AHardwareBuffer_Desc) {
	cbuffer, cbufferAllocMap := (*C.AHardwareBuffer)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	coutDesc, coutDescAllocMap := (*C.AHardwareBuffer_Desc)(unsafe.Pointer(outDesc)), cgoAllocsUnknown
	C.AHardwareBuffer_describe(cbuffer, coutDesc)
	runtime.KeepAlive(coutDescAllocMap)
	runtime.KeepAlive(cbufferAllocMap)
}

func AHardwareBuffer_getId(buffer *AHardwareBuffer, outId *uint64) int32 {
	cbuffer, cbufferAllocMap := (*C.AHardwareBuffer)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	coutId, coutIdAllocMap := (*C.uint64_t)(unsafe.Pointer(outId)), cgoAllocsUnknown
	__ret := C.AHardwareBuffer_getId(cbuffer, coutId)
	runtime.KeepAlive(coutIdAllocMap)
	runtime.KeepAlive(cbufferAllocMap)
	__v := (int32)(__ret)
	return __v
}

func AHardwareBuffer_isSupported(desc *AHardwareBuffer_Desc) int32 {
	cdesc, cdescAllocMap := (*C.AHardwareBuffer_Desc)(unsafe.Pointer(desc)), cgoAllocsUnknown
	__ret := C.AHardwareBuffer_isSupported(cdesc)
	runtime.KeepAlive(cdescAllocMap)
	__v := (int32)(__ret)
	return __v
}

func AHardwareBuffer_lock(buffer *AHardwareBuffer, usage uint64, fence int32, rect *ARect, outVirtualAddress *unsafe.Pointer) int32 {
	cbuffer, cbufferAllocMap := (*C.AHardwareBuffer)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	cusage, cusageAllocMap := (C.uint64_t)(usage), cgoAllocsUnknown
	cfence, cfenceAllocMap := (C.int)(fence), cgoAllocsUnknown
	crect, crectAllocMap := (*C.ARect)(unsafe.Pointer(rect)), cgoAllocsUnknown
	coutVirtualAddress, coutVirtualAddressAllocMap := outVirtualAddress, cgoAllocsUnknown
	__ret := C.AHardwareBuffer_lock(cbuffer, cusage, cfence, crect, coutVirtualAddress)
	runtime.KeepAlive(coutVirtualAddressAllocMap)
	runtime.KeepAlive(crectAllocMap)
	runtime.KeepAlive(cfenceAllocMap)
	runtime.KeepAlive(cusageAllocMap)
	runtime.KeepAlive(cbufferAllocMap)
	__v := (int32)(__ret)
	return __v
}

func AHardwareBuffer_lockAndGetInfo(buffer *AHardwareBuffer, usage uint64, fence int32, rect *ARect, outVirtualAddress *unsafe.Pointer, outBytesPerPixel *int32, outBytesPerStride *int32) int32 {
	cbuffer, cbufferAllocMap := (*C.AHardwareBuffer)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	cusage, cusageAllocMap := (C.uint64_t)(usage), cgoAllocsUnknown
	cfence, cfenceAllocMap := (C.int)(fence), cgoAllocsUnknown
	crect, crectAllocMap := (*C.ARect)(unsafe.Pointer(rect)), cgoAllocsUnknown
	coutVirtualAddress, coutVirtualAddressAllocMap := outVirtualAddress, cgoAllocsUnknown
	coutBytesPerPixel, coutBytesPerPixelAllocMap := (*C.int)(unsafe.Pointer(outBytesPerPixel)), cgoAllocsUnknown
	coutBytesPerStride, coutBytesPerStrideAllocMap := (*C.int)(unsafe.Pointer(outBytesPerStride)), cgoAllocsUnknown
	__ret := C.AHardwareBuffer_lockAndGetInfo(cbuffer, cusage, cfence, crect, coutVirtualAddress, coutBytesPerPixel, coutBytesPerStride)
	runtime.KeepAlive(coutBytesPerStrideAllocMap)
	runtime.KeepAlive(coutBytesPerPixelAllocMap)
	runtime.KeepAlive(coutVirtualAddressAllocMap)
	runtime.KeepAlive(crectAllocMap)
	runtime.KeepAlive(cfenceAllocMap)
	runtime.KeepAlive(cusageAllocMap)
	runtime.KeepAlive(cbufferAllocMap)
	__v := (int32)(__ret)
	return __v
}

func AHardwareBuffer_lockPlanes(buffer *AHardwareBuffer, usage uint64, fence int32, rect *ARect, outPlanes *AHardwareBuffer_Planes) int32 {
	cbuffer, cbufferAllocMap := (*C.AHardwareBuffer)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	cusage, cusageAllocMap := (C.uint64_t)(usage), cgoAllocsUnknown
	cfence, cfenceAllocMap := (C.int)(fence), cgoAllocsUnknown
	crect, crectAllocMap := (*C.ARect)(unsafe.Pointer(rect)), cgoAllocsUnknown
	coutPlanes, coutPlanesAllocMap := (*C.AHardwareBuffer_Planes)(unsafe.Pointer(outPlanes)), cgoAllocsUnknown
	__ret := C.AHardwareBuffer_lockPlanes(cbuffer, cusage, cfence, crect, coutPlanes)
	runtime.KeepAlive(coutPlanesAllocMap)
	runtime.KeepAlive(crectAllocMap)
	runtime.KeepAlive(cfenceAllocMap)
	runtime.KeepAlive(cusageAllocMap)
	runtime.KeepAlive(cbufferAllocMap)
	__v := (int32)(__ret)
	return __v
}

func AHardwareBuffer_recvHandleFromUnixSocket(socketFd int32, outBuffer **AHardwareBuffer) int32 {
	csocketFd, csocketFdAllocMap := (C.int)(socketFd), cgoAllocsUnknown
	coutBuffer, coutBufferAllocMap := (**C.AHardwareBuffer)(unsafe.Pointer(outBuffer)), cgoAllocsUnknown
	var pinnercoutBuffer runtime.Pinner
	pinnercoutBuffer.Pin(outBuffer)
	if outBuffer != nil {
		pinnercoutBuffer.Pin(unsafe.Pointer(*outBuffer))
	}
	defer pinnercoutBuffer.Unpin()
	__ret := C.AHardwareBuffer_recvHandleFromUnixSocket(csocketFd, coutBuffer)
	runtime.KeepAlive(coutBufferAllocMap)
	runtime.KeepAlive(csocketFdAllocMap)
	__v := (int32)(__ret)
	return __v
}

func AHardwareBuffer_release(buffer *AHardwareBuffer) {
	cbuffer, cbufferAllocMap := (*C.AHardwareBuffer)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	C.AHardwareBuffer_release(cbuffer)
	runtime.KeepAlive(cbufferAllocMap)
}

func AHardwareBuffer_sendHandleToUnixSocket(buffer *AHardwareBuffer, socketFd int32) int32 {
	cbuffer, cbufferAllocMap := (*C.AHardwareBuffer)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	csocketFd, csocketFdAllocMap := (C.int)(socketFd), cgoAllocsUnknown
	__ret := C.AHardwareBuffer_sendHandleToUnixSocket(cbuffer, csocketFd)
	runtime.KeepAlive(csocketFdAllocMap)
	runtime.KeepAlive(cbufferAllocMap)
	__v := (int32)(__ret)
	return __v
}

func AHardwareBuffer_unlock(buffer *AHardwareBuffer, fence *int32) int32 {
	cbuffer, cbufferAllocMap := (*C.AHardwareBuffer)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	cfence, cfenceAllocMap := (*C.int)(unsafe.Pointer(fence)), cgoAllocsUnknown
	__ret := C.AHardwareBuffer_unlock(cbuffer, cfence)
	runtime.KeepAlive(cfenceAllocMap)
	runtime.KeepAlive(cbufferAllocMap)
	__v := (int32)(__ret)
	return __v
}
