// Code generated by idiomgen. DO NOT EDIT.

package camera

import (
	capi "github.com/xaionaro-go/ndk/capi/camera"
)

type acamera_metadata_enum_android_sensor_reference_illuminant1_t = capi.Acamera_metadata_enum_android_sensor_reference_illuminant1_t
