// Code generated by idiomgen. DO NOT EDIT.

package camera

type acamera_metadata_enum_android_control_af_trigger_t int32

const (
	ACAMERA_CONTROL_AF_TRIGGER_IDLE   acamera_metadata_enum_android_control_af_trigger_t = 0
	ACAMERA_CONTROL_AF_TRIGGER_START  acamera_metadata_enum_android_control_af_trigger_t = 1
	ACAMERA_CONTROL_AF_TRIGGER_CANCEL acamera_metadata_enum_android_control_af_trigger_t = 2
)
