// Code generated by idiomgen. DO NOT EDIT.

package camera

type acamera_metadata_enum_android_control_ae_lock_t int32

const (
	ACAMERA_CONTROL_AE_LOCK_OFF acamera_metadata_enum_android_control_ae_lock_t = 0
	ACAMERA_CONTROL_AE_LOCK_ON  acamera_metadata_enum_android_control_ae_lock_t = 1
)
