// Code generated by idiomgen. DO NOT EDIT.

package camera

type acamera_metadata_enum_android_depth_depth_is_exclusive_t int32

const (
	ACAMERA_DEPTH_DEPTH_IS_EXCLUSIVE_FALSE acamera_metadata_enum_android_depth_depth_is_exclusive_t = 0
	ACAMERA_DEPTH_DEPTH_IS_EXCLUSIVE_TRUE  acamera_metadata_enum_android_depth_depth_is_exclusive_t = 1
)
