// Code generated by idiomgen. DO NOT EDIT.

package camera

import (
	capi "github.com/AndroidGoLab/ndk/capi/camera"
)

type ACameraCaptureSession_prepareCallback = capi.ACameraCaptureSession_prepareCallback
