// Code generated by idiomgen. DO NOT EDIT.

package camera

import (
	capi "github.com/xaionaro-go/ndk/capi/camera"
)

type acamera_metadata_enum_android_black_level_lock_t = capi.Acamera_metadata_enum_android_black_level_lock_t
