// Code generated by idiomgen. DO NOT EDIT.

package camera

type acamera_metadata_enum_android_control_ae_lock_available_t int32

const (
	ACAMERA_CONTROL_AE_LOCK_AVAILABLE_FALSE acamera_metadata_enum_android_control_ae_lock_available_t = 0
	ACAMERA_CONTROL_AE_LOCK_AVAILABLE_TRUE  acamera_metadata_enum_android_control_ae_lock_available_t = 1
)
