// Code generated by idiomgen. DO NOT EDIT.

package camera

import (
	capi "github.com/xaionaro-go/ndk/capi/camera"
)

type acamera_metadata_enum_android_depth_available_dynamic_depth_stream_configurations_maximum_resolution_t = capi.Acamera_metadata_enum_android_depth_available_dynamic_depth_stream_configurations_maximum_resolution_t
