// Code generated by idiomgen. DO NOT EDIT.

package camera

type acamera_metadata_enum_android_control_extended_scene_mode_t int32

const (
	ACAMERA_CONTROL_EXTENDED_SCENE_MODE_DISABLED            acamera_metadata_enum_android_control_extended_scene_mode_t = 0
	ACAMERA_CONTROL_EXTENDED_SCENE_MODE_BOKEH_STILL_CAPTURE acamera_metadata_enum_android_control_extended_scene_mode_t = 1
	ACAMERA_CONTROL_EXTENDED_SCENE_MODE_BOKEH_CONTINUOUS    acamera_metadata_enum_android_control_extended_scene_mode_t = 2
)
