// Code generated by idiomgen. DO NOT EDIT.

package camera

type acamera_metadata_enum_android_control_awb_lock_available_t int32

const (
	ACAMERA_CONTROL_AWB_LOCK_AVAILABLE_FALSE acamera_metadata_enum_android_control_awb_lock_available_t = 0
	ACAMERA_CONTROL_AWB_LOCK_AVAILABLE_TRUE  acamera_metadata_enum_android_control_awb_lock_available_t = 1
)
