// Code generated by idiomgen. DO NOT EDIT.

package camera

type acamera_metadata_enum_android_statistics_face_detect_mode_t int32

const (
	ACAMERA_STATISTICS_FACE_DETECT_MODE_OFF    acamera_metadata_enum_android_statistics_face_detect_mode_t = 0
	ACAMERA_STATISTICS_FACE_DETECT_MODE_SIMPLE acamera_metadata_enum_android_statistics_face_detect_mode_t = 1
	ACAMERA_STATISTICS_FACE_DETECT_MODE_FULL   acamera_metadata_enum_android_statistics_face_detect_mode_t = 2
)
