// Code generated by idiomgen. DO NOT EDIT.

package camera

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/camera"
)

// CameraManager_AvailabilityCallbacks wraps the NDK ACameraManager_AvailabilityCallbacks handle.
type CameraManager_AvailabilityCallbacks struct {
	ptr *capi.ACameraManager_AvailabilityCallbacks
}

// NewCameraManager_AvailabilityCallbacksFromPointer wraps a raw ACameraManager_AvailabilityCallbacks pointer.
func NewCameraManager_AvailabilityCallbacksFromPointer(ptr unsafe.Pointer) *CameraManager_AvailabilityCallbacks {
	return &CameraManager_AvailabilityCallbacks{ptr: (*capi.ACameraManager_AvailabilityCallbacks)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *CameraManager_AvailabilityCallbacks) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
