// Code generated by idiomgen. DO NOT EDIT.

package camera

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/camera"
)

// CameraOutputTargets wraps the NDK ACameraOutputTargets handle.
type CameraOutputTargets struct {
	ptr *capi.ACameraOutputTargets
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *CameraOutputTargets) cptr() *capi.ACameraOutputTargets {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewCameraOutputTargetsFromPointer wraps a raw ACameraOutputTargets pointer.
func NewCameraOutputTargetsFromPointer(ptr unsafe.Pointer) *CameraOutputTargets {
	return &CameraOutputTargets{ptr: (*capi.ACameraOutputTargets)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *CameraOutputTargets) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
