// Code generated by idiomgen. DO NOT EDIT.

package camera

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/camera"
)

// CameraOutputTargets wraps the NDK ACameraOutputTargets handle.
type CameraOutputTargets struct {
	ptr *capi.ACameraOutputTargets
}

// NewCameraOutputTargetsFromPointer wraps a raw ACameraOutputTargets pointer.
func NewCameraOutputTargetsFromPointer(ptr unsafe.Pointer) *CameraOutputTargets {
	return &CameraOutputTargets{ptr: (*capi.ACameraOutputTargets)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *CameraOutputTargets) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
