// Code generated by idiomgen. DO NOT EDIT.

package camera

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/camera"
)

// CameraCaptureFailure wraps the NDK ACameraCaptureFailure handle.
type CameraCaptureFailure struct {
	ptr *capi.ACameraCaptureFailure
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *CameraCaptureFailure) cptr() *capi.ACameraCaptureFailure {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewCameraCaptureFailureFromPointer wraps a raw ACameraCaptureFailure pointer.
func NewCameraCaptureFailureFromPointer(ptr unsafe.Pointer) *CameraCaptureFailure {
	return &CameraCaptureFailure{ptr: (*capi.ACameraCaptureFailure)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *CameraCaptureFailure) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
