// Code generated by idiomgen. DO NOT EDIT.

package camera

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/camera"
)

// CameraCaptureSession_captureCallbacks wraps the NDK ACameraCaptureSession_captureCallbacks handle.
type CameraCaptureSession_captureCallbacks struct {
	ptr *capi.ACameraCaptureSession_captureCallbacks
}

// NewCameraCaptureSession_captureCallbacksFromPointer wraps a raw ACameraCaptureSession_captureCallbacks pointer.
func NewCameraCaptureSession_captureCallbacksFromPointer(ptr unsafe.Pointer) *CameraCaptureSession_captureCallbacks {
	return &CameraCaptureSession_captureCallbacks{ptr: (*capi.ACameraCaptureSession_captureCallbacks)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *CameraCaptureSession_captureCallbacks) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
