// Code generated by idiomgen. DO NOT EDIT.

package camera

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/camera"
)

// CaptureSession wraps the NDK ACameraCaptureSession handle.
type CaptureSession struct {
	ptr *capi.ACameraCaptureSession
}


// Close releases the underlying NDK handle.
func (h *CaptureSession) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.ACameraCaptureSession_close(h.ptr)
	h.ptr = nil
	return nil
}


// NewCaptureSessionFromPointer wraps a raw ACameraCaptureSession pointer.
func NewCaptureSessionFromPointer(ptr unsafe.Pointer) *CaptureSession {
	return &CaptureSession{ptr: (*capi.ACameraCaptureSession)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *CaptureSession) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// SetRepeatingRequest calls the underlying NDK function.
func (h *CaptureSession) SetRepeatingRequest(req *CaptureRequest) error {
	return result(int32(capi.ACameraCaptureSession_setRepeatingRequest(h.ptr, nil, 1, &req.ptr, nil)))
}
// StopRepeating calls the underlying NDK function.
func (h *CaptureSession) StopRepeating() error {
	return result(int32(capi.ACameraCaptureSession_stopRepeating(h.ptr)))
}


