// Code generated by idiomgen. DO NOT EDIT.

package camera

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/camera"
)

// CaptureSession wraps the NDK ACameraCaptureSession handle.
type CaptureSession struct {
	ptr *capi.ACameraCaptureSession
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *CaptureSession) cptr() *capi.ACameraCaptureSession {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close releases the underlying NDK handle.
func (h *CaptureSession) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.ACameraCaptureSession_close(h.ptr)
	h.ptr = nil
	return nil
}

// NewCaptureSessionFromPointer wraps a raw ACameraCaptureSession pointer.
func NewCaptureSessionFromPointer(ptr unsafe.Pointer) *CaptureSession {
	return &CaptureSession{ptr: (*capi.ACameraCaptureSession)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *CaptureSession) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *CaptureSession) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewCaptureSessionFromUintPtr wraps a uintptr as a CaptureSession.
// The caller must ensure ptr points to a valid ACameraCaptureSession.
func NewCaptureSessionFromUintPtr(ptr uintptr) *CaptureSession {
	return &CaptureSession{ptr: (*capi.ACameraCaptureSession)(unsafe.Pointer(ptr))}
}

// SetRepeatingRequest calls the underlying NDK function.
func (h *CaptureSession) SetRepeatingRequest(req *CaptureRequest) error {
	return result(capi.ACameraCaptureSession_setRepeatingRequest(h.ptr, nil, 1, &req.ptr, nil))
}

// StopRepeating calls the underlying NDK function.
func (h *CaptureSession) StopRepeating() error {
	return result(capi.ACameraCaptureSession_stopRepeating(h.ptr))
}
