// Code generated by idiomgen. DO NOT EDIT.

package camera

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/camera"
)

// CaptureRequest wraps the NDK ACaptureRequest handle.
type CaptureRequest struct {
	ptr *capi.ACaptureRequest
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *CaptureRequest) cptr() *capi.ACaptureRequest {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close releases the underlying NDK handle.
func (h *CaptureRequest) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.ACaptureRequest_free(h.ptr)
	h.ptr = nil
	return nil
}

// NewCaptureRequestFromPointer wraps a raw ACaptureRequest pointer.
func NewCaptureRequestFromPointer(ptr unsafe.Pointer) *CaptureRequest {
	return &CaptureRequest{ptr: (*capi.ACaptureRequest)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *CaptureRequest) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *CaptureRequest) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewCaptureRequestFromUintPtr wraps a uintptr as a CaptureRequest.
// The caller must ensure ptr points to a valid ACaptureRequest.
func NewCaptureRequestFromUintPtr(ptr uintptr) *CaptureRequest {
	return &CaptureRequest{ptr: (*capi.ACaptureRequest)(unsafe.Pointer(ptr))}
}

// AddTarget sets a property and returns the receiver for chaining.
func (h *CaptureRequest) AddTarget(output *OutputTarget) *CaptureRequest {
	capi.ACaptureRequest_addTarget(h.ptr, output.cptr())
	return h
}

// Copy creates a new CaptureRequest from this CaptureRequest.
func (h *CaptureRequest) Copy() *CaptureRequest {
	return &CaptureRequest{ptr: capi.ACaptureRequest_copy(h.ptr)}
}

// RemoveTarget calls the underlying NDK function.
func (h *CaptureRequest) RemoveTarget(output *OutputTarget) error {
	return result(capi.ACaptureRequest_removeTarget(h.ptr, output.cptr()))
}
