// Code generated by idiomgen. DO NOT EDIT.

package camera

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/camera"
)

// OutputTarget wraps the NDK ACameraOutputTarget handle.
type OutputTarget struct {
	ptr *capi.ACameraOutputTarget
}


// NewOutputTarget creates a new OutputTarget.
func NewOutputTarget(window *ANativeWindow) (*OutputTarget, error) {
	var ptr *capi.ACameraOutputTarget
	if err := result(int32(capi.ACameraOutputTarget_create(window, &ptr))); err != nil {
		return nil, err
	}
	return &OutputTarget{ptr: ptr}, nil
}



// Close releases the underlying NDK handle.
func (h *OutputTarget) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.ACameraOutputTarget_free(h.ptr)
	h.ptr = nil
	return nil
}


// NewOutputTargetFromPointer wraps a raw ACameraOutputTarget pointer.
func NewOutputTargetFromPointer(ptr unsafe.Pointer) *OutputTarget {
	return &OutputTarget{ptr: (*capi.ACameraOutputTarget)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *OutputTarget) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}


