// Code generated by idiomgen. DO NOT EDIT.

package sensor

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/sensor"
)

// DynamicSensorEvent wraps the NDK ADynamicSensorEvent handle.
type DynamicSensorEvent struct {
	ptr *capi.ADynamicSensorEvent
}

// NewDynamicSensorEventFromPointer wraps a raw ADynamicSensorEvent pointer.
func NewDynamicSensorEventFromPointer(ptr unsafe.Pointer) *DynamicSensorEvent {
	return &DynamicSensorEvent{ptr: (*capi.ADynamicSensorEvent)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *DynamicSensorEvent) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
