// Code generated by idiomgen. DO NOT EDIT.

package sensor

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/sensor"
)

// EventQueue wraps the NDK ASensorEventQueue handle.
type EventQueue struct {
	ptr *capi.ASensorEventQueue
}

// NewEventQueueFromPointer wraps a raw ASensorEventQueue pointer.
func NewEventQueueFromPointer(ptr unsafe.Pointer) *EventQueue {
	return &EventQueue{ptr: (*capi.ASensorEventQueue)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *EventQueue) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// DisableSensor calls the underlying NDK function.
func (h *EventQueue) DisableSensor(sensor *Sensor) error {
	return result(int32(capi.ASensorEventQueue_disableSensor(h.ptr, sensor.ptr)))
}

// EnableSensor calls the underlying NDK function.
func (h *EventQueue) EnableSensor(sensor *Sensor) error {
	return result(int32(capi.ASensorEventQueue_enableSensor(h.ptr, sensor.ptr)))
}

// GetEvents returns the value directly.
func (h *EventQueue) GetEvents(events *SensorEvent, count uint64) int64 {
	return (int64)(capi.ASensorEventQueue_getEvents(h.ptr, events.ptr, count))
}

// HasEvents returns the value directly.
func (h *EventQueue) HasEvents() int32 {
	return (int32)(capi.ASensorEventQueue_hasEvents(h.ptr))
}

// RegisterSensor calls the underlying NDK function.
func (h *EventQueue) RegisterSensor(sensor *Sensor, samplingPeriodUs int32, maxBatchReportLatencyUs int64) error {
	return result(int32(capi.ASensorEventQueue_registerSensor(h.ptr, sensor.ptr, samplingPeriodUs, maxBatchReportLatencyUs)))
}

// RequestAdditionalInfoEvents calls the underlying NDK function.
func (h *EventQueue) RequestAdditionalInfoEvents(enable bool) error {
	return result(int32(capi.ASensorEventQueue_requestAdditionalInfoEvents(h.ptr, enable)))
}

// SetEventRate calls the underlying NDK function.
func (h *EventQueue) SetEventRate(sensor *Sensor, usec int32) error {
	return result(int32(capi.ASensorEventQueue_setEventRate(h.ptr, sensor.ptr, usec)))
}
