// Code generated by idiomgen. DO NOT EDIT.

package sensor

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/sensor"
)

// HardwareBuffer wraps the NDK AHardwareBuffer handle.
type HardwareBuffer struct {
	ptr *capi.AHardwareBuffer
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *HardwareBuffer) cptr() *capi.AHardwareBuffer {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewHardwareBufferFromPointer wraps a raw AHardwareBuffer pointer.
func NewHardwareBufferFromPointer(ptr unsafe.Pointer) *HardwareBuffer {
	return &HardwareBuffer{ptr: (*capi.AHardwareBuffer)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *HardwareBuffer) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *HardwareBuffer) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewHardwareBufferFromUintPtr wraps a uintptr as a HardwareBuffer.
// The caller must ensure ptr points to a valid AHardwareBuffer.
func NewHardwareBufferFromUintPtr(ptr uintptr) *HardwareBuffer {
	return &HardwareBuffer{ptr: (*capi.AHardwareBuffer)(unsafe.Pointer(ptr))}
}
