// Code generated by idiomgen. DO NOT EDIT.

package sensor

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/sensor"
)

// HeadingEvent wraps the NDK AHeadingEvent handle.
type HeadingEvent struct {
	ptr *capi.AHeadingEvent
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *HeadingEvent) cptr() *capi.AHeadingEvent {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewHeadingEventFromPointer wraps a raw AHeadingEvent pointer.
func NewHeadingEventFromPointer(ptr unsafe.Pointer) *HeadingEvent {
	return &HeadingEvent{ptr: (*capi.AHeadingEvent)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *HeadingEvent) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
