// Code generated by idiomgen. DO NOT EDIT.

package sensor

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/sensor"
)

// HeadTrackerEvent wraps the NDK AHeadTrackerEvent handle.
type HeadTrackerEvent struct {
	ptr *capi.AHeadTrackerEvent
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *HeadTrackerEvent) cptr() *capi.AHeadTrackerEvent {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewHeadTrackerEventFromPointer wraps a raw AHeadTrackerEvent pointer.
func NewHeadTrackerEventFromPointer(ptr unsafe.Pointer) *HeadTrackerEvent {
	return &HeadTrackerEvent{ptr: (*capi.AHeadTrackerEvent)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *HeadTrackerEvent) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *HeadTrackerEvent) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewHeadTrackerEventFromUintPtr wraps a uintptr as a HeadTrackerEvent.
// The caller must ensure ptr points to a valid AHeadTrackerEvent.
func NewHeadTrackerEventFromUintPtr(ptr uintptr) *HeadTrackerEvent {
	return &HeadTrackerEvent{ptr: (*capi.AHeadTrackerEvent)(unsafe.Pointer(ptr))}
}
