// Code generated by idiomgen. DO NOT EDIT.

package sensor

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/sensor"
)

// HeartRateEvent wraps the NDK AHeartRateEvent handle.
type HeartRateEvent struct {
	ptr *capi.AHeartRateEvent
}

// NewHeartRateEventFromPointer wraps a raw AHeartRateEvent pointer.
func NewHeartRateEventFromPointer(ptr unsafe.Pointer) *HeartRateEvent {
	return &HeartRateEvent{ptr: (*capi.AHeartRateEvent)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *HeartRateEvent) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
