// Code generated by idiomgen. DO NOT EDIT.

package sensor

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/sensor"
)

// MetaDataEvent wraps the NDK AMetaDataEvent handle.
type MetaDataEvent struct {
	ptr *capi.AMetaDataEvent
}

// NewMetaDataEventFromPointer wraps a raw AMetaDataEvent pointer.
func NewMetaDataEventFromPointer(ptr unsafe.Pointer) *MetaDataEvent {
	return &MetaDataEvent{ptr: (*capi.AMetaDataEvent)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *MetaDataEvent) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
