// Code generated by idiomgen. DO NOT EDIT.

package sensor

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/sensor"
)

// Sensor wraps the NDK ASensor handle.
type Sensor struct {
	ptr *capi.ASensor
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *Sensor) cptr() *capi.ASensor {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewSensorFromPointer wraps a raw ASensor pointer.
func NewSensorFromPointer(ptr unsafe.Pointer) *Sensor {
	return &Sensor{ptr: (*capi.ASensor)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Sensor) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// GetFifoMaxEventCount calls the underlying NDK function.
func (h *Sensor) GetFifoMaxEventCount() error {
	return result(capi.ASensor_getFifoMaxEventCount(h.ptr))
}

// GetFifoReservedEventCount calls the underlying NDK function.
func (h *Sensor) GetFifoReservedEventCount() error {
	return result(capi.ASensor_getFifoReservedEventCount(h.ptr))
}

// GetHandle calls the underlying NDK function.
func (h *Sensor) GetHandle() error {
	return result(capi.ASensor_getHandle(h.ptr))
}

// GetHighestDirectReportRateLevel calls the underlying NDK function.
func (h *Sensor) GetHighestDirectReportRateLevel() error {
	return result(capi.ASensor_getHighestDirectReportRateLevel(h.ptr))
}

// MinDelay returns the value directly.
func (h *Sensor) MinDelay() int32 {
	return (int32)(capi.ASensor_getMinDelay(h.ptr))
}

// Name returns the value directly.
func (h *Sensor) Name() string {
	return (string)(capi.ASensor_getName(h.ptr))
}

// GetReportingMode calls the underlying NDK function.
func (h *Sensor) GetReportingMode() error {
	return result(capi.ASensor_getReportingMode(h.ptr))
}

// Resolution returns the value directly.
func (h *Sensor) Resolution() float32 {
	return (float32)(capi.ASensor_getResolution(h.ptr))
}

// GetStringType returns the value directly.
func (h *Sensor) GetStringType() string {
	return (string)(capi.ASensor_getStringType(h.ptr))
}

// Type returns the value directly.
func (h *Sensor) Type() int32 {
	return (int32)(capi.ASensor_getType(h.ptr))
}

// Vendor returns the value directly.
func (h *Sensor) Vendor() string {
	return (string)(capi.ASensor_getVendor(h.ptr))
}

// IsDirectChannelTypeSupported returns the value directly.
func (h *Sensor) IsDirectChannelTypeSupported(channelType int32) bool {
	return (bool)(capi.ASensor_isDirectChannelTypeSupported(h.ptr, channelType))
}

// IsWakeUpSensor returns the value directly.
func (h *Sensor) IsWakeUpSensor() bool {
	return (bool)(capi.ASensor_isWakeUpSensor(h.ptr))
}
