// Code generated by idiomgen. DO NOT EDIT.

package sensor

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/sensor"
)

// UncalibratedEvent wraps the NDK AUncalibratedEvent handle.
type UncalibratedEvent struct {
	ptr *capi.AUncalibratedEvent
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *UncalibratedEvent) cptr() *capi.AUncalibratedEvent {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewUncalibratedEventFromPointer wraps a raw AUncalibratedEvent pointer.
func NewUncalibratedEventFromPointer(ptr unsafe.Pointer) *UncalibratedEvent {
	return &UncalibratedEvent{ptr: (*capi.AUncalibratedEvent)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *UncalibratedEvent) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *UncalibratedEvent) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewUncalibratedEventFromUintPtr wraps a uintptr as a UncalibratedEvent.
// The caller must ensure ptr points to a valid AUncalibratedEvent.
func NewUncalibratedEventFromUintPtr(ptr uintptr) *UncalibratedEvent {
	return &UncalibratedEvent{ptr: (*capi.AUncalibratedEvent)(unsafe.Pointer(ptr))}
}
