// Code generated by idiomgen. DO NOT EDIT.

package sensor

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/sensor"
)

// UncalibratedEvent wraps the NDK AUncalibratedEvent handle.
type UncalibratedEvent struct {
	ptr *capi.AUncalibratedEvent
}

// NewUncalibratedEventFromPointer wraps a raw AUncalibratedEvent pointer.
func NewUncalibratedEventFromPointer(ptr unsafe.Pointer) *UncalibratedEvent {
	return &UncalibratedEvent{ptr: (*capi.AUncalibratedEvent)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *UncalibratedEvent) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
