// Code generated by capigen. DO NOT EDIT.

package sensor

/*
#cgo LDFLAGS: -landroid
#include "android/sensor.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

var _ runtime.Error
var _ unsafe.Pointer

func ASensorEventQueue_disableSensor(queue *ASensorEventQueue, sensor *ASensor) int32 {
	cqueue, cqueueAllocMap := (*C.ASensorEventQueue)(unsafe.Pointer(queue)), cgoAllocsUnknown
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	__ret := C.ASensorEventQueue_disableSensor(cqueue, csensor)
	runtime.KeepAlive(csensorAllocMap)
	runtime.KeepAlive(cqueueAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensorEventQueue_enableSensor(queue *ASensorEventQueue, sensor *ASensor) int32 {
	cqueue, cqueueAllocMap := (*C.ASensorEventQueue)(unsafe.Pointer(queue)), cgoAllocsUnknown
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	__ret := C.ASensorEventQueue_enableSensor(cqueue, csensor)
	runtime.KeepAlive(csensorAllocMap)
	runtime.KeepAlive(cqueueAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensorEventQueue_getEvents(queue *ASensorEventQueue, events *ASensorEvent, count uint64) int64 {
	cqueue, cqueueAllocMap := (*C.ASensorEventQueue)(unsafe.Pointer(queue)), cgoAllocsUnknown
	cevents, ceventsAllocMap := (*C.ASensorEvent)(unsafe.Pointer(events)), cgoAllocsUnknown
	ccount, ccountAllocMap := (C.uint64_t)(count), cgoAllocsUnknown
	__ret := C.ASensorEventQueue_getEvents(cqueue, cevents, ccount)
	runtime.KeepAlive(ccountAllocMap)
	runtime.KeepAlive(ceventsAllocMap)
	runtime.KeepAlive(cqueueAllocMap)
	__v := (int64)(__ret)
	return __v
}

func ASensorEventQueue_hasEvents(queue *ASensorEventQueue) int32 {
	cqueue, cqueueAllocMap := (*C.ASensorEventQueue)(unsafe.Pointer(queue)), cgoAllocsUnknown
	__ret := C.ASensorEventQueue_hasEvents(cqueue)
	runtime.KeepAlive(cqueueAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensorEventQueue_registerSensor(queue *ASensorEventQueue, sensor *ASensor, samplingPeriodUs int32, maxBatchReportLatencyUs int64) int32 {
	cqueue, cqueueAllocMap := (*C.ASensorEventQueue)(unsafe.Pointer(queue)), cgoAllocsUnknown
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	csamplingPeriodUs, csamplingPeriodUsAllocMap := (C.int)(samplingPeriodUs), cgoAllocsUnknown
	cmaxBatchReportLatencyUs, cmaxBatchReportLatencyUsAllocMap := (C.int64_t)(maxBatchReportLatencyUs), cgoAllocsUnknown
	__ret := C.ASensorEventQueue_registerSensor(cqueue, csensor, csamplingPeriodUs, cmaxBatchReportLatencyUs)
	runtime.KeepAlive(cmaxBatchReportLatencyUsAllocMap)
	runtime.KeepAlive(csamplingPeriodUsAllocMap)
	runtime.KeepAlive(csensorAllocMap)
	runtime.KeepAlive(cqueueAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensorEventQueue_requestAdditionalInfoEvents(queue *ASensorEventQueue, enable bool) int32 {
	cqueue, cqueueAllocMap := (*C.ASensorEventQueue)(unsafe.Pointer(queue)), cgoAllocsUnknown
	cenable, cenableAllocMap := (C._Bool)(enable), cgoAllocsUnknown
	__ret := C.ASensorEventQueue_requestAdditionalInfoEvents(cqueue, cenable)
	runtime.KeepAlive(cenableAllocMap)
	runtime.KeepAlive(cqueueAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensorEventQueue_setEventRate(queue *ASensorEventQueue, sensor *ASensor, usec int32) int32 {
	cqueue, cqueueAllocMap := (*C.ASensorEventQueue)(unsafe.Pointer(queue)), cgoAllocsUnknown
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	cusec, cusecAllocMap := (C.int)(usec), cgoAllocsUnknown
	__ret := C.ASensorEventQueue_setEventRate(cqueue, csensor, cusec)
	runtime.KeepAlive(cusecAllocMap)
	runtime.KeepAlive(csensorAllocMap)
	runtime.KeepAlive(cqueueAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensorManager_configureDirectReport(manager *ASensorManager, sensor *ASensor, channelId int32, rate int32) int32 {
	cmanager, cmanagerAllocMap := (*C.ASensorManager)(unsafe.Pointer(manager)), cgoAllocsUnknown
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	cchannelId, cchannelIdAllocMap := (C.int)(channelId), cgoAllocsUnknown
	crate, crateAllocMap := (C.int)(rate), cgoAllocsUnknown
	__ret := C.ASensorManager_configureDirectReport(cmanager, csensor, cchannelId, crate)
	runtime.KeepAlive(crateAllocMap)
	runtime.KeepAlive(cchannelIdAllocMap)
	runtime.KeepAlive(csensorAllocMap)
	runtime.KeepAlive(cmanagerAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensorManager_createEventQueue(manager *ASensorManager, looper *ALooper, ident int32, callback ALooper_callbackFunc, data unsafe.Pointer) *ASensorEventQueue {
	cmanager, cmanagerAllocMap := (*C.ASensorManager)(unsafe.Pointer(manager)), cgoAllocsUnknown
	clooper, clooperAllocMap := (*C.ALooper)(unsafe.Pointer(looper)), cgoAllocsUnknown
	cident, cidentAllocMap := (C.int)(ident), cgoAllocsUnknown
	ccallback, ccallbackAllocMap := (C.ALooper_callbackFunc)(callback), cgoAllocsUnknown
	cdata, cdataAllocMap := data, cgoAllocsUnknown
	__ret := C.ASensorManager_createEventQueue(cmanager, clooper, cident, ccallback, cdata)
	runtime.KeepAlive(cdataAllocMap)
	runtime.KeepAlive(ccallbackAllocMap)
	runtime.KeepAlive(cidentAllocMap)
	runtime.KeepAlive(clooperAllocMap)
	runtime.KeepAlive(cmanagerAllocMap)
	__v := *(**ASensorEventQueue)(unsafe.Pointer(&__ret))
	return __v
}

func ASensorManager_createHardwareBufferDirectChannel(manager *ASensorManager, buffer *AHardwareBuffer, size uint64) int32 {
	cmanager, cmanagerAllocMap := (*C.ASensorManager)(unsafe.Pointer(manager)), cgoAllocsUnknown
	cbuffer, cbufferAllocMap := (*C.AHardwareBuffer)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	csize, csizeAllocMap := (C.uint64_t)(size), cgoAllocsUnknown
	__ret := C.ASensorManager_createHardwareBufferDirectChannel(cmanager, cbuffer, csize)
	runtime.KeepAlive(csizeAllocMap)
	runtime.KeepAlive(cbufferAllocMap)
	runtime.KeepAlive(cmanagerAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensorManager_createSharedMemoryDirectChannel(manager *ASensorManager, fd int32, size uint64) int32 {
	cmanager, cmanagerAllocMap := (*C.ASensorManager)(unsafe.Pointer(manager)), cgoAllocsUnknown
	cfd, cfdAllocMap := (C.int)(fd), cgoAllocsUnknown
	csize, csizeAllocMap := (C.uint64_t)(size), cgoAllocsUnknown
	__ret := C.ASensorManager_createSharedMemoryDirectChannel(cmanager, cfd, csize)
	runtime.KeepAlive(csizeAllocMap)
	runtime.KeepAlive(cfdAllocMap)
	runtime.KeepAlive(cmanagerAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensorManager_destroyDirectChannel(manager *ASensorManager, channelId int32) {
	cmanager, cmanagerAllocMap := (*C.ASensorManager)(unsafe.Pointer(manager)), cgoAllocsUnknown
	cchannelId, cchannelIdAllocMap := (C.int)(channelId), cgoAllocsUnknown
	C.ASensorManager_destroyDirectChannel(cmanager, cchannelId)
	runtime.KeepAlive(cchannelIdAllocMap)
	runtime.KeepAlive(cmanagerAllocMap)
}

func ASensorManager_destroyEventQueue(manager *ASensorManager, queue *ASensorEventQueue) int32 {
	cmanager, cmanagerAllocMap := (*C.ASensorManager)(unsafe.Pointer(manager)), cgoAllocsUnknown
	cqueue, cqueueAllocMap := (*C.ASensorEventQueue)(unsafe.Pointer(queue)), cgoAllocsUnknown
	__ret := C.ASensorManager_destroyEventQueue(cmanager, cqueue)
	runtime.KeepAlive(cqueueAllocMap)
	runtime.KeepAlive(cmanagerAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensorManager_getDefaultSensor(manager *ASensorManager, _type int32) *ASensor {
	cmanager, cmanagerAllocMap := (*C.ASensorManager)(unsafe.Pointer(manager)), cgoAllocsUnknown
	c_type, c_typeAllocMap := (C.int)(_type), cgoAllocsUnknown
	__ret := C.ASensorManager_getDefaultSensor(cmanager, c_type)
	runtime.KeepAlive(c_typeAllocMap)
	runtime.KeepAlive(cmanagerAllocMap)
	__v := *(**ASensor)(unsafe.Pointer(&__ret))
	return __v
}

func ASensorManager_getDefaultSensorEx(manager *ASensorManager, _type int32, wakeUp bool) *ASensor {
	cmanager, cmanagerAllocMap := (*C.ASensorManager)(unsafe.Pointer(manager)), cgoAllocsUnknown
	c_type, c_typeAllocMap := (C.int)(_type), cgoAllocsUnknown
	cwakeUp, cwakeUpAllocMap := (C._Bool)(wakeUp), cgoAllocsUnknown
	__ret := C.ASensorManager_getDefaultSensorEx(cmanager, c_type, cwakeUp)
	runtime.KeepAlive(cwakeUpAllocMap)
	runtime.KeepAlive(c_typeAllocMap)
	runtime.KeepAlive(cmanagerAllocMap)
	__v := *(**ASensor)(unsafe.Pointer(&__ret))
	return __v
}

func ASensorManager_getDynamicSensorList(manager *ASensorManager, list *ASensorList) int64 {
	cmanager, cmanagerAllocMap := (*C.ASensorManager)(unsafe.Pointer(manager)), cgoAllocsUnknown
	clist, clistAllocMap := (*C.ASensorList)(unsafe.Pointer(list)), cgoAllocsUnknown
	__ret := C.ASensorManager_getDynamicSensorList(cmanager, clist)
	runtime.KeepAlive(clistAllocMap)
	runtime.KeepAlive(cmanagerAllocMap)
	__v := (int64)(__ret)
	return __v
}

func ASensorManager_getInstance() *ASensorManager {
	__ret := C.ASensorManager_getInstance()
	__v := *(**ASensorManager)(unsafe.Pointer(&__ret))
	return __v
}

func ASensorManager_getInstanceForPackage(packageName string) *ASensorManager {
	cpackageName, cpackageNameAllocMap := UnpackPCharString(packageName)
	__ret := C.ASensorManager_getInstanceForPackage(cpackageName)
	runtime.KeepAlive(cpackageNameAllocMap)
	__v := *(**ASensorManager)(unsafe.Pointer(&__ret))
	return __v
}

func ASensorManager_getSensorList(manager *ASensorManager, list *ASensorList) int32 {
	cmanager, cmanagerAllocMap := (*C.ASensorManager)(unsafe.Pointer(manager)), cgoAllocsUnknown
	clist, clistAllocMap := (*C.ASensorList)(unsafe.Pointer(list)), cgoAllocsUnknown
	__ret := C.ASensorManager_getSensorList(cmanager, clist)
	runtime.KeepAlive(clistAllocMap)
	runtime.KeepAlive(cmanagerAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensor_getFifoMaxEventCount(sensor *ASensor) int32 {
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	__ret := C.ASensor_getFifoMaxEventCount(csensor)
	runtime.KeepAlive(csensorAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensor_getFifoReservedEventCount(sensor *ASensor) int32 {
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	__ret := C.ASensor_getFifoReservedEventCount(csensor)
	runtime.KeepAlive(csensorAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensor_getHandle(sensor *ASensor) int32 {
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	__ret := C.ASensor_getHandle(csensor)
	runtime.KeepAlive(csensorAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensor_getHighestDirectReportRateLevel(sensor *ASensor) int32 {
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	__ret := C.ASensor_getHighestDirectReportRateLevel(csensor)
	runtime.KeepAlive(csensorAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensor_getMinDelay(sensor *ASensor) int32 {
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	__ret := C.ASensor_getMinDelay(csensor)
	runtime.KeepAlive(csensorAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensor_getName(sensor *ASensor) string {
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	__ret := C.ASensor_getName(csensor)
	runtime.KeepAlive(csensorAllocMap)
	__v := C.GoString(__ret)
	return __v
}

func ASensor_getReportingMode(sensor *ASensor) int32 {
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	__ret := C.ASensor_getReportingMode(csensor)
	runtime.KeepAlive(csensorAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensor_getResolution(sensor *ASensor) float32 {
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	__ret := C.ASensor_getResolution(csensor)
	runtime.KeepAlive(csensorAllocMap)
	__v := (float32)(__ret)
	return __v
}

func ASensor_getStringType(sensor *ASensor) string {
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	__ret := C.ASensor_getStringType(csensor)
	runtime.KeepAlive(csensorAllocMap)
	__v := C.GoString(__ret)
	return __v
}

func ASensor_getType(sensor *ASensor) int32 {
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	__ret := C.ASensor_getType(csensor)
	runtime.KeepAlive(csensorAllocMap)
	__v := (int32)(__ret)
	return __v
}

func ASensor_getVendor(sensor *ASensor) string {
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	__ret := C.ASensor_getVendor(csensor)
	runtime.KeepAlive(csensorAllocMap)
	__v := C.GoString(__ret)
	return __v
}

func ASensor_isDirectChannelTypeSupported(sensor *ASensor, channelType int32) bool {
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	cchannelType, cchannelTypeAllocMap := (C.int)(channelType), cgoAllocsUnknown
	__ret := C.ASensor_isDirectChannelTypeSupported(csensor, cchannelType)
	runtime.KeepAlive(cchannelTypeAllocMap)
	runtime.KeepAlive(csensorAllocMap)
	__v := (bool)(__ret)
	return __v
}

func ASensor_isWakeUpSensor(sensor *ASensor) bool {
	csensor, csensorAllocMap := (*C.ASensor)(unsafe.Pointer(sensor)), cgoAllocsUnknown
	__ret := C.ASensor_isWakeUpSensor(csensor)
	runtime.KeepAlive(csensorAllocMap)
	__v := (bool)(__ret)
	return __v
}
