// Code generated by idiomgen. DO NOT EDIT.

package hwbuf

import (
	capi "github.com/AndroidGoLab/ndk/capi/hardwarebuffer"
)

// Allocate calls the underlying C function.
func Allocate(desc *Desc) (*Buffer, error) {
	var outBufferPtr *capi.AHardwareBuffer
	ret := capi.AHardwareBuffer_allocate(desc.cptr(), &outBufferPtr)
	if err := result(int32(ret)); err != nil {
		return nil, err
	}
	return &Buffer{ptr: outBufferPtr}, nil
}

// IsSupported calls the underlying C function.
func IsSupported(desc *Desc) int32 {
	return (int32)(capi.AHardwareBuffer_isSupported(desc.cptr()))
}

// RecvHandleFromUnixSocket calls the underlying C function.
func RecvHandleFromUnixSocket(socketFd int32) (*Buffer, error) {
	var outBufferPtr *capi.AHardwareBuffer
	ret := capi.AHardwareBuffer_recvHandleFromUnixSocket(socketFd, &outBufferPtr)
	if err := result(int32(ret)); err != nil {
		return nil, err
	}
	return &Buffer{ptr: outBufferPtr}, nil
}
