// Code generated by idiomgen. DO NOT EDIT.

package hwbuf

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/hardwarebuffer"
)

// HardwareBuffer_Planes wraps the NDK AHardwareBuffer_Planes handle.
type HardwareBuffer_Planes struct {
	ptr *capi.AHardwareBuffer_Planes
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *HardwareBuffer_Planes) cptr() *capi.AHardwareBuffer_Planes {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewHardwareBuffer_PlanesFromPointer wraps a raw AHardwareBuffer_Planes pointer.
func NewHardwareBuffer_PlanesFromPointer(ptr unsafe.Pointer) *HardwareBuffer_Planes {
	return &HardwareBuffer_Planes{ptr: (*capi.AHardwareBuffer_Planes)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *HardwareBuffer_Planes) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *HardwareBuffer_Planes) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewHardwareBuffer_PlanesFromUintPtr wraps a uintptr as a HardwareBuffer_Planes.
// The caller must ensure ptr points to a valid AHardwareBuffer_Planes.
func NewHardwareBuffer_PlanesFromUintPtr(ptr uintptr) *HardwareBuffer_Planes {
	return &HardwareBuffer_Planes{ptr: (*capi.AHardwareBuffer_Planes)(unsafe.Pointer(ptr))}
}
