// Code generated by idiomgen. DO NOT EDIT.

package hwbuf

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/hardwarebuffer"
)

// HardwareBuffer_Desc wraps the NDK AHardwareBuffer_Desc handle.
type HardwareBuffer_Desc struct {
	ptr *capi.AHardwareBuffer_Desc
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *HardwareBuffer_Desc) cptr() *capi.AHardwareBuffer_Desc {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewHardwareBuffer_DescFromPointer wraps a raw AHardwareBuffer_Desc pointer.
func NewHardwareBuffer_DescFromPointer(ptr unsafe.Pointer) *HardwareBuffer_Desc {
	return &HardwareBuffer_Desc{ptr: (*capi.AHardwareBuffer_Desc)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *HardwareBuffer_Desc) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *HardwareBuffer_Desc) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewHardwareBuffer_DescFromUintPtr wraps a uintptr as a HardwareBuffer_Desc.
// The caller must ensure ptr points to a valid AHardwareBuffer_Desc.
func NewHardwareBuffer_DescFromUintPtr(ptr uintptr) *HardwareBuffer_Desc {
	return &HardwareBuffer_Desc{ptr: (*capi.AHardwareBuffer_Desc)(unsafe.Pointer(ptr))}
}
