// Code generated by idiomgen. DO NOT EDIT.

package hwbuf

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/hardwarebuffer"
)

// HardwareBuffer_Plane wraps the NDK AHardwareBuffer_Plane handle.
type HardwareBuffer_Plane struct {
	ptr *capi.AHardwareBuffer_Plane
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *HardwareBuffer_Plane) cptr() *capi.AHardwareBuffer_Plane {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewHardwareBuffer_PlaneFromPointer wraps a raw AHardwareBuffer_Plane pointer.
func NewHardwareBuffer_PlaneFromPointer(ptr unsafe.Pointer) *HardwareBuffer_Plane {
	return &HardwareBuffer_Plane{ptr: (*capi.AHardwareBuffer_Plane)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *HardwareBuffer_Plane) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *HardwareBuffer_Plane) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewHardwareBuffer_PlaneFromUintPtr wraps a uintptr as a HardwareBuffer_Plane.
// The caller must ensure ptr points to a valid AHardwareBuffer_Plane.
func NewHardwareBuffer_PlaneFromUintPtr(ptr uintptr) *HardwareBuffer_Plane {
	return &HardwareBuffer_Plane{ptr: (*capi.AHardwareBuffer_Plane)(unsafe.Pointer(ptr))}
}
