// Code generated by idiomgen. DO NOT EDIT.

package hwbuf

type Usage uint64

const (
	CpuReadNever      Usage = 0
	CpuReadRarely     Usage = 2
	CpuReadOften      Usage = 3
	CpuReadMask       Usage = 15
	CpuWriteNever     Usage = 0
	CpuWriteRarely    Usage = 32
	CpuWriteOften     Usage = 48
	CpuWriteMask      Usage = 240
	GpuSampledImage   Usage = 256
	GpuFramebuffer    Usage = 512
	GpuColorOutput    Usage = 512
	ComposerOverlay   Usage = 2048
	ProtectedContent  Usage = 16384
	VideoEncode       Usage = 65536
	SensorDirectData  Usage = 8388608
	GpuDataBuffer     Usage = 16777216
	GpuCubeMap        Usage = 33554432
	GpuMipmapComplete Usage = 67108864
	FrontBuffer       Usage = 4294967296
	Vendor0           Usage = 268435456
	Vendor1           Usage = 536870912
	Vendor2           Usage = 1073741824
	Vendor3           Usage = 0xFFFFFFFF80000000
	Vendor4           Usage = 281474976710656
	Vendor5           Usage = 562949953421312
	Vendor6           Usage = 1125899906842624
	Vendor7           Usage = 2251799813685248
	Vendor8           Usage = 4503599627370496
	Vendor9           Usage = 9007199254740992
	Vendor10          Usage = 18014398509481984
	Vendor11          Usage = 36028797018963968
	Vendor12          Usage = 72057594037927936
	Vendor13          Usage = 144115188075855872
	Vendor14          Usage = 288230376151711744
	Vendor15          Usage = 576460752303423488
	Vendor16          Usage = 1152921504606846976
	Vendor17          Usage = 2305843009213693952
	Vendor18          Usage = 4611686018427387904
	Vendor19          Usage = 0x8000000000000000
)
