// Code generated by capigen. DO NOT EDIT.

package aaudio

/*
#cgo LDFLAGS: -laaudio
#include "aaudio/AAudio.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

type AAudioStream C.AAudioStream

type AAudioStreamBuilder C.AAudioStreamBuilder

type Aaudio_allowed_capture_policy_t int32

type Aaudio_channel_mask_t uint32

type Aaudio_content_type_t int32

type Aaudio_data_callback_result_t int32

type Aaudio_direction_t int32

type Aaudio_format_t int32

type Aaudio_input_preset_t int32

type Aaudio_performance_mode_t int32

type Aaudio_result_t int32

type Aaudio_session_id_t int32

type Aaudio_sharing_mode_t int32

type Aaudio_spatialization_behavior_t int32

type Aaudio_stream_state_t int32

type Aaudio_usage_t int32

type Clockid_t C.clockid_t

type AAudioStream_dataCallback func(stream *AAudioStream, userData unsafe.Pointer, audioData unsafe.Pointer, numFrames int32) Aaudio_data_callback_result_t

type AAudioStream_errorCallback func(stream *AAudioStream, userData unsafe.Pointer, _error Aaudio_result_t)
