// Code generated by idiomgen. DO NOT EDIT.

package binder

import (
	capi "github.com/AndroidGoLab/ndk/capi/binder"
)

type AIBinder_DeathRecipient_onBinderUnlinked = capi.AIBinder_DeathRecipient_onBinderUnlinked
