// Code generated by idiomgen. DO NOT EDIT.

package binder

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/binder"
)

// Class wraps the NDK AIBinder_Class handle.
type Class struct {
	ptr *capi.AIBinder_Class
}

// NewClassFromPointer wraps a raw AIBinder_Class pointer.
func NewClassFromPointer(ptr unsafe.Pointer) *Class {
	return &Class{ptr: (*capi.AIBinder_Class)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *Class) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
