// Code generated by idiomgen. DO NOT EDIT.

package binder

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/binder"
)

// IBinder_DeathRecipient wraps the NDK AIBinder_DeathRecipient handle.
type IBinder_DeathRecipient struct {
	ptr *capi.AIBinder_DeathRecipient
}

// NewIBinder_DeathRecipient creates a new IBinder_DeathRecipient.
func NewIBinder_DeathRecipient(onBinderDied AIBinder_DeathRecipient_onBinderDied) *IBinder_DeathRecipient {
	return &IBinder_DeathRecipient{ptr: capi.AIBinder_DeathRecipient_new(onBinderDied)}
}

// Close releases the underlying NDK handle.
func (h *IBinder_DeathRecipient) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.AIBinder_DeathRecipient_delete(h.ptr)
	h.ptr = nil
	return nil
}

// NewIBinder_DeathRecipientFromPointer wraps a raw AIBinder_DeathRecipient pointer.
func NewIBinder_DeathRecipientFromPointer(ptr unsafe.Pointer) *IBinder_DeathRecipient {
	return &IBinder_DeathRecipient{ptr: (*capi.AIBinder_DeathRecipient)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *IBinder_DeathRecipient) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
