// Code generated by idiomgen. DO NOT EDIT.

package activity

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/nativeactivity"
)

// NativeActivityCallbacks wraps the NDK ANativeActivityCallbacks handle.
type NativeActivityCallbacks struct {
	ptr *capi.ANativeActivityCallbacks
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *NativeActivityCallbacks) cptr() *capi.ANativeActivityCallbacks {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewNativeActivityCallbacksFromPointer wraps a raw ANativeActivityCallbacks pointer.
func NewNativeActivityCallbacksFromPointer(ptr unsafe.Pointer) *NativeActivityCallbacks {
	return &NativeActivityCallbacks{ptr: (*capi.ANativeActivityCallbacks)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *NativeActivityCallbacks) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
