// Code generated by capigen. DO NOT EDIT.

package midi

/*
#cgo LDFLAGS: -lamidi
#include "amidi/AMidi.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

type AMidiDevice C.AMidiDevice

type AMidiDevice_Protocol int32

type AMidiInputPort C.AMidiInputPort

type AMidiOutputPort C.AMidiOutputPort

type JNIEnv C.JNIEnv

type Jobject C.jobject

type Media_status_t C.media_status_t
