// Code generated by idiomgen. DO NOT EDIT.

package image

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/imagedecoder"
)

// AssetDir wraps the NDK AAssetDir handle.
type AssetDir struct {
	ptr *capi.AAssetDir
}

// Close releases the underlying NDK handle.
func (h *AssetDir) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.AAssetDir_close(h.ptr)
	h.ptr = nil
	return nil
}

// NewAssetDirFromPointer wraps a raw AAssetDir pointer.
func NewAssetDirFromPointer(ptr unsafe.Pointer) *AssetDir {
	return &AssetDir{ptr: (*capi.AAssetDir)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *AssetDir) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// GetNextFileName returns the value directly.
func (h *AssetDir) GetNextFileName() string {
	return (string)(capi.AAssetDir_getNextFileName(h.ptr))
}

// Rewind calls the underlying NDK function.
func (h *AssetDir) Rewind() {
	capi.AAssetDir_rewind(h.ptr)
}
