// Code generated by idiomgen. DO NOT EDIT.

package image

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/imagedecoder"
)

// AssetDir wraps the NDK AAssetDir handle.
type AssetDir struct {
	ptr *capi.AAssetDir
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *AssetDir) cptr() *capi.AAssetDir {
	if h == nil {
		return nil
	}
	return h.ptr
}

// Close releases the underlying NDK handle.
func (h *AssetDir) Close() error {
	if h.ptr == nil {
		return nil
	}
	capi.AAssetDir_close(h.ptr)
	h.ptr = nil
	return nil
}

// NewAssetDirFromPointer wraps a raw AAssetDir pointer.
func NewAssetDirFromPointer(ptr unsafe.Pointer) *AssetDir {
	return &AssetDir{ptr: (*capi.AAssetDir)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *AssetDir) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *AssetDir) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewAssetDirFromUintPtr wraps a uintptr as a AssetDir.
// The caller must ensure ptr points to a valid AAssetDir.
func NewAssetDirFromUintPtr(ptr uintptr) *AssetDir {
	return &AssetDir{ptr: (*capi.AAssetDir)(unsafe.Pointer(ptr))}
}

// GetNextFileName returns the value directly.
func (h *AssetDir) GetNextFileName() string {
	return (string)(capi.AAssetDir_getNextFileName(h.ptr))
}

// Rewind calls the underlying NDK function.
func (h *AssetDir) Rewind() {
	capi.AAssetDir_rewind(h.ptr)
}
