// Code generated by idiomgen. DO NOT EDIT.

package image

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/imagedecoder"
)

// AssetManager wraps the NDK AAssetManager handle.
type AssetManager struct {
	ptr *capi.AAssetManager
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *AssetManager) cptr() *capi.AAssetManager {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewAssetManagerFromPointer wraps a raw AAssetManager pointer.
func NewAssetManagerFromPointer(ptr unsafe.Pointer) *AssetManager {
	return &AssetManager{ptr: (*capi.AAssetManager)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *AssetManager) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// Open creates a new Asset from this AssetManager.
func (h *AssetManager) Open(filename string, mode int32) *Asset {
	return &Asset{ptr: capi.AAssetManager_open(h.ptr, filename, mode)}
}

// OpenDir creates a new AssetDir from this AssetManager.
func (h *AssetManager) OpenDir(dirName string) *AssetDir {
	return &AssetDir{ptr: capi.AAssetManager_openDir(h.ptr, dirName)}
}
