// Code generated by idiomgen. DO NOT EDIT.

package image

import (
	capi "github.com/xaionaro-go/ndk/capi/imagedecoder"
)

// AImageDecoder_resultToString calls the underlying C function.
func AImageDecoder_resultToString(arg0 int32) string {
	return (string)(capi.AImageDecoder_resultToString(arg0))
}
