// Code generated by idiomgen. DO NOT EDIT.

package image

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/imagedecoder"
)

// HeaderInfo wraps the NDK AImageDecoderHeaderInfo handle.
type HeaderInfo struct {
	ptr *capi.AImageDecoderHeaderInfo
}

// NewHeaderInfoFromPointer wraps a raw AImageDecoderHeaderInfo pointer.
func NewHeaderInfoFromPointer(ptr unsafe.Pointer) *HeaderInfo {
	return &HeaderInfo{ptr: (*capi.AImageDecoderHeaderInfo)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *HeaderInfo) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}
