// Code generated by idiomgen. DO NOT EDIT.

package image

import (
	"unsafe"

	capi "github.com/xaionaro-go/ndk/capi/imagedecoder"
)

// HeaderInfo wraps the NDK AImageDecoderHeaderInfo handle.
type HeaderInfo struct {
	ptr *capi.AImageDecoderHeaderInfo
}

// NewHeaderInfoFromPointer wraps a raw AImageDecoderHeaderInfo pointer.
func NewHeaderInfoFromPointer(ptr unsafe.Pointer) *HeaderInfo {
	return &HeaderInfo{ptr: (*capi.AImageDecoderHeaderInfo)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *HeaderInfo) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// GetAlphaFlags calls the underlying NDK function.
func (h *HeaderInfo) GetAlphaFlags() error {
	return result(int32(capi.AImageDecoderHeaderInfo_getAlphaFlags(h.ptr)))
}

// GetAndroidBitmapFormat calls the underlying NDK function.
func (h *HeaderInfo) GetAndroidBitmapFormat() error {
	return result(int32(capi.AImageDecoderHeaderInfo_getAndroidBitmapFormat(h.ptr)))
}

// GetDataSpace calls the underlying NDK function.
func (h *HeaderInfo) GetDataSpace() error {
	return result(int32(capi.AImageDecoderHeaderInfo_getDataSpace(h.ptr)))
}

// Height returns the value directly.
func (h *HeaderInfo) Height() int32 {
	return (int32)(capi.AImageDecoderHeaderInfo_getHeight(h.ptr))
}

// MimeType returns the value directly.
func (h *HeaderInfo) MimeType() string {
	return (string)(capi.AImageDecoderHeaderInfo_getMimeType(h.ptr))
}

// Width returns the value directly.
func (h *HeaderInfo) Width() int32 {
	return (int32)(capi.AImageDecoderHeaderInfo_getWidth(h.ptr))
}
