// Code generated by idiomgen. DO NOT EDIT.

package bitmap

import (
	"unsafe"

	capi "github.com/AndroidGoLab/ndk/capi/bitmap"
)

// AndroidBitmapInfo wraps the NDK AndroidBitmapInfo handle.
type AndroidBitmapInfo struct {
	ptr *capi.AndroidBitmapInfo
}

// cptr returns the underlying C pointer, or nil if h is nil.
// This allows passing optional (nullable) handle parameters to capi functions.
func (h *AndroidBitmapInfo) cptr() *capi.AndroidBitmapInfo {
	if h == nil {
		return nil
	}
	return h.ptr
}

// NewAndroidBitmapInfoFromPointer wraps a raw AndroidBitmapInfo pointer.
func NewAndroidBitmapInfoFromPointer(ptr unsafe.Pointer) *AndroidBitmapInfo {
	return &AndroidBitmapInfo{ptr: (*capi.AndroidBitmapInfo)(ptr)}
}

// Pointer returns the underlying pointer as unsafe.Pointer.
func (h *AndroidBitmapInfo) Pointer() unsafe.Pointer {
	return unsafe.Pointer(h.ptr)
}

// UintPtr returns the underlying pointer as a uintptr.
// This is useful for interop with gomobile bind, golang.org/x/mobile,
// gioui.org, and other packages that represent native handles as uintptr.
func (h *AndroidBitmapInfo) UintPtr() uintptr {
	return uintptr(unsafe.Pointer(h.ptr))
}

// NewAndroidBitmapInfoFromUintPtr wraps a uintptr as a AndroidBitmapInfo.
// The caller must ensure ptr points to a valid AndroidBitmapInfo.
func NewAndroidBitmapInfoFromUintPtr(ptr uintptr) *AndroidBitmapInfo {
	return &AndroidBitmapInfo{ptr: (*capi.AndroidBitmapInfo)(unsafe.Pointer(ptr))}
}
